### ISSUE TITLE
Chromebook Screen Flickering Issues

### ISSUE THREAD

**Issue by Nonary** [LizardByte/Sunshine#1042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Chromebooks have issues with Sunshines low framerate when displaying static content, it almost seems like it is dynamically adjusting the displays framerate instead of remaining fixed. So it's technically not an issue with Sunshine itself, but rather the 10fps limit of Sunshine causes Chromebooks to break.

This is mentioned in #988 and #1009 but I am re-opening this issue as it cannot be resolved without changing Sunshines code.

### Expected Behavior

Increase default fps from 10 to 20? A user confirmed that it fixed their problem when doing that.

### Host Operating System

other, n/a

### Operating System Version

N/A

### Architecture

64 bit

### Sunshine commit or version

0.18.4

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

N/A

### GPU Driver/Mesa Version

N/A

### Config

```Shell
N/A
```

### Relevant log output

```shell
N/A
```

**Comment by ReenigneArcher** [comment]
I'll make it a configurable option

**Comment by Nonary** [comment]
> 



> I'll make it a configurable option

Great minds think alike, that sounds like a great idea.
We've had people ask for changing that minimum for awhile, like some people prefer it being 60fps at all times.

I have also noticed audio issues with the lower framerates, wonder if those will go away if we allow it to be configurable and set it to something higher for example.
