### ISSUE TITLE
sunshine switch monitor shortcut supports gamepad

### ISSUE THREAD

**Issue by zph308** [LizardByte/Sunshine#1047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I did not find how to use the controller to switch monitor,
now the document only has switching monitor using the keyboard:
CTRL + ALT + SHIFT + F1/F12 - Switch to different monitor for Streaming

### Expected Behavior

Support using game controller to quickly switch monitor

### Host Operating System

Windows

### Operating System Version

11

### Architecture

64 bit

### Sunshine commit or version

0.18.4

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

N/A

### GPU Driver/Mesa Version

N/A

### Config

```Shell
N/A
```

### Relevant log output

```shell
N/A
```

**Comment by ReenigneArcher** [comment]
Did you find a solution to this?

**Comment by zph308** [comment]
> Did you find a solution to this?

no,I mapped keyboard hotkeys using driver settings provided by a third-party gamepad
