### ISSUE TITLE
/applist URL parameter compatibility with Moonlight

### ISSUE THREAD

**Issue by Macellatore** [LizardByte/Sunshine#1068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I think the URL parameter /applist is not compatible with Moonlight, or better, i think it does not emulate Moonlight's behaviour correctly.

I'm using [Recalbox](https://www.recalbox.com/) on my raspberry pi which uses the xml returned by /applist to build its interface games list.
I haven't tried it on Moonlight as i don't have a nvidia card, but given that people use it, i suppose it works.

This is the URL that Recalbox calls:
`https://<server-ip>:47984/applist?unique_id=<ID>&uuid=<UUID>`

and Sunshine answers with:
```
<?xml version="1.0" encoding="utf-8"?>
<root status_code="400"/>

```
If i change the "unique_id" parameter to "uniqueid", Sunshine gives the proper answer:

```
<?xml version="1.0" encoding="utf-8"?>
<root status_code="200"><App><IsHdrSupported>0</IsHdrSupported><AppTitle>Steam BigPicture</AppTitle><ID>1260880620</ID></App></root>
```

Moreover (but i can't confirm it yet, i'll get back with more info as soon as i can get them), still judging by [Recalbox code](https://gitlab.com/recalbox/recalbox/-/tree/master/board/recalbox/fsoverlay/recalbox/scripts/moonlight), i think Moonlight might expose more game details in the xml.

### Host Operating System

Windows

### Operating System Version

Windows 10

### Architecture

64 bit

### Sunshine commit or version

0.18.04

### Package

Windows - installer

### GPU Type

AMD

### GPU Model

RX480

### GPU Driver/Mesa Version

23.3.1

### Config

```Shell
key_rightalt_to_key_win = disabled
gamepad = x360
upnp = disabled
dwmflush = enabled
min_log_level = 2
origin_pin_allowed = pc
origin_web_ui_allowed = lan
hevc_mode = 0
nv_preset = p4
nv_tune = ull
nv_coder = auto
nv_rc = cbr
qsv_preset = medium
qsv_coder = auto
amd_coder = auto
amd_preanalysis = disabled
amd_quality = balanced
amd_rc = vbr_latency
amd_usage = ultralowlatency
amd_vbaq = enabled
vt_coder = auto
vt_software = auto
vt_realtime = enabled
fps = [10,30,60,90,120,"50"]
resolutions = [
    352x240,
    480x360,
    858x480,
    1280x720,
    1920x1080,
    2560x1080,
    3440x1440,
    1920x1200,
    3860x2160,
    3840x1600,
    640x480
]
```

### Relevant log output

```shell
no logs available
```

**Comment by ReenigneArcher** [comment]
The code requires `uniqueid` not `unique_id`

```cpp
  auto args = request->parse_query_string();
  if(args.find("uniqueid"s) == std::end(args)) {
    tree.put("root.<xmlattr>.status_code", 400);

    return;
  }
```

Searching `uniqueid` in Moonlight's org would give an indication that it's correct as it returns far more results than `unique_id`.

65 results https://github.com/search?q=org%3Amoonlight-stream+uniqueid&type=code

5 results https://github.com/search?q=org%3Amoonlight-stream%20unique_id&type=code

Narrowing it down further to the actual applist endpoint shows `uniqueid` being used, not `unique_id` ... https://github.com/search?q=org%3Amoonlight-stream+%2Fapplist%3Funiqueid&type=code

The code you shared from recalbox was last updated 5 years ago, so it's possible that GFE changed something between then and now, but I am not familiar with the history on that side.
