### ISSUE TITLE
Release Notifications do not work for Nightly branch

### ISSUE THREAD

**Issue by Nonary** [LizardByte/Sunshine#1072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

The version notification in the web UI is currently bugged and does not work for nightly releases of Sunshine. It offers to upgrade to stable and is unable to recognize when a new nightly release is available for download.

### Expected Behavior

If a new nightly release is available, it should suggest it.
If a stable release exists, don't suggest it unless it's higher version than the nightly release.

### Host Operating System

other, n/a

### Operating System Version

N/A

### Architecture

32 bit

### Sunshine commit or version

0.18.4

### Package

other (fork of this repo)

### GPU Type

none (software encoding)

### GPU Model

N/A

### GPU Driver/Mesa Version

N/A

### Capture Method (Linux Only)

N/A

### Config

```Shell
N/A
```

### Apps

```json
N/A
```

### Relevant log output

```shell
N/A
```

**Comment by Adam1986** [comment]
Sorry for asking a silly question, but where do you actually download the nightly builds from for Windows?

Thanks

**Comment by KuleRucket** [comment]
> Sorry for asking a silly question, but where do you actually download the nightly builds from for Windows?
> 
> Thanks

Main page => Releases => Scroll to the bottom. The date of the nightly is "Oct 29, 2022" so it is stuck at the bottom. It would be useful if this date was updated when the nightly branch is updated.

**Comment by ReenigneArcher** [comment]
> It would be useful if this date was updated when the nightly branch is updated.

Unfortunately this would require actually creating a new release every time I merge anything. This could be done but there are some drawbacks.

- Notifications on discord, reddit, etc. for every release (this is probably not difficult to solve)
- Have to wait about 4 hours between merges to nightly to allow all artifacts to build due to the workflow concurrency rules (not easy to solve without consuming a significant amount of simultaneous runs).
