### ISSUE TITLE
No Audio 0x800401F0

### ISSUE THREAD

**Issue by Nonary** [LizardByte/Sunshine#1102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

#1094 has caused an issue for Windows users that prevents audio from working, due to how when the variable goes out of scope, it de-initializes the COM API used for audio.

### Host Operating System

Windows

### Operating System Version

11

### Architecture

64 bit

### Sunshine commit or version

0.19

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

N/A

### GPU Driver/Mesa Version

N/A

### Capture Method (Linux Only)

N/A

### Config

```Shell
N/A
```

### Apps

```json
N/A
```

### Relevant log output

```shell
N/A
```

**Comment by buthig666** [comment]
windows 11, same settings as 18.4, no audio will pass through moonlight.

**Comment by drat0s** [comment]
Same issue here, Windows 10 21H2, didn't change any settings. I was confused for a bit then found this issue tracker.

**Comment by gundao** [comment]
I also encountered this problem on WINDOWS 11.

**Comment by Nonary** [comment]
There really is no point of commenting and letting us now you have this issue. You can use reactions on the post and do a thumbs up. But besides that, I've confirmed this issue impacts everyone on Windows, I've only opened up this issue for those who search about the issue basically.

**Comment by KuleRucket** [comment]
PR created with hotfix: #1104
