### ISSUE TITLE
Web interface claims there is a new version, while running latest available

### ISSUE THREAD

**Issue by FridgeRacer** [LizardByte/Sunshine#1103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Super minor nitpick, but I figured I might as well report it.

The web interface claims there is a new update available, when in reality, that new version is the version I'm using.

![bilde](https://user-images.githubusercontent.com/40672277/228780355-b0cfad59-d682-4e27-b0cb-2fed78a71c0c.png)

### Expected Behavior

The web interface doesn't tell me there's a new update when I'm on the latest release.

### Additional Context

Also happens in the 0.19.0 version built with the AUR script.

I did build the nightly (972f726) branch and test with that only to realise it's older than the release, but it did at least let me know there's a new version available, properly.

### Host Operating System

Linux

### Operating System Version

Arch Linux

### Architecture

64 bit

### Sunshine commit or version

v0.19.0

### Package

Linux - pkg.tar.zst

### GPU Type

AMD

### GPU Model

AMD RX 6700 XT

### GPU Driver/Mesa Version

23.0.1

### Capture Method (Linux Only)

KMS

### Config

```Shell
sunshine_name = Ridge-Arch
fps = [30,60]
adapter_name = renderD128
nv_preset = default
amd_coder = auto
upnp = disabled
vt_coder = auto
file_state = /home/ridge/.config/sunshine/sunshine_state.json
amd_rc = auto
encoder = vaapi
amd_quality = default
vt_software = auto
origin_web_ui_allowed = lan
min_log_level = 2
vt_realtime = enabled
key_rightalt_to_key_win = disabled
origin_pin_allowed = pc
display_cursor = true
resolutions = [
    1920x1080
]
nv_coder = auto
file_apps = apps_linux.json
dwmflush = enabled
nv_rc = auto
hevc_mode = 2
output_name = 2
```

### Relevant log output

```shell
[2023:03:30:10:37:43]: Info: Sunshine version: 0.19.0
```

**Comment by kode54** [comment]
Does this change require an update to the AUR package?

**Comment by ReenigneArcher** [comment]
@kode54 what if you use the `sunshine.pkg.tar.zst` from here? https://docs.lizardbyte.dev/projects/sunshine/en/latest/about/installation.html#archlinux-pkg

**Comment by slagiewka** [comment]
@ReenigneArcher @TheElixZammuto the issue is back, it seems. I had it with 0.22.0, too (Fedora 39 RPM).

![image](https://github.com/LizardByte/Sunshine/assets/11974489/c2b143bd-da0d-402d-8efe-532a0e1886e7)

**Comment by ReenigneArcher** [comment]
@slagiewka please open a new issue
