### ISSUE TITLE
The installer won't use system proxy to download ViGEmBus

### ISSUE THREAD

**Issue by lns103** [LizardByte/Sunshine#1116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

In China, the speed of accessing GitHub by most ISPs is very slow and may facing blocking. The installation process can get stuck while downloading ViGEmBus. Most people use proxy to speed up their access to GitHub. If it is possible to download through the system proxy, it could significantly improve the installation experience for many Chinese users.
For my ISP, the speed of directly download from GitHub is about 20kb/s.😥
![image](https://user-images.githubusercontent.com/49310852/229004596-675c6bef-8982-44ae-b3b6-406ca2bda1d7.png)

### Expected Behavior

Use system proxy to download ViGEmBus.

### Host Operating System

Windows

### Operating System Version

11

### Architecture

64 bit

### Sunshine commit or version

0.19.1

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

RTX 2060

### GPU Driver/Mesa Version

528.02

### Config

```Shell
not important
```

### Relevant log output

```shell
no log
```

**Comment by ReenigneArcher** [comment]
We're just using standard curl in a bat file to download it. As far as I know it doesn't support using the system proxy. If you want support for that you'll need to talk to the people of curl.

Alternatively, just download and install it yourself.

**Comment by lns103** [comment]
> We're just using standard curl in a bat file to download it. As far as I know it doesn't support using the system proxy. If you want support for that you'll need to talk to the people of curl.
> 
> Alternatively, just download and install it yourself.

I changed ```curl -s -L -o "%temp_dir%\vigembus.exe" %browser_download_url%```
to ```powershell -Command "(New-Object Net.WebClient).DownloadFile('%browser_download_url%', '%temp_dir%\vigembus.exe')"```
in ```/src_assets/windows/misc/vigembus/install-vigembus.bat```,
and it's working for me.
Could you please modify this?🙏

**Comment by ReenigneArcher** [comment]
Instead of using PowerShell, we should find a way to get the system proxy using batch scripting. Perhaps `netsh winhttp show proxy`?

Then set the appropriate proxy variables.

Or set the proxy in the `_curlrc` file. https://stackoverflow.com/a/35815181/11214013
