### ISSUE TITLE
Malware Bytes Reports False Positive

### ISSUE THREAD

**Issue by jet082** [LizardByte/Sunshine#1126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Malware Bytes currently reports Sunshine as a Potentially Unwanted Program (Corner Sunshine). Apparently, to get it to whitelist you, a dev needs to email pup@malwarebytes.com.

![image](https://user-images.githubusercontent.com/46708077/229394817-c3d97a7c-b648-4129-a8bd-b3a5cdba214f.png)

### Host Operating System

Windows

### Operating System Version

Windows 11

### Architecture

64 bit

### Sunshine commit or version

0.19.1.01167569abfddac195db968ce1da5111b15e6cc7

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

3080

### GPU Driver/Mesa Version

531.41

### Config

```Shell
Irrelevant for this.
```

### Relevant log output

```shell
Irrelevant for this.
```

**Comment by Nonary** [comment]
I am not sure if it can be whitelisted in this case, because its a false positive of an actual PUP called Corner Sunshine, not Sunshine...

**Comment by Nonary** [comment]
@cgutman @ReenigneArcher Should we just name our service SunshineStreamSvc instead? I mean its probably pointless anyway, but either way doesn't seem like it wouldn't be a big change in our code anyway... just renaming crap anyway

**Comment by ReenigneArcher** [comment]
I think it's fine to rename.

We'll probably need to update the service scripts so they remove the obsolete one.

That name is fine, let's spell out service though. "SunshineStreamService"

**Comment by Mister-333** [comment]
This issue still persists with Adwcleaner (Adware cleaner from Malware bytes).

**Comment by SeiferLeonheart** [comment]
Can confirm, issue persists. I didn't even have Sunshine installed when the issue here was reported and (allegedly) fixed, so I know it's not a leftover registry entry.

**Comment by ditydot** [comment]
> Can confirm, issue persists. I didn't even have Sunshine installed when the issue here was reported and (allegedly) fixed, so I know it's not a leftover registry entry.

I'm the same, I no longer have Sunshine installed and some leftover folders are being reported as CornerSunshine:

<img width="497" height="97" alt="Image" src="https://github.com/user-attachments/assets/ac07d3e3-785a-4c38-a88a-b82dc96d614f" />

**Comment by ReenigneArcher** [comment]
Submit it to your AV as a false positive.
