### ISSUE TITLE
Old certification not removed during install : error SEC_ERROR_REUSED_ISSUER_AND_SERIAL

### ISSUE THREAD

**Issue by shodanx2** [LizardByte/Sunshine#114]
### Describe the Bug

![image](https://user-images.githubusercontent.com/10621885/160356073-cfdd265e-d695-4571-bc29-b385f1e342ef.png)

Trying the latest release, it seems the serial number on the certification has changed.
This freaks out Firefox and leaves no way to bypass.

Annoyingly, I don't even know the name of the certification to delete ?
Could you add replacement of old certifications in the install.bat ?

thanks !

Error text

Secure Connection Failed

An error occurred during a connection to localhost:47990. You are attempting to import a cert with the same issuer/serial as an existing cert, but that is not the same cert.

Error code: SEC_ERROR_REUSED_ISSUER_AND_SERIAL

### Expected Behavior

Software should ensure correct certifications are installed / superseded certifications are removed

### Sunshine Host Operating System and Version

Windows 10

### Architecture

x64

### Sunshine Version

0.13

### GPU Type

nvidia 

### GPU Model

1080 ti

### GPU Driver/Mesa Version

497.29

**Comment by gnoumph** [comment]
Hello,

This is not a Windows 10 related issue, got the same on Kubuntu 21.10 (5.13.0-39-generic) with Firefox 98.0.2 x64.

**Comment by stenwt** [comment]
This is a 14-year old UI problem in FF that they refuse to fix: https://bugzilla.mozilla.org/show_bug.cgi?id=435013

Any chance we could get a toggle to disable TLS on the web ui? Dealing with this is a PITA.

**Comment by cromefire** [comment]
I mean it would be as easy a just using a random serial number to generate a new certificate. Firefox is completely right that an issuer may not reuse a serial number.
 I'm not involved in C++ & OpenSSL, but just setting a random serial number somewhere around this line would probably permanently properly fix this issue: https://github.com/LizardByte/Sunshine/blob/08d623ce44f77061a26de9dc50a2aef60f1b6158/src/crypto.cpp#L446
