### ISSUE TITLE
Unable to connect multiple clients

### ISSUE THREAD

**Issue by iMonZ** [LizardByte/Sunshine#1213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

So I can connect to the server with the first client.
But when a second client connects and I select desktop I get: Server error

### Expected Behavior

I would like to play with two other relatives

### Host Operating System

Linux

### Operating System Version

Fedora 38

### Architecture

64 bit

### Sunshine commit or version

0.19.1

### Package

Linux - rpm

### GPU Type

Nvidia

### GPU Model

RTX A3000

### GPU Driver/Mesa Version

530.41.3.192

### Capture Method (Linux Only)

KMS

### Config

```Shell
upnp = enabled
mouse = disabled
keyboard = disabled
output_name = 0
min_log_level = 2
```

### Relevant log output

```shell
In the server, there are no extra log entries when this happens
```

**Comment by ReenigneArcher** [comment]
Add this to your config.

```
channels = 2
```

Docs: https://docs.lizardbyte.dev/projects/sunshine/en/latest/about/advanced_usage.html#channels

**Comment by iMonZ** [comment]
> Add this to your config.
> 
> ```
> channels = 2
> ```
> 
> Docs: https://docs.lizardbyte.dev/projects/sunshine/en/latest/about/advanced_usage.html#channels

Thanks let me try that

**Comment by iMonZ** [comment]
> Add this to your config.
> 
> ```
> channels = 2
> ```
> 
> Docs: https://docs.lizardbyte.dev/projects/sunshine/en/latest/about/advanced_usage.html#channels

But are multiple controller working as well?

**Comment by iMonZ** [comment]
Omg it works! Thanks @ReenigneArcher
