### ISSUE TITLE
Rivatuner OSD toggle not working on latest Nightly Build (Mar 25, 2023)

### ISSUE THREAD

**Issue by cgutman** [LizardByte/Sunshine#1233]
### Discussed in https://github.com/LizardByte/Sunshine/discussions/1220

<div type='discussions-op-text'>

<sup>Originally posted by **mrallroy** April 25, 2023</sup>
As the title says, I am no longer able to toggle the OSD on or off in Rivatuner since upgrading to the latest nightly build (as of Mar 25, 2023).  I've confirmed this isn't an issue with both versions 18.4 and 19.1.  I've not made any setting changes in RT or AB and am running the latest versions of both.  I connect to sunshine via Shield TV w/ Moonlight.  My keyboard is a logitech K400+ that is connected to the Shield TV.  I've made no settings changes in both Shield TV and Moonlight.  To test, I simply downgrade from Nightly to 18.4 then upgrade to 19.1, reboot and the toggle works with both versions.  I've not used any other nightly builds so I can't confirm if this issue is new to the latest build or not.

Anyways, I thought I should post my findings for the devs and please let me know if there's any other information I may need to provide.  

Thank you.</div>

I suspect this regression is caused by 4e04604696a93020226182cba17562def1890467. We might need to ignore `SS_KBE_FLAG_NON_NORMALIZED` or add a config option for users to specify whether to obey it (more correct with alternate layouts) or not (more compatible with host software).

**Comment by mrallroy** [comment]
Hi again.  I noticed today that CTRL + ALT + DEL is not working in ver 18.4 and 19.1 (nightly as of May 13, 2023).  My setup as listed in OP, has not changed.  To confirm this, I also use a sideloaded copy of MS remote desktop on my shield to remote into my pc, and CTRL + ALT + DEL works with it.  It also worked with GFE.  I've no other info in this regard and hope this is the proper place to post this.

**Comment by cgutman** [comment]
> Hi again. I noticed today that CTRL + ALT + DEL is not working in ver 18.4 and 19.1 (nightly as of May 13, 2023). My setup as listed in OP, has not changed. To confirm this, I also use a sideloaded copy of MS remote desktop on my shield to remote into my pc, and CTRL + ALT + DEL works with it. It also worked with GFE. I've no other info in this regard and hope this is the proper place to post this.

I don't think Windows allows you to send Ctrl+Alt+Del using the `SendInput` API. The reason it worked with GFE is because they used a virtual USB driver that emulates a USB mouse and keyboard. We can't do that without a virtual USB input driver, and I don't think there are any of those that we can legal redistribute as part of Sunshine.
