### ISSUE TITLE
Archlinux v0.19.1 laggy, but v0.18.3 run smoothly

### ISSUE THREAD

**Issue by dreamtwi** [LizardByte/Sunshine#1252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Streaming laggy in v0.19.1, but when changed to v0.18.3, the straming run smoothly.

### Host Operating System

Linux

### Operating System Version

Linux version 6.3.1-arch1-1 (linux@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) #1 SMP PREEMPT_DYNAMIC Mon, 01 May 2023 17:42:39 +0000

### Architecture

64 bit

### Sunshine commit or version

v0.19.1

### Package

Linux - pkg.tar.zst

### GPU Type

AMD

### GPU Model

Radeon RX 6400/6500 XT/6500M

### GPU Driver/Mesa Version

OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.0.3

### Capture Method (Linux Only)

RxRPC

### Config

```Shell
port = 47989
upnp = enabled
sunshine_name = MinkieSunshine
key_rightalt_to_key_win = enabled
hevc_mode = 0
min_log_level = 2
channels = 10
output_name = 1
```

### Relevant log output

```shell
none
```

**Comment by ReenigneArcher** [comment]
Well, using 10 channels is a likely a reason...

**Comment by eidetic-av** [comment]
I'm seeing this behaviour also. 
I'm on Arch Linux, kernel 6.2.13, GPU is an Nvidia 3090 running nvidia 530.41.03.

Streaming in from Windows with Arch on Sunshine 19.1 is laggy and freezes up completely after some activity. 

I have downloaded AppImage for 18.4, 19.0 and 19.1 and can confirm that 18.4 launches fine but 19.0 and 19.1 fail to launch. 

This is different behaviour to what I see with the AUR package, which launches fine, but has the lagging & freeze.

AppImages 19.0 and 19.1 both output the same error:
