### ISSUE TITLE
[Linux] running sunshine command stalls full desktop

### ISSUE THREAD

**Issue by ConstantinCezarBegu** [LizardByte/Sunshine#1263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

when I run the sunshine command, I am supposed to see the app working or see an error message but instead when I run the command the whole gnome desktop freezes making the computer unusable. 

I have to connect to ssh from another computer to kill the process for it to unblock.

### Expected Behavior

when I run the sunshine command, I am supposed to see the app working or see an error message.

### Host Operating System

Linux

### Operating System Version

Arch

### Architecture

64 bit

### Sunshine commit or version

0.19.1

### Package

Linux - AUR (Third Party)

### GPU Type

Nvidia

### GPU Model

GeForce RTX 2070

### GPU Driver/Mesa Version

nvidia 530.41.03-9 nvidia-utils 530.41.03-1

### Capture Method (Linux Only)

X11

### Config

```Shell
sunshine_name = Constantin's Sunshine
resolutions = [
    1280x720,
    3440x1440
]
fps = [60,90,120]
output_name = 1
```

### Relevant log output

```shell
[2023:05:08:21:05:18]: Info: Sunshine version: 0.19.1
[2023:05:08:21:05:18]: Error: Couldn't expose some/all drm planes for card: /dev/dri/card0
[2023:05:08:21:05:18]: Info: Detecting monitors
```

**Comment by hilts-vaughan** [comment]
FWIW This does happen to me as well, but it happens randomly. It seems not really happen if I am using the `systemd` target, though.

**Comment by v7rzlhb3xg** [comment]
This is also happening to me on BazziteOS, GNOME Xorg with Nvidia 4070 GPU

**Comment by asier-ochoa** [comment]
My Xorg kde nvidia arch linux setup freezes when launchin sunshine. It then only lets me use my mouse. What is this program doing??

**Comment by SqueakyMonjuer** [comment]
I get the same issue on debian 12.11 after upgrading from 11 @asier-ochoa , Im going to try reinstalling

**Comment by SqueakyMonjuer** [comment]
having worse issues now :(

**Comment by SqueakyMonjuer** [comment]
back to square one, no progress

**Comment by bassmannate** [comment]
For what is worth, I've started getting this on mint Cinnamon 24.04 but only if I start then restart sunshine in the same session.

**Comment by BogTheMudWing** [comment]
> For what is worth, I've started getting this on mint Cinnamon 24.04 but only if I start then restart sunshine in the same session.

I am also seeing this behavior. It might be worth noting that when the first session is stopped, it reports:

```
Fatal: 10 seconds passed, yet Sunshine's still running: Forcing shutdown
```

Perhaps this is the cause?

**Comment by SqueakyMonjuer** [comment]
> > For what is worth, I've started getting this on mint Cinnamon 24.04 but only if I start then restart sunshine in the same session.
> 
> I am also seeing this behavior. It might be worth noting that when the first session is stopped, it reports:
> 
> ```
> Fatal: 10 seconds passed, yet Sunshine's still running: Forcing shutdown
> ```
> 
> Perhaps this is the cause?

I seemed to get this too
