### ISSUE TITLE
On Linux uinput's absolute mode is left behind

### ISSUE THREAD

**Issue by vignedev** [LizardByte/Sunshine#1266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

On Linux (tested on X11) `uinput` is left behind the cursor in absolute mode.

To demonstrate, I've created the following video:

https://github.com/LizardByte/Sunshine/assets/18449733/4a1a8303-4535-4018-b9a1-13f195c02ca9

- On the left: `xdotool getmouselocation` running in a infinite loop
- On the right: `evtest` pointing towards the emulated touchscreen
- On the top right (white console): Sunshine with Debug logging level

The **white** cursor is the guest's cursor, while the **blue** cursor is the host's one. When I am doing rapid movements and then lifting the mouse, you can see the position deprecancy between the *actual position reported by `xdotool`* and the *sent (by Sunshine) and received (by uinput) position*.

---

For a specific example, here's a screenshot from the video:

![mpv-shot0114](https://github.com/LizardByte/Sunshine/assets/18449733/72f5b3c0-2b0a-464f-879a-08c1e168bc4e)

You can see the last packet sent by Sunshine (white console) is `x=1021 y=1011`. `uinput` has received the `EV_ABS` of `x=10215 y=10118`, however `xdotool` reports the cursor's position to be `x=953 y=1016`.

### Expected Behavior

The cursor position of the host machine to match the cursor of the host/client/Moonlight.

### Additional Context

This does not occur if the mouse events are done using XTest, it always goes right under the guest's cursor.

### Host Operating System

Linux

### Operating System Version

Arch Linux

### Architecture

64 bit

### Sunshine commit or version

4ae412b21945b87a980dcdc31d219dc0699aabe5

### Package

other (self built)

### GPU Type

Nvidia

### GPU Model

NVIDIA GeForce GTX 1650 Super

### GPU Driver/Mesa Version

530.41.03

### Capture Method (Linux Only)

NvFBC

### Config

```Shell
ps = [10,30,60,90]
amd_rc = auto
encoder = nvenc
hevc_mode = 0
nv_rc = vbr
min_log_level = 1
output_name = 2
fec_percentage = 5
nv_coder = cabac
resolutions = [
    352x240,
    480x360,
    858x480,
    1280x720,
    1920x1080,
    2560x1080,
    3440x1440,
    1920x1200,
    3860x2160,
    3840x1600
]
sunshine_name = detached-arch
amd_quality = default
```

### Relevant log output

Sunshine reports the last absolute mouse move packet as follows:
```shell
--end absolute mouse move packet--
[2023:05:09:19:19:13]: Debug: --begin absolute mouse move packet--
x      [1021]
y      [1011]
width  [1919]
height [1199]
--end absolute mouse move packet--
```

On the host side, using `evdev` we can verify that the data is received correctly:
```shell
Event: time 1683652753.0840536, ------------- SYN_REPORT -------------
Event: time 1683652753.0848992, code 0 (ABS_X), value 10215
Event: time 1683652753.0848992, code 1 (ABS_Y), value 10118
Event: time 1683652753.0848992, type 1 (EV_KEY), code 325 (BTN_TOOL_FINGER), value 1
Event: time 1683652753.0848992, type 1 (EV_KEY), code 325 (BTN_TOOL_FINGER), value 0
Event: time 1683652753.0848992, ------------- SYN_REPORT -------------
```

However, the user can notice that the clicks are not aligned to the guest's cursor. This can further be confirmed by `xdotool getmouselocation`, which outputs a slightly off location:

```shell
x: 953 y:1016 screen:0 window:20971537
x: 953 y:1016 screen:0 window:20971537
x: 953 y:1016 screen:0 window:20971537
x: 953 y:1016 screen:0 window:20971537
x: 953 y:1016 screen:0 window:20971537
x: 953 y:1016 screen:0 window:20971537
```

Note that at the time when this log was written down, the mouse was *left untouched and those were the last input packets sent*.

**Comment by ReenigneArcher** [comment]
Please add the logs...

A. it's often difficult to read screenshots of logs
B. it helps users who may be searching for the same thing

**Comment by vignedev** [comment]
I've updated the original issue with the logs from Sunshine, `evtest` and `xdotool`.

**Comment by CristianPi** [comment]
Same here, i'm using wayland connecting from moonlight flatpak (fedora linux - fedora linux).
I see a mouse, but clicks does nothing as the position is wrong.
Basically unusable :(

**Comment by ReenigneArcher** [comment]
@CristianPi you probably have a different issue -> https://github.com/LizardByte/Sunshine/issues/93
