### ISSUE TITLE
v0.19.1  (Audio) Fixed no audio issue introduced in v0.19.0 not find  sunshine_x86_64.flatpak  of releases

### ISSUE THREAD

**Issue by jcleng** [LizardByte/Sunshine#1279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

v0.19.1  (Audio) Fixed no audio issue introduced in v0.19.0 not find  sunshine_x86_64.flatpak  of releases

### Host Operating System

Linux

### Operating System Version

nixos-Flatpak 1.14.0

### Architecture

64 bit

### Sunshine commit or version

v0.19.1 

### Package

Linux - flatpak

### GPU Type

AMD

### GPU Model

rx580

### GPU Driver/Mesa Version

-

### Config

```Shell
-
```

### Relevant log output

```shell
-
```

**Comment by ReenigneArcher** [comment]
![image](https://github.com/LizardByte/Sunshine/assets/42013603/fb2fb16f-ce73-4f5b-8662-092882929dec)
