### ISSUE TITLE
Support Ubuntu 23.04 Release

### ISSUE THREAD

**Issue by ZaxLofful** [LizardByte/Sunshine#1284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

No Debian Package Released for Ubuntu 23.04 which is the newest LTS.

### Expected Behavior

Ubuntu 23.04 Package On the Release Page

### Host Operating System

Linux

### Operating System Version

Ubuntu 23.04

### Architecture

64 bit

### Sunshine commit or version

v0.19.1

### Package

Linux - deb

### GPU Type

Nvidia

### GPU Model

NVIDIA GTX 3080

### GPU Driver/Mesa Version

NVIDIA 515.105.1

### Config

```Shell
N/A
```

### Relevant log output

```shell
N/A
```

**Comment by ReenigneArcher** [comment]
This is not an LTS release and for Ubuntu we don't build packages for non LTS releases.

You're welcome to build yourself. Instructions are in the docs.
