### ISSUE TITLE
Make Discord integration optional (makes several calls to external servers/analytics)

### ISSUE THREAD

**Issue by FallingSnow** [LizardByte/Sunshine#1300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Can we make discord integration optional?

Opening the web ui reveals that the widgetbot package makes a lot of calls to external services. I'm not a fan of a self hosted application making calls to external services.
![Screenshot from 2023-05-22 12-16-58](https://github.com/LizardByte/Sunshine/assets/2512197/50779064-b468-47ff-8cb8-4fe4bce99efc)

I also have some questions about these calls, which seem to be analytics and no clear option to disable.

![Screenshot from 2023-05-22 12-20-19](https://github.com/LizardByte/Sunshine/assets/2512197/a6967569-85d3-4cdd-a0e1-df95afafa436)

### Host Operating System

Linux

### Operating System Version

Arch Linux

### Architecture

64 bit

### Sunshine commit or version

0.19.1

### Package

Linux - AUR (Third Party)

### GPU Type

none (software encoding)

### GPU Model

N/A

### GPU Driver/Mesa Version

N/A

### Capture Method (Linux Only)

KVM

### Config

```Shell
N/A
```

### Relevant log output

```shell
See screenshots.
```

**Comment by FallingSnow** [comment]
Why will you not consider this?

**Comment by ReenigneArcher** [comment]
We have more important issues to worry about.

**Comment by FallingSnow** [comment]
If I submit a PR will you consider?

**Comment by jerrcs** [comment]
I would like this too. Despite blocking the element, it still makes calls to external services and there is no way to disable it in the configuration options. You added a feature that we can't turn off.

Is the development team not interested in privacy-respecting options being added in the future? It doesn't need to be done ASAP, but it should at least go into a backlog instead of shutting it down like this. After all, this is a self-hosted application.

**Comment by ReenigneArcher** [comment]
Since discord is the only location we provide support, it will not be made optional. You can block the javascript that loads it in, if it bothers you that much.

**Comment by shodanx2** [comment]
It should be possible to disable the integration, why not ? This is weird

**Comment by shodanx2** [comment]
I would have been fine to just switch it off.

I was appalled at seeing it call home to discord and so many requests to 3rd party website

I rejoice at this change

Thank you Sunshine team !!
