### ISSUE TITLE
Can no longer connect to 5ghz network after installing - Windows 10

### ISSUE THREAD

**Issue by tpsteiner** [LizardByte/Sunshine#1317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Summary: I installed Sunshine on my Windows 10 PC and immediately could not use my 5ghz wifi connection.

Details: Apologies if this isn't the right place, but this issue started with installing Sunshine and is network related. Please point me elsewhere if necessary. Below are the order things happened, I'm not sure what all is important.

- Installed Geforce experience via chocolatey GUI
- Installed Sunshine v18.3 via Chocolatey GUI
- Realized it is an old version, so uninstalled Sunshine and Geforce experience, then installed Sunshine v19.1 from github and vigembus
- Realized 5ghz was not working, so moved to 2.4ghz. When I enter the correct password, it tries to connect for a minute, then fails and tells me it was the wrong password. I am certain it is correct.
- Other devices working fine on 5ghz, and i'm able to host on 2.4ghz with Sunshine and stream to devices on 5ghz
- Eventually realized it wasn't a temporary issue, so started troubleshooting
- Uninstalled Sunshine and Moonlight
- I noticed that immediately after uninstalling Sunshine, there was a 3rd network that was a duplicate of the 2.4ghz name with the number 2 appended to it. After system restart that is gone.
- Reset network drivers
- Uninstalled and reinstalled all network drivers from device manager
- I tried these steps found online:
1. Type ipconfig /release and press Enter.
2. Type ipconfig /flushdns and press Enter.
3. Type ipconfig /renew and press Enter. (This will stall for a moment.)
4. Type netsh int ip reset and press Enter. (Don’t restart yet.)
5. Type netsh winsock reset and press Enter.

Nothing has worked. I still can't connect to 5ghz. My next step is to do an full system factory reset. Before doing so, could anyone provided any insight into what happened?

### Host Operating System

Windows

### Operating System Version

Windows 10

### Architecture

64 bit

### Sunshine commit or version

0.19.1

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

Geforce RTX 2070 SUPER

### GPU Driver/Mesa Version

31.0.15.3179

### Config

```Shell
Uninstalled
```

### Relevant log output

```shell
N/A
```

**Comment by ReenigneArcher** [comment]
Sunshine does not modify network devices in any way whatsoever.

**Comment by tpsteiner** [comment]
I appreciate what you do. This software is fantastic. 

Could you offer a suggestion on next step for troubleshooting? I'm not a strong programmer, but I don't believe this was a coincidence. Maybe Sunshine prompted windows to change something? Why would my networks duplicate upon uninstalling, is there like a virtual network created that could be interfering? There's gotta be something more to this.

I spent hours uninstalling-reinstalling drivers, updating bios, changing pcie slots, changing device advanced properties values. Nothing has helped.

**Comment by ReenigneArcher** [comment]
There is no virtual device created by Sunshine... Sunshine does not do anything with your network adapters. I don't know what else to tell you.
