### ISSUE TITLE
MacPort 0.20.0 and up returns segmentation fault 11

### ISSUE THREAD

**Issue by EgeToksoz** [LizardByte/Sunshine#1348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

0.19.1 works well but after updating to 0.20.0 and nightly build. zsh returns zsh: segmentation fault sunshine and bash returns Segmentation fault: 11
it doesn't seem like a GPU issue integrated and discrete gpu returns the same error unlike #804

### Host Operating System

macOS

### Operating System Version

macOS 13.4 (22F66)

### Architecture

64 bit

### Sunshine commit or version

0.20.0

### Package

macOS - Portfile

### GPU Type

AMD

### GPU Model

Radeon Pro 555X/Intel UHD Graphics 630

### GPU Driver/Mesa Version

Latest

### Config

```Shell
default
```

### Relevant log output

```shell
user@mac .ports % sunshine
[2023:06:03:12:42:55]: Info: Sunshine version: 0.20.0
[2023:06:03:12:42:55]: Info: system_tray() is not yet implemented for this platform.
[2023:06:03:12:42:55]: Error: No screen capture permission!
[2023:06:03:12:42:55]: Error: Please activate it in 'System Preferences' -> 'Privacy' -> 'Screen Recording'
[2023:06:03:12:42:55]: Error: Platform failed to initialize
[2023:06:03:12:42:55]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2023:06:03:12:42:55]: Info: Trying encoder [videotoolbox]
[2023:06:03:12:42:55]: Info: SDR color coding [Rec. 601]
[2023:06:03:12:42:55]: Info: Color range: [JPEG]

  [Restored Jun 3, 2023 at 12:43:09 PM]
Restored session: Sat Jun  3 12:43:07 +03 2023
user@mac .ports % sunshine
[2023:06:03:12:43:11]: Info: Sunshine version: 0.20.0
[2023:06:03:12:43:11]: Info: system_tray() is not yet implemented for this platform.
[2023:06:03:12:43:11]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2023:06:03:12:43:11]: Info: Trying encoder [videotoolbox]
[2023:06:03:12:43:11]: Info: SDR color coding [Rec. 601]
[2023:06:03:12:43:11]: Info: Color range: [JPEG]
zsh: segmentation fault  sunshine
```

**Comment by jershell** [comment]
+1. Same trouble.

**Comment by lucasscheepers** [comment]
+1 On Xubuntu VM same issue. With virtio-pci enabled

**Comment by classicalwow** [comment]
+1 same

**Comment by DevSrSouza** [comment]
+1

**Comment by qdore** [comment]
Add backtrace:

(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x137c8c008)
  * frame #0: 0x00007ff819b3abc3 libsystem_platform.dylib`_platform_memset$VARIANT$Rosetta + 206
    frame #1: 0x000000010015204a sunshine`platf::nv12_zero_device::convert(platf::img_t&) + 378
    frame #2: 0x0000000100114b49 sunshine`video::validate_config(std::__1::shared_ptr<platf::display_t>&, video::encoder_t const&, video::config_t const&) + 281
    frame #3: 0x000000010011514e sunshine`video::validate_encoder(video::encoder_t&, bool) + 574
    frame #4: 0x0000000100116920 sunshine`video::probe_encoders() + 3936
    frame #5: 0x000000010002ee2c sunshine`main + 4012
    frame #6: 0x000000020170f310 dyld`start + 2432

**Comment by FrancescoBrunoDev** [comment]
+1

**Comment by JonoloLuo** [comment]
+1

**Comment by ReenigneArcher** [comment]
Do not continue with these +1 comments. Use the reactions instead please.

**Comment by Timfon** [comment]
How do I add the backtrace? I'm not sure if I understand properly

**Comment by ReenigneArcher** [comment]
Additional context: https://discord.com/channels/804382334370578482/1074377411069747250/1142206674959085679

**Comment by ReenigneArcher** [comment]
This build "may" fix this issue, if anyone would like to test and report on the status of the macport file from here: https://github.com/LizardByte/Sunshine/actions/runs/6040829220#artifacts

You must be logged into GitHub in order to download it.

**Comment by downthecrop** [comment]
Verified the Portfile is functional. Macports does encounter a minor issue when fetching the **specific orphaned commit** 40b78436d2c9a0988b3ad9e619fe166e47226110 referenced with that artifact. However, that won't affect tagged release versions.

No boost180 Macports issue or segfault ect

![](https://i.imgur.com/2rfs6WA.png)

[macports-install-output.txt](https://github.com/LizardByte/Sunshine/files/12594598/macports-install-output.txt)
