### ISSUE TITLE
Custom SSL Certificate Breaks Pairing

### ISSUE THREAD

**Issue by NolanWelser** [LizardByte/Sunshine#1353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Using a custom certificate and key causes Moonlight to unpair the remote machine. When entering a PIN to re-pair in Sunshine, the web UI reports pairing was successful, but Moonlight says paring failed.

### Expected Behavior

Client pairs successfully

### Additional Context

The web UI correctly serves the custom SSL certificate in browser, running in a virtual machine using NVIDIA vgpu_unlock on an RTX 2060 (VM GPU reads as Quadro RTX 6000

### Host Operating System

Windows

### Operating System Version

10 22H2

### Architecture

64 bit

### Sunshine commit or version

0.20.0.cdbc0e699cb7c0291f4d61af724f48ca8e23fc95

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

RTX 2060 12GB / vgpu_unlock Quadro RTX 6000

### GPU Driver/Mesa Version

511.79

### Config

```Shell
resolutions = [
    352x240,
    480x360,
    858x480,
    1280x720,
    1920x1080,
    2560x1080,
    3440x1440,
    1920x1200,
    3860x2160,
    3840x1600
]
origin_pin_allowed = wan
min_log_level = 2
origin_web_ui_allowed = wan
hevc_mode = 0
pkey = [PATH_TO_KEY]
cert = [PATH_TO_CERT]
```

### Relevant log output

```shell
No relevant log output
```

**Comment by ReenigneArcher** [comment]
Private key and cert both need to 2048 bit. https://docs.lizardbyte.dev/projects/sunshine/en/latest/about/advanced_usage.html#pkey

**Comment by NolanWelser** [comment]
Yup that's the problem, Let's Encrypt changed to using EC 256bit keys instead of RSA by default. Solved.

**Comment by valpackett** [comment]
It would be nice if Sunshine allowed a different key&cert (and port) for the management UI.
