### ISSUE TITLE
HEVC not available on GTX 1060

### ISSUE THREAD

**Issue by burner1024** [LizardByte/Sunshine#1361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Can't use HEVC on GeForce GTX 1060.

It appears that Sunshine uses Intel graphics, even though GTX is set to be the primary adapter on the server.
If I set `adapter_name = NVIDIA GeForce GTX 1060`, then Moonlight fails to connect completely.

### Expected Behavior

Can use HEVC on GeForce GTX 1060.
It's working on the same server when using GeForce Experience.

### Additional Context

GPU
![Captura desde 2023-06-11 02-54-48](https://github.com/LizardByte/Sunshine/assets/1279852/55f5cc44-e077-4faf-b1f5-05a6240a4c62)
Connecting to Sunshine
![Captura desde 2023-06-11 02-55-17](https://github.com/LizardByte/Sunshine/assets/1279852/c184aef7-72c7-4782-8111-f6a572de455c)

Connected to GeForce Experience
![Captura desde 2023-06-11 04-07-48](https://github.com/LizardByte/Sunshine/assets/1279852/85127b9e-de97-42e5-9112-c61902a44829)

### Host Operating System

Windows

### Operating System Version

11

### Architecture

64 bit

### Sunshine commit or version

0.20.0

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

GeForce GTX 1060

### GPU Driver/Mesa Version

535.98

### Config

```Shell
nv_coder = cabac
nv_preset = p7
nv_tune = hq
```

### Relevant log output

```shell
Not sure, probably this...

[2023:06:10:20:50:32]: Info: SDR color coding [Rec. 601]
[2023:06:10:20:50:32]: Info: Color range: [JPEG]
[2023:06:10:20:50:32]: Error: Could not open codec [h264_nvenc]: No such file or directory
[2023:06:10:20:50:32]: Info: 
Device Description : Intel(R) HD Graphics 530
Device Vendor ID   : 0x00008086
Device Device ID   : 0x0000191B
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8132 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:06:10:20:50:32]: Info: Desktop resolution [1920x1080]
[2023:06:10:20:50:32]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:06:10:20:50:32]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.149414,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
```

**Comment by ns6089** [comment]
I have 1060 laying around, will check if current nightly works alright on it.
I'm particularly curious about quarter resolution two-pass mode support.

**Comment by burner1024** [comment]
I switched host to Linux, HEVC works there.

**Comment by IamTheFij** [comment]
@burner1024 how are you running it on Linux that it works for you? I'm running the Flatpak on Pop_OS and I'm seeing the same original error as you.

**Comment by burner1024** [comment]
ubuntu 22.04, deb package, nvidia drivers, [nvidia-patch](https://github.com/keylase/nvidia-patch).
