### ISSUE TITLE
Unable to Stream 4K120 to any device

### ISSUE THREAD

**Issue by zurce** [LizardByte/Sunshine#1403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I am trying to stream 4K 120 fps to both my iPhone 13 Pro Max and my Pimax Portal and both get stuck at 90~fps in the overlay. The content in the host pc is running at 120 fps but the devices doesn't seem to be getting them

Tested both HEVC and H264 with and without HDR , with gamestream and without gamestream enabled. It doesn't seem to be a limitation of the device, but the host

My setup: 

### Host Operating System

Windows

### Operating System Version

Windows 11

### Architecture

64 bit

### Sunshine commit or version

20.0

### Package

Windows - installer

### GPU Type

NVIDIA

### GPU Model

GeForce RTX 4090

### GPU Driver/Mesa Version

536.23

### Config

```Shell
qsv_preset = veryfast
fps = [30,60,90,120,61]
origin_pin_allowed = wan
sunshine_name = Sunshine H5
min_log_level = 2
amd_quality = default
resolutions = [
    1280x720,
    1920x1080,
    3840x2160
]
upnp = enabled
gamepad = ds4
nv_preset = p6
hevc_mode = 3
amd_rc = auto
encoder = nvenc
key_rightalt_to_key_win = enabled
```

### Apps

```json
Moonlight
```

### Relevant log output

```shell
N/A
```

**Comment by KuleRucket** [comment]
Reduce nv_preset to p3 or less.

"content in the host pc is running at 120 fps" - this is not relevant to the speed the encoding is working at

**Comment by zurce** [comment]
I fixed the ticket but I am in NVIDIA. 


as we'll switch the preset to p4 or bellow fixed the issue . Thanks the resolved it 

Is this documented anywhere I didn't think I found it when I look for it
