### ISSUE TITLE
Mouse gestures in windows don't work

### ISSUE THREAD

**Issue by priomsrb** [LizardByte/Sunshine#1459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

(Note: I have a code fix below)

When using a windows host, mouse gesture applications (for example StrokeIt, FastKeys) don't work. They act all glitchy.

The way mouse gestures typically work is:
1. You hold down the right mouse button
2. You draw a pattern
3. You let go of the right mouse button
4. The mouse gesture program then performs an action (e.g. press some key strokes or run a command)

With Nvidia Gamestream, these gestures worked fine. But in Sunshine they don't work. When drawing the pattern, the mouse button gets stuck and acts weird.

I was able to fix it by changing a single line in the code. I removed the return statement in `src\platform\windows\input.cpp:312`

![sunshine_mouse_gestures_fix](https://github.com/LizardByte/Sunshine/assets/1480667/668251c1-a26d-411c-a3fb-b973f2936208)

By making that change mouse gestures work again.

### Expected Behavior

Mouse gestures should work.

### Host Operating System

Windows

### Operating System Version

10

### Architecture

64 bit

### Sunshine commit or version

31e8b798dabf47d5847a1b485f57cf850a15fcae

### Package

other (self built)

### GPU Type

Nvidia

### GPU Model

RTX 3070

### GPU Driver/Mesa Version

N/A

### Config

```Shell
N/A
```

### Relevant log output

```shell
N/A
```

**Comment by ReenigneArcher** [comment]
Please submit a PR.

**Comment by cgutman** [comment]
This was already fixed in nightly by https://github.com/LizardByte/Sunshine/pull/1437
