### ISSUE TITLE
Typo in QRes command in documentations

### ISSUE THREAD

**Issue by ahmadalli** [LizardByte/Sunshine#1484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [x] This issue is present in the nightly release

### Describe the Bug

The `Do Command` for windows in [the docs](https://docs.lizardbyte.dev/projects/sunshine/en/nightly/about/app_examples.html#windows) uses `SUNSHINE_CLIENT_WIDTH` instead of `SUNSHINE_CLIENT_HEIGHT` (this was overlooked on #1430).

### Expected Behavior

The command for Windows should be `cmd /C FullPath\qres.exe /x:%SUNSHINE_CLIENT_WIDTH% /y:%SUNSHINE_CLIENT_HEIGHT% /r:%SUNSHINE_CLIENT_FPS%`

### Host Operating System

other, n/a

### Operating System Version

n/a

### Architecture

64 bit

### Sunshine commit or version

0.20.0

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

n/a

### GPU Driver/Mesa Version

n/a

### Config

```Shell
n/a
```

### Relevant log output

```shell
[2023:07:31:09:03:37]: Info: Executing Do Cmd: [cmd /C D:\Programs\qres\QRes.exe /x:%SUNSHINE_CLIENT_WIDTH% /y:%SUNSHINE_CLIENT_WIDTH% /r:%SUNSHINE_CLIENT_FPS%]
[2023:07:31:09:03:37]: Info: cmd /C D:\Programs\qres\QRes.exe /x:%SUNSHINE_CLIENT_WIDTH% /y:%SUNSHINE_CLIENT_WIDTH% /r:%SUNSHINE_CLIENT_FPS% running with PID 27568
```

**Comment by ReenigneArcher** [comment]
Why not just make a PR fixing it?

**Comment by ahmadalli** [comment]
I was going to do that but got distracted by other stuff. I'll do that

**Comment by ReenigneArcher** [comment]
Please leave open, until we merge this into `master`
