### ISSUE TITLE
Program keeps restarting. Application Error: The memory could not be read

### ISSUE THREAD

**Issue by system198** [LizardByte/Sunshine#1503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

After I uninstall and reinstall the program to the latest version, I now got this error.
The program also keeps restarting (icon appearing in the system tray for a few seconds then disappears, and it keeps on looping)

At one point this error will pop up:
![Screenshot 2023-08-04 231149](https://github.com/LizardByte/Sunshine/assets/34373616/d9e0c277-867c-47bd-9479-f5a7f6d4b4d6)

Loading the web UI with get an error ERR_CONNECTION_REFUSED

### Expected Behavior

For the program to work normally.

### Additional Context

*I got a PAGE_FAULT_IN_NONPAGED_AREA BSOD at one point. Tried Memory Diagnostic but it returned with no error
- Tried automatically managed system page file size, and custom size (16gb) Virtual memory: both doesn't resolved the issue

*Already reinstalled ViGEm but to no luck

*I tried rolling back to the previous version before I update it but it no longer works; it ended up flooding the system tray with Sunshine icons

*Tried both installer and portable version but it does not work

PC Specification:
AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx     2.10 GHz
Radeon RX 560X Series

### Host Operating System

Windows

### Operating System Version

Windows 11 22H2

### Architecture

64 bit

### Sunshine commit or version

v0.20.0

### Package

Windows - installer

### GPU Type

AMD

### GPU Model

Radeon RX 560X Series

### GPU Driver/Mesa Version

27.20.1028.1

### Config

```Shell
**none**
```

### Relevant log output

```shell
[2023:08:04:23:19:25]: Info: Sunshine version: 0.20.0
[2023:08:04:23:19:25]: Info: Compiling shaders...
[2023:08:04:23:19:25]: Info: System tray created
[2023:08:04:23:19:25]: Info: Compiled shaders
[2023:08:04:23:19:25]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2023:08:04:23:19:25]: Info: Trying encoder [nvenc]
[2023:08:04:23:19:25]: Info: ddprobe.exe [1] [] returned: 0x00000000
[2023:08:04:23:19:25]: Info: Set GPU preference: 1
[2023:08:04:23:19:25]: Info: 
Device Description : AMD Radeon(TM) Vega 8 Graphics
Device Vendor ID   : 0x00001002
Device Device ID   : 0x000015D8
Device Video Mem   : 498 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 1761 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:08:04:23:19:25]: Info: Desktop resolution [1920x1080]
[2023:08:04:23:19:25]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:04:23:19:25]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.149414,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:08:04:23:19:25]: Info: SDR color coding [Rec. 601]
[2023:08:04:23:19:25]: Info: Color range: [JPEG]
[2023:08:04:23:19:25]: Error: Could not open codec [h264_nvenc]: Operation not permitted
[2023:08:04:23:19:26]: Info: 
Device Description : AMD Radeon(TM) Vega 8 Graphics
Device Vendor ID   : 0x00001002
Device Device ID   : 0x000015D8
Device Video Mem   : 498 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 1761 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:08:04:23:19:26]: Info: Desktop resolution [1920x1080]
[2023:08:04:23:19:26]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:04:23:19:26]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.149414,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:08:04:23:19:26]: Info: SDR color coding [Rec. 601]
[2023:08:04:23:19:26]: Info: Color range: [JPEG]
[2023:08:04:23:19:26]: Error: Could not open codec [h264_nvenc]: Operation not permitted
[2023:08:04:23:19:26]: Info: 
Device Description : AMD Radeon(TM) Vega 8 Graphics
Device Vendor ID   : 0x00001002
Device Device ID   : 0x000015D8
Device Video Mem   : 498 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 1761 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:08:04:23:19:26]: Info: Desktop resolution [1920x1080]
[2023:08:04:23:19:26]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:04:23:19:26]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.149414,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:08:04:23:19:26]: Info: SDR color coding [Rec. 601]
[2023:08:04:23:19:26]: Info: Color range: [JPEG]
[2023:08:04:23:19:26]: Error: Could not open codec [h264_nvenc]: Operation not permitted
[2023:08:04:23:19:26]: Info: 
Device Description : AMD Radeon(TM) Vega 8 Graphics
Device Vendor ID   : 0x00001002
Device Device ID   : 0x000015D8
Device Video Mem   : 498 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 1761 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:08:04:23:19:26]: Info: Desktop resolution [1920x1080]
[2023:08:04:23:19:26]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:04:23:19:26]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.149414,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:08:04:23:19:26]: Info: SDR color coding [Rec. 601]
[2023:08:04:23:19:26]: Info: Color range: [JPEG]
[2023:08:04:23:19:26]: Error: Could not open codec [h264_nvenc]: Operation not permitted
[2023:08:04:23:19:26]: Info: Encoder [nvenc] failed
[2023:08:04:23:19:26]: Info: Trying encoder [quicksync]
[2023:08:04:23:19:26]: Info: 
Device Description : AMD Radeon(TM) Vega 8 Graphics
Device Vendor ID   : 0x00001002
Device Device ID   : 0x000015D8
Device Video Mem   : 498 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 1761 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:08:04:23:19:26]: Info: Desktop resolution [1920x1080]
[2023:08:04:23:19:26]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:04:23:19:26]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.149414,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:08:04:23:19:26]: Info: SDR color coding [Rec. 601]
[2023:08:04:23:19:26]: Info: Color range: [JPEG]
[2023:08:04:23:19:26]: Error: Failed to derive device context: Unknown error occurred
[2023:08:04:23:19:26]: Info: 
Device Description : AMD Radeon(TM) Vega 8 Graphics
Device Vendor ID   : 0x00001002
Device Device ID   : 0x000015D8
Device Video Mem   : 498 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 1761 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:08:04:23:19:26]: Info: Desktop resolution [1920x1080]
[2023:08:04:23:19:26]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:04:23:19:26]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.149414,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:08:04:23:19:26]: Info: SDR color coding [Rec. 601]
[2023:08:04:23:19:26]: Info: Color range: [JPEG]
[2023:08:04:23:19:26]: Error: Failed to derive device context: Unknown error occurred
[2023:08:04:23:19:26]: Info: 
Device Description : AMD Radeon(TM) Vega 8 Graphics
Device Vendor ID   : 0x00001002
Device Device ID   : 0x000015D8
Device Video Mem   : 498 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 1761 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:08:04:23:19:26]: Info: Desktop resolution [1920x1080]
[2023:08:04:23:19:26]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:04:23:19:26]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.149414,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:08:04:23:19:26]: Info: SDR color coding [Rec. 601]
[2023:08:04:23:19:26]: Info: Color range: [JPEG]
[2023:08:04:23:19:26]: Error: Failed to derive device context: Unknown error occurred
[2023:08:04:23:19:26]: Info: 
Device Description : AMD Radeon(TM) Vega 8 Graphics
Device Vendor ID   : 0x00001002
Device Device ID   : 0x000015D8
Device Video Mem   : 498 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 1761 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:08:04:23:19:26]: Info: Desktop resolution [1920x1080]
[2023:08:04:23:19:26]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:04:23:19:26]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.149414,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:08:04:23:19:27]: Info: SDR color coding [Rec. 601]
[2023:08:04:23:19:27]: Info: Color range: [JPEG]
[2023:08:04:23:19:27]: Error: Failed to derive device context: Unknown error occurred
[2023:08:04:23:19:27]: Info: Encoder [quicksync] failed
[2023:08:04:23:19:27]: Info: Trying encoder [amdvce]
[2023:08:04:23:19:27]: Info: 
Device Description : AMD Radeon(TM) Vega 8 Graphics
Device Vendor ID   : 0x00001002
Device Device ID   : 0x000015D8
Device Video Mem   : 498 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 1761 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:08:04:23:19:27]: Info: Desktop resolution [1920x1080]
[2023:08:04:23:19:27]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:04:23:19:27]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.149414,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:08:04:23:19:27]: Info: SDR color coding [Rec. 601]
[2023:08:04:23:19:27]: Info: Color range: [JPEG]
[2023:08:04:23:19:27]: Info: 
Device Description : AMD Radeon(TM) Vega 8 Graphics
Device Vendor ID   : 0x00001002
Device Device ID   : 0x000015D8
Device Video Mem   : 498 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 1761 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:08:04:23:19:27]: Info: Desktop resolution [1920x1080]
[2023:08:04:23:19:27]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:04:23:19:27]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.149414,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:08:04:23:19:27]: Info: SDR color coding [Rec. 601]
[2023:08:04:23:19:27]: Info: Color range: [JPEG]
[2023:08:04:23:19:27]: Info: 
Device Description : AMD Radeon(TM) Vega 8 Graphics
Device Vendor ID   : 0x00001002
Device Device ID   : 0x000015D8
Device Video Mem   : 498 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 1761 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:08:04:23:19:27]: Info: Desktop resolution [1920x1080]
[2023:08:04:23:19:27]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:04:23:19:27]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.149414,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:08:04:23:19:27]: Info: SDR color coding [Rec. 709]
[2023:08:04:23:19:27]: Info: Color range: [JPEG]
```

**Comment by cgutman** [comment]
Usually these are display driver bugs, but we'll need a memory dump to know for sure.

To collect a memory dump:
1. Download and extract [ProcDump](https://learn.microsoft.com/en-us/sysinternals/downloads/procdump)
2. Start an admin command prompt in the directory where you extracted ProcDump
3. Run `procdump -e -ma -w sunshine.exe`
4. Start Sunshine to trigger the crash
5. Compress the `.dmp` file written in the ProcDump directory and attach it to this issue.

**Comment by system198** [comment]
> Usually these are display driver bugs, but we'll need a memory dump to know for sure.
> 
> To collect a memory dump:
> 
> 1. Download and extract [ProcDump](https://learn.microsoft.com/en-us/sysinternals/downloads/procdump)
> 2. Start an admin command prompt in the directory where you extracted ProcDump
> 3. Run `procdump -e -ma -w sunshine.exe`
> 4. Start Sunshine to trigger the crash and wait for a `.dmp` file to be written in the ProcDump directory
> 5. Compress the dump file and attach it to this issue.

Here are file 3 memory dump files it produced compressed in the zip files. I uploaded it to mega.nz since it exceeds with the Github 25 MB files size limit

https://mega.nz/file/sx5zzKAI#I7Td49FIgmh7mMrPo1r8CJizDwlhAkttEVMh78mJIG8

Log:
`C:\Procdump>procdump -e -ma -w sunshine.exe

ProcDump v11.0 - Sysinternals process dump utility
Copyright (C) 2009-2022 Mark Russinovich and Andrew Richards
Sysinternals - www.sysinternals.com

Waiting for process named sunshine.exe...

Process:               sunshine.exe (19244)
Process image:         C:\Program Files\Sunshine\sunshine.exe
CPU threshold:         n/a
Performance counter:   n/a
Commit threshold:      n/a
Threshold seconds:     n/a
Hung window check:     Disabled
Log debug strings:     Disabled
Exception monitor:     Unhandled
Exception filter:      [Includes]
                       *
                       [Excludes]
Terminate monitor:     Disabled
Cloning type:          Disabled
Concurrent limit:      n/a
Avoid outage:          n/a
Number of dumps:       1
Dump folder:           C:\Procdump\
Dump filename/mask:    PROCESSNAME_YYMMDD_HHMMSS
Queue to WER:          Disabled
Kill after dump:       Disabled


Press Ctrl-C to end monitoring without terminating the process.

[14:29:26] Process Exit: PID 19244, Exit Code 0x00000000
[14:29:26] The process has exited.
[14:29:26] Dump count not reached.


C:\Procdump>procdump -e -ma -w sunshine.exe

ProcDump v11.0 - Sysinternals process dump utility
Copyright (C) 2009-2022 Mark Russinovich and Andrew Richards
Sysinternals - www.sysinternals.com

Waiting for process named sunshine.exe...

Process:               sunshine.exe (4244)
Process image:         C:\Program Files\Sunshine\sunshine.exe
CPU threshold:         n/a
Performance counter:   n/a
Commit threshold:      n/a
Threshold seconds:     n/a
Hung window check:     Disabled
Log debug strings:     Disabled
Exception monitor:     Unhandled
Exception filter:      [Includes]
                       *
                       [Excludes]
Terminate monitor:     Disabled
Cloning type:          Disabled
Concurrent limit:      n/a
Avoid outage:          n/a
Number of dumps:       1
Dump folder:           C:\Procdump\
Dump filename/mask:    PROCESSNAME_YYMMDD_HHMMSS
Queue to WER:          Disabled
Kill after dump:       Disabled


Press Ctrl-C to end monitoring without terminating the process.

[14:30:06] Exception: C0000005.ACCESS_VIOLATION
[14:30:06] Unhandled: C0000005.ACCESS_VIOLATION
[14:30:06] Dump 1 initiated: C:\Procdump\sunshine.exe_230809_143006.dmp
[14:30:07] Dump 1 writing: Estimated dump file size is 218 MB.
[14:30:10] Dump 1 complete: 218 MB written in 3.1 seconds
[14:30:10] Dump count reached.


C:\Procdump>procdump -e -ma -w sunshine.exe

ProcDump v11.0 - Sysinternals process dump utility
Copyright (C) 2009-2022 Mark Russinovich and Andrew Richards
Sysinternals - www.sysinternals.com

Waiting for process named sunshine.exe...

Process:               sunshine.exe (18736)
Process image:         C:\Program Files\Sunshine\sunshine.exe
CPU threshold:         n/a
Performance counter:   n/a
Commit threshold:      n/a
Threshold seconds:     n/a
Hung window check:     Disabled
Log debug strings:     Disabled
Exception monitor:     Unhandled
Exception filter:      [Includes]
                       *
                       [Excludes]
Terminate monitor:     Disabled
Cloning type:          Disabled
Concurrent limit:      n/a
Avoid outage:          n/a
Number of dumps:       1
Dump folder:           C:\Procdump\
Dump filename/mask:    PROCESSNAME_YYMMDD_HHMMSS
Queue to WER:          Disabled
Kill after dump:       Disabled


Press Ctrl-C to end monitoring without terminating the process.

[14:30:21] Exception: C0000005.ACCESS_VIOLATION
[14:30:21] Unhandled: C0000005.ACCESS_VIOLATION
[14:30:21] Dump 1 initiated: C:\Procdump\sunshine.exe_230809_143021.dmp
[14:30:21] Dump 1 writing: Estimated dump file size is 215 MB.
[14:30:23] Dump 1 complete: 215 MB written in 1.7 seconds
[14:30:23] Dump count reached.


C:\Procdump>procdump -e -ma -w sunshine.exe

ProcDump v11.0 - Sysinternals process dump utility
Copyright (C) 2009-2022 Mark Russinovich and Andrew Richards
Sysinternals - www.sysinternals.com

Waiting for process named sunshine.exe...

[14:30:44] Multiple processes match the specified name.

C:\Procdump>procdump -e -ma -w sunshine.exe

ProcDump v11.0 - Sysinternals process dump utility
Copyright (C) 2009-2022 Mark Russinovich and Andrew Richards
Sysinternals - www.sysinternals.com

Waiting for process named sunshine.exe...

Process:               sunshine.exe (18696)
Process image:         C:\Program Files\Sunshine\sunshine.exe
CPU threshold:         n/a
Performance counter:   n/a
Commit threshold:      n/a
Threshold seconds:     n/a
Hung window check:     Disabled
Log debug strings:     Disabled
Exception monitor:     Unhandled
Exception filter:      [Includes]
                       *
                       [Excludes]
Terminate monitor:     Disabled
Cloning type:          Disabled
Concurrent limit:      n/a
Avoid outage:          n/a
Number of dumps:       1
Dump folder:           C:\Procdump\
Dump filename/mask:    PROCESSNAME_YYMMDD_HHMMSS
Queue to WER:          Disabled
Kill after dump:       Disabled


Press Ctrl-C to end monitoring without terminating the process.

[14:30:50] Exception: C0000005.ACCESS_VIOLATION
[14:30:50] Unhandled: C0000005.ACCESS_VIOLATION
[14:30:50] Dump 1 initiated: C:\Procdump\sunshine.exe_230809_143050.dmp
[14:30:50] Dump 1 writing: Estimated dump file size is 217 MB.
[14:30:52] Dump 1 complete: 217 MB written in 1.8 seconds
[14:30:52] Dump count reached.
`

**Comment by cgutman** [comment]
Thanks. As I suspected, AMD encoder is crashing when we're trying to test for working encoders. 

```
0:000> k
 # Child-SP          RetAddr               Call Site
00 000000ce`437fe7a0 00007ffe`82f052f9     amfrt64+0x11eaba
01 000000ce`437fe860 00007ffe`82f63a87     amfrt64+0x1152f9
02 000000ce`437febb0 00007ffe`82e48fae     amfrt64+0x173a87
03 000000ce`437ff260 00007ff6`ec549993     amfrt64+0x58fae
04 000000ce`437ff3c0 00007ff6`ec53dc95     sunshine!ff_amf_receive_packet+0x933 [D:\a\build-deps\build-deps\ffmpeg_sources\ffmpeg\libavcodec\amfenc.c @ 814] 
05 000000ce`437ff4f0 00007ff6`ec53e4e9     sunshine!encode_receive_packet_internal+0x4e5 [D:\a\build-deps\build-deps\ffmpeg_sources\ffmpeg\libavcodec\encode.c @ 295] 
06 000000ce`437ff590 00007ff6`ec4a6506     sunshine!avcodec_send_frame+0xb9 [D:\a\build-deps\build-deps\ffmpeg_sources\ffmpeg\libavcodec\encode.c @ 381] 
07 000000ce`437ff600 00007ff6`ec4abf96     sunshine!encode+0x36 [D:\a\Sunshine\Sunshine\src\video.cpp @ 1006] 
08 000000ce`437ff720 00007ff6`ec4ac813     sunshine!validate_config+0x3e6 [D:\a\Sunshine\Sunshine\src\video.cpp @ 1836] 
09 000000ce`437ff890 00007ff6`ec4ad53f     sunshine!validate_encoder+0x723 [D:\a\_temp\msys64\mingw64\include\c++\13.1.0\bitset @ 425] 
0a 000000ce`437ff9c0 00007ff6`edab6a28     sunshine!probe_encoders+0xaaf [D:\a\Sunshine\Sunshine\src\video.cpp @ 2049] 
0b 000000ce`437ffa80 00007ff6`ec4512ee     sunshine!main+0x828 [D:\a\Sunshine\Sunshine\src\main.cpp @ 624] 
0c 000000ce`437ffc50 00007ff6`ec451406     sunshine!__tmainCRTStartup+0x16e [C:\M\B\src\mingw-w64\mingw-w64-crt\crt\crtexe.c @ 273] 
0d 000000ce`437ffca0 00007ffe`eb2f26ad     sunshine!mainCRTStartup+0x16 [C:\M\B\src\mingw-w64\mingw-w64-crt\crt\crtexe.c @ 195] 
0e 000000ce`437ffcd0 00007ffe`ec40aa68     kernel32!BaseThreadInitThunk+0x1d
0f 000000ce`437ffd00 00000000`00000000     ntdll!RtlUserThreadStart+0x28
```

It looks like it's happening during HEVC Main10 encoder tests which old hardware like this doesn't even support, so I made a possible fix to avoid probing HEVC Main10 on older drivers.

Please try this build https://github.com/LizardByte/Sunshine/suites/14970304158/artifacts/854085489 (need to be signed in with your GitHub account for the link to work). If this build doesn't work, please attach new logs and a new dump file.

**Comment by system198** [comment]
> Thanks. As I suspected, AMD encoder is crashing when we're trying to test for working encoders.
> 
> Please try this build https://github.com/LizardByte/Sunshine/suites/14970304158/artifacts/854085489 (need to be signed in with your GitHub account for the link to work). If this build doesn't work, please attach new logs and a new dump file.

Thank you very much! I tried the build and it finally works without any issues. Cheers
