### ISSUE TITLE
Silverblue install error

### ISSUE THREAD

**Issue by morphiak** [LizardByte/Sunshine#1510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Try to install via flatpak on Kinoite 38
1. `flatpak install dev.lizardbyte.app.Sunshine`
2. `flatpak run --command=additional-install.sh dev.lizardbyte.sunshine`

results in 
`error: app/dev.lizardbyte.sunshine/x86_64/master not installed`

### Expected Behavior

no error

### Additional Context

Said Silverblue because it's almost certainly there too, and people can search it.
Tried on a Nvidia/AMD desktop (X11) and an intel laptop (wayland).

Workaround, install in a fedora distrobox (I imagine toolbox as well) as a rpm, works fine.
Thought you should know...

### Host Operating System

Linux

### Operating System Version

Kinoite 38

### Architecture

64 bit

### Sunshine commit or version

current flatpak

### Package

Linux - flatpak

### GPU Type

Nvidia

### GPU Model

980

### GPU Driver/Mesa Version

mesa-dri-drivers-23.1.4-1.fc38.x86_64

### Config

```Shell
Happens prior to that.
```

### Relevant log output

```shell
error: app/dev.lizardbyte.sunshine/x86_64/master not installed
FAIL
```

**Comment by ReenigneArcher** [comment]
This issue should be moved here: https://github.com/flathub/dev.lizardbyte.app.Sunshine

Unless you can reproduce it with the flatpak we publish in GitHub releases.

**Comment by morphiak** [comment]
Fair enough. You might consider putting a line in the fedora install doco saying a rpm install in a toolbox/distrobox works fine in Silverblue/Kinoite as we tend to knee jerk to flatpak. Just saying...

**Comment by ReenigneArcher** [comment]
I'm saying there are multiple flatpaks... one maintained by us... one that is maintained by the community. You are trying to use the one maintained by the community which is why I referred you there. The one we maintain is only available in releases. https://github.com/LizardByte/Sunshine/releases
