### ISSUE TITLE
steam deck windows sunshine and phone moonlight turns out blackscreen on phone but controller works 

### ISSUE THREAD

**Issue by theplayer666** [LizardByte/Sunshine#1514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Installed newest sunshine on steam deck windows, use moonlight on phone to stream to steamdeck, but only controller works, screen is black. Please fix this.
Logs:
[2023:08:09:00:03:24]: Info: SDR color coding [Rec. 709]
[2023:08:09:00:03:24]: Info: Color range: [MPEG]
[2023:08:09:00:03:24]: Info: Capture format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:09:00:03:24]: Info: Capture size changed [1280x800 -> 800x1280]
[2023:08:09:00:03:24]: Info:
Device Description : AMD Custom GPU 0405
Device Vendor ID   : 0x00001002
Device Device ID   : 0x0000163F
Device Video Mem   : 4073 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 6066 MiB
Feature Level      : 0x0000B100
Capture size       : 1280x800
Offset             : 0x0
Virtual Desktop    : 1280x800
[2023:08:09:00:03:24]: Info: Desktop resolution [1280x800]
[2023:08:09:00:03:24]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:09:00:03:24]: Info:
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.000624657,0.000322342]
Green Primary      : [0.000292778,0.000585556]
Blue Primary       : [0.000145912,5.81741e-05]
White Point        : [0.000305176,0.000321388]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:08:09:00:03:24]: Info: SDR color coding [Rec. 709]
[2023:08:09:00:03:24]: Info: Color range: [MPEG]
[2023:08:09:00:03:24]: Info: Capture format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:09:00:03:24]: Info: Capture size changed [1280x800 -> 800x1280]

### Host Operating System

Windows

### Operating System Version

win11

### Architecture

64 bit

### Sunshine commit or version

0.20.0

### Package

Windows - portable

### GPU Type

AMD

### GPU Model

AMD Custom GPU 0405

### GPU Driver/Mesa Version

steamdeck's

### Config

```Shell
fps = [10,30,60,90,120]
vt_coder = auto
amd_rc = vbr_latency
vt_realtime = enabled
key_rightalt_to_key_win = disabled
resolutions = [
    352x240,
    480x360,
    858x480,
    1280x720,
    1920x1080,
    2560x1080,
    3440x1440,
    1920x1200,
    3860x2160,
    3840x1600,
    1280x800
]
origin_pin_allowed = pc
gamepad = x360
nv_coder = auto
dwmflush = enabled
min_log_level = 2
vt_software = auto
amd_quality = balanced
origin_web_ui_allowed = lan
nv_rc = cbr
hevc_mode = 0
nv_tune = ull
nv_preset = p7
upnp = disabled
amd_coder = auto
```

### Relevant log output

```shell
[2023:08:09:00:03:24]: Info: SDR color coding [Rec. 709]
[2023:08:09:00:03:24]: Info: Color range: [MPEG]
[2023:08:09:00:03:24]: Info: Capture format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:09:00:03:24]: Info: Capture size changed [1280x800 -> 800x1280]
[2023:08:09:00:03:24]: Info:
Device Description : AMD Custom GPU 0405
Device Vendor ID   : 0x00001002
Device Device ID   : 0x0000163F
Device Video Mem   : 4073 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 6066 MiB
Feature Level      : 0x0000B100
Capture size       : 1280x800
Offset             : 0x0
Virtual Desktop    : 1280x800
[2023:08:09:00:03:24]: Info: Desktop resolution [1280x800]
[2023:08:09:00:03:24]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:09:00:03:24]: Info:
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.000624657,0.000322342]
Green Primary      : [0.000292778,0.000585556]
Blue Primary       : [0.000145912,5.81741e-05]
White Point        : [0.000305176,0.000321388]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:08:09:00:03:24]: Info: SDR color coding [Rec. 709]
[2023:08:09:00:03:24]: Info: Color range: [MPEG]
[2023:08:09:00:03:24]: Info: Capture format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:09:00:03:24]: Info: Capture size changed [1280x800 -> 800x1280]
```

**Comment by ReenigneArcher** [comment]
I think it's related to the rotated display.

**Comment by pearce31** [comment]
Same problem aokzoe

**Comment by pearce31** [comment]
There's a fix for the time being.
Create a virtual monitor I used usbmmidd.
Run dxgi-info.exe in cmd prompt from within program files/sunshine/tools folder. Get the virtual screen display number from it. Go into sunshine web interface then to configuration video and scroll down and enter the display number you got from cmd in the correct format click save then apply.  Now it should work and you can change the resolution in windows display settings.

**Comment by Nonary** [comment]
You’ll need to use a virtual monitor or attach a HDMI dummy plug to use Sunshine on Windows on the Steam Deck. This is a security limitation of the API calls we use to capture the display that is specific to windows, there is no workaround for that and the only way we could resolve is by using an virtual screen ourselves but that is complicated because it would require a signed driver which costs money.

Closing this out as not an issue, since there isn’t really anything we can do to resolve. As mentioned earlier, the solution is to use a virtual screen. Please keep in mind that virtual screens are not perfect and your best bet would be to get an HDMI dummy plug.

**Comment by bobbyl140** [comment]
> Changing the orientation to portrait gave me picture no black screen but the resolutions are unusable but there's a fix for the time being. Create a virtual monitor I used usbmmidd. Run dxgi-info.exe in cmd prompt from within program files/sunshine/tools folder. Get the virtual screen display number from it. Go into sunshine web interface then to configuration video and scroll down and enter the display number you got from cmd in the correct format click save then apply. Now it should work and you can change the resolution in windows display settings.

@pearce31 I am experiencing this, and I wanted to ask what your exact solution was. I am about to get usbmmid, but I don't want to leave a virtual display running 24/7 as that would inhibit normal use. I was thinking I could add the usbmmid command as a pre-exec for all apps, then somehow close it afterwards? But I still don't know how this would work, as apps might choose to open on the main display, which would result in them being inaccessible remotely. If I set the display to mirror, would that work? Thanks.

**Comment by bobbyl140** [comment]
@Nonary I ended up installing [this virtual display driver](https://github.com/itsmikethetech/Virtual-Display-Driver), and from what I can tell, part of the install process is to import a custom code-signing certificate so that paying isn't needed. Would this be possible/viable? From my testing since my last comment, I can't have both the ability to play games remotely and the ability to use the Steam Deck normally, unless I install and uninstall the virtual display every time.

**Comment by bobbyl140** [comment]
@Nonary still wondering about this, as I really wish I could stream from my Steam Deck. Steam Link is able to capture the screen, is there any way Sunshine could implement something like that?

**Comment by popcornman209** [comment]
same issue here, trying to use windows on the steam deck. dont see any reason this shouldnt work (from someone who doesnt know what tf they are saying) as its just any normal screen but rotated 90 degrees. using the virtual display driver works but only when extending the screen, not duplicating it.
