### ISSUE TITLE
Sound device taken away from opened program on disconnect

### ISSUE THREAD

**Issue by henry2k** [LizardByte/Sunshine#1546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

After I get disconnected and reconnect to sunshine via moonlight the audio-device is reassigned instead of (like nvidia did) staying active, so opened programs that use this old device get disconnected and I have to restart (for example Adobe Premiere) so the audio-device is accessed again.

Programs that rely on a specific device on startup and seemingly don't reevaluate the devices will just freeze instead of playing audio like they should.

### Expected Behavior

Virtual audio device will stay active even when disconnected until the streamed program (like desktop) is closed so programs don't crash.

### Host Operating System

Windows

### Operating System Version

Windows 10, latest updates

### Architecture

64 bit

### Sunshine commit or version

20.2

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

GTX 1660 SUPER

### GPU Driver/Mesa Version

536.23

### Config

```Shell
fps = [30,60]
nv_rc = vbr
resolutions = [
    1280x720,
    1920x1080
]
```

### Relevant log output

```shell
no log
```

**Comment by reinra** [comment]
It seems I have a similar issue with latest version.
When reconnecting to remote PC audio is lost.
If I restart the app/game the audio is restored.
This is quite inconvenient.

**Comment by reinra** [comment]
It seems I have a similar issue with latest version.
When reconnecting to remote PC audio is lost.
If I restart the app/game the audio is restored.
This is quite inconvenient.
