### ISSUE TITLE
CertPathvalidatorException when using from behind a proxy

### ISSUE THREAD

**Issue by eddie-LA** [LizardByte/Sunshine#1550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

My laptop has Zscaler on it. That is the issue.
Moonlight discovers my laptop's okay and asks for PIN but after I put that in I get `java.security.cert.CertPathValidatorException: Trust anchor for certification path not found` on my Android TV's side. No connection.

### Expected Behavior

To connect and work, like Parsec and Steam Link.

### Host Operating System

Windows

### Operating System Version

Windows 10 22H2, 19045.3208

### Architecture

64 bit

### Sunshine commit or version

0.20.0

### Package

Windows - portable

### GPU Type

AMD

### GPU Model

AMD Barcelo - Internal GPU [Lenovo]

### GPU Driver/Mesa Version

23.7.2

### Config

```Shell
origin_pin_allowed = lan
fps = [10,30,60,90,120,75]
resolutions = [
    352x240,
    480x360,
    858x480,
    1280x720,
    1920x1080,
    2560x1080,
    3440x1440,
    1920x1200,
    3840x1600,
    2560x1440
]
```

### Relevant log output

```shell
[2023:08:16:22:22:26]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2023:08:16:22:22:26]: Info: 
[2023:08:16:22:22:26]: Info: Found encoder amdvce: [h264_amf, hevc_amf]
[2023:08:16:22:22:26]: Info: Configuration UI available at [https://localhost:47990]
[2023:08:16:22:22:27]: Info: Registered Sunshine mDNS service
[2023:08:16:22:22:49]: Info: Web UI: [127.0.0.1] -- not authorized
[2023:08:16:22:22:50]: Info: Web UI: [127.0.0.1] -- not authorized
[2023:08:16:22:23:08]: Info: Opening UI from system tray
[2023:08:16:22:23:08]: Info: cmd /C "start https://localhost:47990" running with PID 44904
[2023:08:16:22:23:08]: Info: Opened url [https://localhost:47990]
[2023:08:16:22:23:09]: Info: Web UI: [127.0.0.1] -- not authorized
[2023:08:16:22:23:49]: Info: Web UI: [127.0.0.1] -- not authorized
```

**Comment by cgutman** [comment]
The cert validation error is expected in this scenario.

The pairing process performs certificate pinning between the client and the host to prevent attackers from impersonating them. Without this, an attacker could trick you into connecting and sending sensitive data like keypresses to them.

Zscaler's forged certificate for the host doesn't match the certificate established during the secure pairing process, so the connection is rejected by the client.

The only way to address this is to adjust Zscaler settings to prevent it from trying to inspect Moonlight/Sunshine traffic.

**Comment by eddie-LA** [comment]
Yeah, that adjustment is not happening. My point was that similar software works alright, so there must be other ways to do it. Adding the ZScaler cert on the client device's end may work but it's very difficult if possible at all on recent versions of Android TV.
I have secured my network well enough. Is there a way to disable certificate pinning then?

**Comment by cgutman** [comment]
Certificate pinning that takes place during the pairing process is the foundation of the whole decentralized trust model of GameStream (similar to how PIN-based pairing works with Bluetooth devices or WPS for Wi-Fi). Other software has centralized servers that perform "pairing" via account username/password or simply requires username/password for each connection.

Disabling certificate pinning would be equivalent to allowing anyone to stream from your host with no authentication (or intercept your traffic and log your keystrokes), so it is definitely not an option that we will provide. One-time connections or username/password authentication could be introduced in the future, but that isn't going to be done any time soon.
