### ISSUE TITLE
Sunshine keeps disabling file and printer sharing

### ISSUE THREAD

**Issue by SloppyGoat** [LizardByte/Sunshine#1595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I keep having to reenable file and printer sharing, each time I use it. 

### Host Operating System

Windows

### Operating System Version

Win 10 Pro 22H2

### Architecture

64 bit

### Sunshine commit or version

.20

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

RTX 3060

### GPU Driver/Mesa Version

537.13

### Config

```Shell
min_log_level = 6
```

### Relevant log output

```shell
Nothing in there
```

**Comment by ReenigneArcher** [comment]
Sunshine does not enable or disable these features.

**Comment by SloppyGoat** [comment]
It sure as hell does!! It only happens right after I use that app. Not every time, but almost every time. And nothing else does that.

**Comment by ReenigneArcher** [comment]
There is nothing in Sunshine's code that touches those Windows settings. With that said, there is no place in this organization for disrespectful comments like that.
