### ISSUE TITLE
audio-info.exe showing only 1 device

### ISSUE THREAD

**Issue by Eyji** [LizardByte/Sunshine#1599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

When executing audio-info.exe with elevated rights using both cmd and powershell, I only get 1 unnamed device 

PS C:\Program Files\Sunshine\tools> .\audio-info.exe
====== Found 4 audio devices ======
===== Device =====
Device ID          : {0.0.0.00000000}.{220e1f93-2b90-4b98-b0d4-621b6882e6ee}
Device name        :

### Expected Behavior

All the devices, their names and instance id

### Additional Context

All the devices, their names and intance id.
Using the following command works fine
` Get-PnpDevice -Class AudioEndpoint | Select-Object InstanceId, FriendlyName`

### Host Operating System

Windows

### Operating System Version

Windows 11 

### Architecture

64 bit

### Sunshine commit or version

0.20

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

3070

### GPU Driver/Mesa Version

537.13

### Config

```Shell
Irrelevant
```

### Relevant log output

```shell
Get-PnpDevice -Class AudioEndpoint | Select-Object InstanceId, FriendlyName
```

**Comment by Nonary** [comment]
Please paste the results from running: 

Get-PnpDevice -Class AudioEndpoint | Select-Object InstanceId, FriendlyName

**Comment by Eyji** [comment]
`InstanceId                                                           FriendlyName
----------                                                           ------------
SWD\MMDEVAPI\{0.0.1.00000000}.{96697FAE-1CCA-4A3F-B5FD-D5667B2D6007} Microphone (Realtek(R) Audio)
SWD\MMDEVAPI\{0.0.1.00000000}.{4F6C1597-6FDE-4A5C-9921-21A4436B2313} Microphone (Realtek(R) Audio)
SWD\MMDEVAPI\{0.0.0.00000000}.{2BCE9636-EFF9-4483-9210-6B2B33A32E14} 27GL850 (NVIDIA High Definition Audio)
SWD\MMDEVAPI\{0.0.0.00000000}.{947EF60F-2C41-4D88-8A6C-F11083E53B7B} Casque (Realtek(R) Audio)
SWD\MMDEVAPI\{0.0.0.00000000}.{65BB7189-0499-4431-89D7-3D0C7B85606C} LG HDR 4K (NVIDIA High Definition Audio)
SWD\MMDEVAPI\{0.0.0.00000000}.{4F721E43-FE04-4632-9AEA-FC5BAE947A37} Realtek Digital Output (Realtek(R) Audio)
SWD\MMDEVAPI\{0.0.0.00000000}.{4EF16D41-B08B-4AA0-A01D-E6945FD79F92} Digital Audio (S/PDIF) (High Definition Audio Dev…
SWD\MMDEVAPI\{0.0.1.00000000}.{9088DA74-AA7A-4DCE-845A-D8BF2E08AE70} Microphone (High Definition Audio Device)
SWD\MMDEVAPI\{0.0.1.00000000}.{A43606AD-E1DE-41A8-8D38-7244242BA68C} Microphone (Logitech BRIO)
SWD\MMDEVAPI\{0.0.0.00000000}.{42B71DB4-BB3A-4A09-8F1A-495616DA6CBA} LG HDR 4K (NVIDIA High Definition Audio)
SWD\MMDEVAPI\{0.0.0.00000000}.{9D8C04DA-6F8D-48CF-80F4-9C7DDBD03076} Haut-parleurs (Realtek(R) Audio)
SWD\MMDEVAPI\{0.0.0.00000000}.{AEEA8B39-3EEA-4592-8B8B-AC3691AC795D} 27GL850 (NVIDIA High Definition Audio)


`

**Comment by mostm** [comment]
I have the same issue, and it's caused by Sunshine failing to properly decode device description.
Rename all of your speakers in Windows to something with english letters only. That seems to fix it.
(You can do that by going to Windows Settings -> System -> Sound (on the left) -> Audio Control Panel (on the right) -> Double click on speakers/headset -> Rename to something -> Click OK, and now do that for every speaker set you have installed)

As for the test case, developers may use name `Динамики` description which is present on Russian installations of Windows by default.

**Comment by BlueD** [comment]
> I have the same issue (was present for as long as I can remember using Sunshine), and it's caused by Sunshine failing to properly decode device description. Rename all of your speakers in Windows to something with english letters only. That seems to fix it. (You can do that by going to Windows Settings -> System -> Sound (on the left) -> Audio Control Panel (on the right) -> Double click on speakers/headset -> Rename to something -> Click OK, and now do that for every speaker set you have installed)
> 
> As for the test case, developers may use `Динамики` description which is present on Russian installations of Windows by default.

Same here.
Thanks for your suggestion.
