### ISSUE TITLE
[Arch] NVENC not being recognised

### ISSUE THREAD

**Issue by r0m5s** [LizardByte/Sunshine#1668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

After updating arch to Linux 6.5 and Nvidia 535.104.05 drivers with the nvidia-utils-nvlax 535.104.05-1, sunshine stopped recognising the encoder and therefore starting. I'm running my desktop headless with a HDMI dongle.

I have a backup before the changes and If I get back to 6.4 kernel there's no issues starting the stream. Already tried building the nightly build and rebuilding my install and still nothing. I also get a error 503.

I know that the NvFBC patch is working since the output from ffmpeg test lines (from keylase/nvidia-patch) work without any issues.

### Expected Behavior

Stream should start without any errors

### Host Operating System

Linux

### Operating System Version

Linux 6.5.4-zen2-1-zen #1 ZEN SMP PREEMPT_DYNAMIC

### Architecture

64 bit

### Sunshine commit or version

0.20.0

### Package

Linux - AUR (Third Party)

### GPU Type

Nvidia

### GPU Model

GeForce GTX 1050 Ti

### GPU Driver/Mesa Version

535.104.05

### Capture Method (Linux Only)

NvFBC

### Config

```Shell
min_log_level = 1
nvenc_preset = 4
fps = [30,60,90,120]
resolutions = [
    352x240,
    480x360,
    858x480,
    1280x720,
    1920x1080,
    2560x1080,
    3440x1440,
    1920x1200,
    3840x2160,
    3840x1600,
    1280x800
]
capture = nvfbc
encoder = nvenc
output_name = 1
```

### Relevant log output

```shell
[2023:09:23:11:21:08]: Info: Sunshine version: 0.20.0
[2023:09:23:11:21:08]: Error: Unable to initialize capture method
[2023:09:23:11:21:08]: Error: Platform failed to initialize
[2023:09:23:11:21:08]: Info: Trying encoder [nvenc]
[2023:09:23:11:21:08]: Info: System tray created
[2023:09:23:11:21:09]: Info: Encoder [nvenc] failed
[2023:09:23:11:21:09]: Error: Couldn't find any working encoder matching [nvenc]
[2023:09:23:11:21:09]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2023:09:23:11:21:09]: Info: Trying encoder [vaapi]
[2023:09:23:11:21:11]: Info: Encoder [vaapi] failed
[2023:09:23:11:21:11]: Info: Trying encoder [software]
[2023:09:23:11:21:13]: Info: Encoder [software] failed
[2023:09:23:11:21:13]: Fatal: Couldn't find any working encoder
[2023:09:23:11:21:13]: Error: Video failed to find working encoder
[2023:09:23:11:21:13]: Info: Adding avahi service Sunshine
[2023:09:23:11:21:13]: Info: Configuration UI available at [https://localhost:47990]
[2023:09:23:11:21:14]: Info: Avahi service Sunshine successfully established.
```

**Comment by v1nsai** [comment]
Are you trying to connect to a headless server?  I've been wrestling with a similar error finding encoders on my headless linux server (with dummy hdmi plug) for a few days now.  Running `sudo setcap cap_sys_admin+p $(readlink -f $(which sunshine))` has been said to fix this issue, but didn't affect anything for me.

Finally I decided to try logging into remote desktop with NoMachine.  I logged in, opened a terminal in the remote desktop and ran `sunshine`.  It found `nvenc` encoders finally!  It threw some other errors but the log output literally said "ignore errors above" so I did and all works now!

Not sure if there's a better way to get headless servers to work but this has gotten me moving again.  I had my desktop manager enabled, and I even tried logging in but it seems like sunshine expects to be run from an active (virtual) display.

**Comment by KuleRucket** [comment]
Long shot, but if you are using zsh or anything other than bash you need to ensure that nvcc is in your path before installing sunshine with nvidia. This is because the nvidia driver packages assumes you are using bash and sets the path in the profile file.

@v1nsai cap_sys_admin is for setting up KMS screen capture, it is not relevant to nvfbc capture or anything related to encoding.

**Comment by lencio** [comment]
> Long shot, but if you are using zsh or anything other than bash you need to ensure that nvcc is in your path before installing sunshine with nvidia. This is because the nvidia driver packages assume you are using bash and sets the path in the profile file.
> 
> @v1nsai cap_sys_admin is for setting up KMS screen capture, it is not relevant to nvfbc capture or anything related to encoding.

Cap_sys_admin is irrelevant. Sunshine not works on Wayland. I have the same problem, switch to X11 and works like a charm.

**Comment by KuleRucket** [comment]
> > Long shot, but if you are using zsh or anything other than bash you need to ensure that nvcc is in your path before installing sunshine with nvidia. This is because the nvidia driver packages assume you are using bash and sets the path in the profile file.
> > @v1nsai cap_sys_admin is for setting up KMS screen capture, it is not relevant to nvfbc capture or anything related to encoding.
> 
> Cap_sys_admin is irrelevant. Sunshine not works on Wayland. I have the same problem, switch to X11 and works like a charm.

If you look up there ^^^ to the config supplied, it says "capture = nvfbc", cap_sys_admin is only required for KMS capture.

**Comment by KuleRucket** [comment]
> > Long shot, but if you are using zsh or anything other than bash you need to ensure that nvcc is in your path before installing sunshine with nvidia. This is because the nvidia driver packages assume you are using bash and sets the path in the profile file.
> > @v1nsai cap_sys_admin is for setting up KMS screen capture, it is not relevant to nvfbc capture or anything related to encoding.
> 
> Cap_sys_admin is irrelevant. Sunshine not works on Wayland. I have the same problem, switch to X11 and works like a charm.

Reading is hard isn't it?

**Comment by r0m5s** [comment]
> Long shot, but if you are using zsh or anything other than bash you need to ensure that nvcc is in your path before installing sunshine with nvidia. This is because the nvidia driver packages assume you are using bash and sets the path in the profile file.
> 
> @v1nsai cap_sys_admin is for setting up KMS screen capture, it is not relevant to nvfbc capture or anything related to encoding.

And it was spot on! Indeed CUDA was installed no problems but I needed to add these lines to .bashrc so nvcc was used:
```
export PATH=/opt/cuda/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/opt/cuda/lib64
```
I don't remember if the path was detected before or if it got removed after the update, but anyways.

Compiled sunshine again using bash (was using fish before) and it got detected.

> [2023:09:30:10:32:46]: Info: Sunshine version: 0.20.0
> [2023:09:30:10:32:46]: Info: System tray created
> [2023:09:30:10:32:46]: Info: Found [1] outputs
> [2023:09:30:10:32:46]: Info: Virtual Desktop: 1920x1080
> [2023:09:30:10:32:46]: Info: XrandR: available
> [2023:09:30:10:32:46]: Info: -- Output --
> [2023:09:30:10:32:46]: Info:   Resolution: 1920x1080
> [2023:09:30:10:32:46]: Info:   Offset: 0x0
> [2023:09:30:10:32:46]: Error: Couldn't destroy session handle: Unable to cleanup NvFBC
> [2023:09:30:10:32:46]: Info: Trying encoder [nvenc]
> [2023:09:30:10:32:46]: Info: Screencasting with NvFBC
> [2023:09:30:10:32:46]: Info: SDR color coding [Rec. 601]
> [2023:09:30:10:32:46]: Info: Color range: [JPEG]
> [2023:09:30:10:32:46]: Error: Could not open codec [h264_nvenc]: Function not implemented
> [2023:09:30:10:32:46]: Error: Couldn't destroy session handle: The context is not bound
> [2023:09:30:10:32:46]: Info: Screencasting with NvFBC

Thanks. :)

**Comment by lencio** [comment]
> > > Long shot, but if you are using zsh or anything other than bash you need to ensure that nvcc is in your path before installing sunshine with nvidia. This is because the nvidia driver packages assume you are using bash and sets the path in the profile file.
> > > @v1nsai cap_sys_admin is for setting up KMS screen capture, it is not relevant to nvfbc capture or anything related to encoding.
> > 
> > 
> > Cap_sys_admin is irrelevant. Sunshine not works on Wayland. I have the same problem, switch to X11 and works like a charm.
> 
> Reading is hard isn't it?

From what I see, it is worse for you to admit a mistake than for me to read ;)

**Comment by ReenigneArcher** [comment]
A. Sunshine does work on wayland!
B. I'm locking this thread.
