### ISSUE TITLE
Can't map port and fails to enable remote streaming

### ISSUE THREAD

**Issue by NovaMoon** [LizardByte/Sunshine#172]
### Describe the Bug

When i start sunshine with upnp enabled it get either error

`Error: Failed to map port [48010] to port [48010]: error code [403]
`
or 
`Error: Failed to map port [48010] to port [48010]: error code [606]
`

### Expected Behavior

Opening the ports through my router and enable remote streaming

### Sunshine Host Operating System and Version

Arch

### Architecture

64bit

### Sunshine Version

0.13.0

### GPU Type

Nvidia

### GPU Model

GTX 1080

### GPU Driver/Mesa Version

515.48.07

### Capture Method (Linux Only)

X11

**Comment by ReenigneArcher** [comment]
Probably better off asking in AUR. I'm guessing this is a permissions issue.
