### ISSUE TITLE
Usage > Windows documentation links to retired project ViGEmBus

### ISSUE THREAD

**Issue by jfly** [LizardByte/Sunshine#1741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

The [Usage > Windows documentation](https://docs.lizardbyte.dev/projects/sunshine/en/latest/about/usage.html#windows) says:

> For gamepad support, install [ViGEmBus](https://github.com/ViGEm/ViGEmBus/releases/latest)

However, as of [September 8](https://github.com/nefarius/ViGEmBus/commit/d986e1d93708ec9b11049542fa6027272cce716c), it looks like ViGEmBus is "retired". According to [the EOL statement](https://docs.nefarius.at/projects/ViGEm/End-of-Life/):

> This has no impact on existing installations except for the updater components: their auto-updaters need to be adjusted to prevent a potential security risk!

So, this might be fine, but it sure would be nice if the docs could say something about this before linking to an archived GitHub repo.

<hr>
(rest of the bug issue template omitted as it is not applicable)

**Comment by ReenigneArcher** [comment]
This has already been updated in `nightly`.

https://docs.lizardbyte.dev/projects/sunshine/en/nightly/about/usage.html#windows

**Comment by jfly** [comment]
Ah, sorry I missed that, @ReenigneArcher!

I believe that the [latest release of `nefarius/ViGEmBus`](https://github.com/nefarius/ViGEmBus/releases/tag/v1.21.442.0) (1.21.442 at time of writing) suffers from the "potential security risk" described [here](https://docs.nefarius.at/projects/ViGEm/End-of-Life/#about-the-update-warnings). 1.21.442 was released in Aug 30, 2022, long before any of this [trademark stuff started in May 2023](https://fosstodon.org/@Nefarius/111062829193071136). Here's [the relevant code in `nefarius/ViGEmBus` v1.21.442.0](https://github.com/nefarius/ViGEmBus/blob/v1.21.442.0/setup/ViGEmBus.aip#L265):

```
    <ROW IniFile="URL" FileName="VIGEMB~1.INI|ViGEmBus_Updater.ini" DirProperty="APPDIR" Section="General" Key="URL" Value="https://updates.vigem.org/api/github/ViGEm/ViGEmBus/updates" Action="0" Component_="updater.exe"/>
```

(Note the problematic `updates.vigem.org` domain name.)

Fixing this requires either running Legacinator or some manual editing of ini files (as documented in the [EOL Statement](https://docs.nefarius.at/projects/ViGEm/End-of-Life/#adjusting-the-automatic-updater-configuration)). I think it would be a good idea for the Sunshine docs to tell people about this, as I had to do a *lot* of reading to understand the current state of things.

Separately, it sure would be nice if @nefarius would do one final release of `nefarius/ViGEmBus` with a fixed updater url just to save people this hassle, but I totally understand if they're just fed up with the whole situation.

**Comment by nefarius** [comment]
> Separately, it sure would be nice if @nefarius would do one final release of `nefarius/ViGEmBus` with a fixed updater url just to save people this hassle, but I totally understand if they're just fed up with the whole situation.

I still plan to do so, but one thing after another, as soon as my time allows it.

**Comment by nefarius** [comment]
> Separately, it sure would be nice if @nefarius would do one final release of `nefarius/ViGEmBus` with a fixed updater url just to save people this hassle, but I totally understand if they're just fed up with the whole situation.

[It's done](https://github.com/nefarius/ViGEmBus/releases/tag/v1.22.0). So glad I am done with it, this setup maker is pure pain.

**Comment by jfly** [comment]
Thanks so much @nefarius! Good luck with your future projects.
