### ISSUE TITLE
Adding "flatpak-spawn --host" to a command instantly crashes sunshine

### ISSUE THREAD

**Issue by HollyCeuin** [LizardByte/Sunshine#1780]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Title, running a command prefixed with that immediately crashes sunshine. 

### Expected Behavior

Not crashing

### Host Operating System

Linux

### Operating System Version

Pop!_OS 22.04

### Architecture

64 bit

### Sunshine commit or version

0.21.0.5bca024.dirty

### Package

Linux - flatpak

### GPU Type

AMD

### GPU Model

5600XT

### GPU Driver/Mesa Version

21.1.3

### Config

```Shell
min_log_level = 1
encoder = vaapi
fps = [60]
resolutions = [
    1920x1080
]
sunshine_name = HollyPC
```

### Apps

```json
{
    "env": {
        "PATH": "$(PATH):$(HOME)\/.local\/bin"
    },
    "apps": [
        {
            "name": "Desktop",
            "image-path": "desktop.png"
        },
        {
            "name": "20XX",
            "output": "",
            "cmd": "flatpak-spawn --host \"bash -c \/home\/holly\/SunshineLaunchers\/20XX.sh\"",
            "exclude-global-prep-cmd": "false",
            "elevated": "false",
            "auto-detach": "true",
            "image-path": "\/home\/holly\/.config\/sunshine\/covers\/igdb_17828.png",
            "working-dir": ""
        },
        {
            "name": "Elden Ring",
            "output": "",
            "cmd": "bash -c \/home\/holly\/SunshineLaunchers\/EldenRing.sh",
            "exclude-global-prep-cmd": "false",
            "elevated": "false",
            "auto-detach": "true",
            "image-path": "\/home\/holly\/.config\/sunshine\/covers\/igdb_119133.png"
        }
    ]
}
```

### Relevant log output

```shell
[2023:10:25:12:03:41]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2023:10:25:12:03:41]: Info: 
[2023:10:25:12:03:41]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2023:10:25:12:03:41]: Info: 
[2023:10:25:12:03:41]: Info: Found H.264 encoder: h264_vaapi [vaapi]
[2023:10:25:12:03:41]: Info: Found HEVC encoder: hevc_vaapi [vaapi]
[2023:10:25:12:03:41]: Info: Executing: [flatpak-spawn --host bash -c /home/holly/SunshineLaunchers/20XX.sh] in ["/usr/bin"]
[2023:10:25:12:03:41]: Info: App exited with code [256]
```

**Comment by ReenigneArcher** [comment]
I think Sunshine is still running, but the stream has ended?

That would be the expected behavior if your 20XX.sh script takes longer than a second or two to execute and fails (i.e. any exit code other than 0 is a failure). I'd suggest making it a a detached command.

"cmd" is for commands that are expected to run the entirety of the stream... "detached" is for shorter running commands.

Also, searching for exit code 256 seems to indicate this is a lutris error code.
