### ISSUE TITLE
Connection terminated immediately after connecting by IPV6 WAN

### ISSUE THREAD

**Issue by RagnarosXD** [LizardByte/Sunshine#1804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

My connection terminated immediately after connecting to the remote computer. I checked possbile two problem( ping/virtual sink audio devices), but seems the problem i faced is different.
The problem was occured only on Windows platform and using ipv6 WAN.  I have tried different devices and net work, only this particular combien have problem, please check below picture
![image](https://github.com/LizardByte/Sunshine/assets/75155739/c68f3a00-2c6d-4a5d-b65f-ddf4d7ba703f)

### Expected Behavior

It is really strange, through different combination test, I think there is no problem with my network or devices, but the problem has actually occurred.
This problem has been bugging me for a long time and I'd really appreciate any information or help.

### Host Operating System

Windows

### Operating System Version

Windwos 11 22H2

### Architecture

64 bit

### Sunshine commit or version

0.21.0

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

RTX 3070 Notebook

### GPU Driver/Mesa Version

537.42

### Config

```Shell
upnp = enabled
address_family = both
ping_timeout = 20000
```

### Relevant log output

```shell
[2023:10:31:20:58:11]: Info: Capture format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:10:31:20:58:11]: Info: SDR color coding [Rec. 601]
[2023:10:31:20:58:11]: Info: Color depth: 8-bit
[2023:10:31:20:58:11]: Info: Color range: [MPEG]
[2023:10:31:20:58:12]: Info: NvEnc: created encoder P1 two-pass rfi
[2023:10:31:20:58:12]: Warning: QOSAddSocketToFlow() failed: 1168
[2023:10:31:21:07:26]: Info: CLIENT DISCONNECTED
```

**Comment by NukedBart** [comment]
replicated on ipv4 lan

**Comment by Ravnger** [comment]
@RagnarosXD When you try to connect, do you see anything similar to this in the logs?
"Warning: Rejected connection from [::xxx:xxx.xxx.xxx.xxx]: it's not properly set up"
I also get an occational "Warning: QOSAddSocketToFlow() failed: 1168" error.

I've seen this issue mentioned in the Moonlight github sector as well.

**Comment by maxim-saplin** [comment]
Up, still present

https://github.com/LizardByte/Sunshine/issues/2120#issuecomment-2135015791
