### ISSUE TITLE
Let Windows/DS4Windows Program Detect DS4 Controller as an actual controller so we can switch Profiles, Currently its being undetected. 

### ISSUE THREAD

**Issue by Kristijan1001** [LizardByte/Sunshine#1819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

When using a DS4 Controller the Controller does not show up as that on Windows so its undetected by DS4 Windows

### Expected Behavior

To Detect the Controller.

### Host Operating System

Windows

### Operating System Version

Windows 11

### Architecture

64 bit

### Sunshine commit or version

0.21.0

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

2070 Super

### GPU Driver/Mesa Version

545.84

### Config

```Shell
/
```

### Relevant log output

```shell
/
```

**Comment by Kristijan1001** [comment]
Releated prolly.

https://ideas.moonlight-stream.org/posts/39/dualshock-4-passthrough

Also:

https://github.com/Ryochan7/DS4Windows/issues/3152

**Comment by ReenigneArcher** [comment]
We have no control over DS4Windows
