### ISSUE TITLE
The streaming color seems grayed out

### ISSUE THREAD

**Issue by laolarou726** [LizardByte/Sunshine#1826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

The streaming color is much dimmer and the saturation is lower than the native machine.

[sunshine.log](https://github.com/LizardByte/Sunshine/files/13271224/sunshine.log)

### Host Operating System

Windows

### Operating System Version

Windows 11 22H2

### Architecture

64 bit

### Sunshine commit or version

0.21.0

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

GeForce RTX 3080

### GPU Driver/Mesa Version

545.92

### Config

```Shell
fps = [10,30,60,90,120,144]
```

### Relevant log output

```shell
*See Describe the Bug*
```

**Comment by A-m-a-a-n** [comment]
Bumping. This is affecting my Steam Deck and iPad

**Comment by systox** [comment]
try disabling HDR on the host computer.

**Comment by laolarou726** [comment]
> try disabling HDR on the host computer.

I didn't turn on the HDR option in windows and moonlight

**Comment by systox** [comment]
> > try disabling HDR on the host computer.
> 
> I didn't turn on the HDR option in windows and moonlight

Sorry, that’s all I could think of.
