### ISSUE TITLE
Typo and mistake in installation docs

### ISSUE THREAD

**Issue by AppleMangoOrange** [LizardByte/Sunshine#1829]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

The installation docs for the [Flatpak installation](https://docs.lizardbyte.dev/projects/sunshine/en/latest/about/installation.html#flatpak-package) has a typo to be corrected and an addition to be made. Shown as follows:
OLD:
`flatpak run --command=additional-install.sh dev.lizardbyte.sunshine`
NEW
`flatpak run --command=additional-install.sh dev.lizardbyte.app.Sunshine`

Changes are the "app" part and the capitalisation of S in 'Sunshine'

### Host Operating System

other, n/a

### Operating System Version

N/A

### Architecture

other, n/a

### Sunshine commit or version

N/A

### Package

Linux - flatpak

### GPU Type

n/a

### GPU Model

N/A

### GPU Driver/Mesa Version

N/A

### Capture Method (Linux Only)

N/A

### Config

```Shell
N/A
```

### Apps

```json
N/A
```

### Relevant log output

```shell
N/A
```

**Comment by ReenigneArcher** [comment]
Our docs are correct for the package we publish to GitHub releases!

**Comment by AppleMangoOrange** [comment]
Thanks to [this post](https://discord.com/channels/804382334370578482/1118278441205256304) by Phantom0 on discord for pointing it out

**Comment by AppleMangoOrange** [comment]
It is to be expected that people would install software from flathub... Am I wrong?

**Comment by ReenigneArcher** [comment]
Until the two packages are in parity, the docs will refer to our version. https://github.com/flathub/dev.lizardbyte.app.Sunshine/issues/36
