### ISSUE TITLE
Windows Key being passed as Left Alt 

### ISSUE THREAD

**Issue by LanHikari22** [LizardByte/Sunshine#1839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

When I press the windows key, Moonlight seems to correctly distinguish it from Left Alt, but on Sunshine, both are received and interpreted as Left Alt.

I read on the documentation that this issue seems to be known with a Right Alt workaround, but I wanna know what the cause is:
https://docs.lizardbyte.dev/projects/sunshine/en/latest/about/advanced_usage.html#key-rightalt-to-key-win

Thanks,
Lan

### Additional Context

Issue also submitted at https://github.com/moonlight-stream/moonlight-qt/issues/1113

### Host Operating System

Linux

### Operating System Version

6.2.0-36-generic #37~22.04.1-Ubuntu

### Architecture

64 bit

### Sunshine commit or version

0.21.0

### Package

Linux - deb

### GPU Type

Nvidia

### GPU Model

Nvidia Titan RTX

### GPU Driver/Mesa Version

535.129.03

### Config

```Shell
Empty
```

### Relevant log output

```shell
Moonlight logs show it is passing the windows key:

For Windows key:
00:04:42 - SDL Info (0): SDL EVENT: SDL_KEYDOWN (timestamp=282381 windowid=2 state=pressed repeat=false scancode=227 keycode=1073742051 mod=5120)
00:04:42 - SDL Info (0): SDL EVENT: SDL_KEYUP (timestamp=282509 windowid=2 state=released repeat=false scancode=227 keycode=1073742051 mod=4096)

For Left Alt:
00:04:45 - SDL Info (0): SDL EVENT: SDL_KEYUP (timestamp=285013 windowid=2 state=released repeat=false scancode=226 keycode=1073742050 mod=4096)
00:04:45 - SDL Info (0): SDL EVENT: SDL_KEYDOWN (timestamp=285157 windowid=2 state=pressed repeat=false scancode=226 keycode=1073742050 mod=4352)
```

**Comment by thatsysadmin** [comment]
This feels like a stupid XNU platform oddity - I had an iOS client for a while while my Linux notebook was MIA, and I seem to remember that pressing CMD would behave as Super/Start (Was labeled Start as well on a Logitech K375s).

You might have to use custom keybindings for this - see https://docs.lizardbyte.dev/projects/sunshine/en/latest/about/advanced_usage.html
