### ISSUE TITLE
Ghost controller created when connecting to Sunshine 0.21 (or newer)

### ISSUE THREAD

**Issue by NanDSi** [LizardByte/Sunshine#1841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

After the update of Sunshine from 0.20 to 0.21, when connecting (or reconnecting) to Stream, Sunshine is creating an extra Virtual controller, which is not controllable or accessible to the player, being a dummy controller of sorts. Another controller is created, which captures the user controller, making the computer think that theres two controllers, which impact some games that only allows the first controller to move around.

After disconnecting, the dummy controller is still detected by windows (even with no clients connected).

My Client is an Moonlight-Android on S20 FE 5G, but i also tested on a A22 5G.

In attempts to fix the issue, i have tested:
1. Downgrading the Vigem Driver to 1.21.442
2. Limited Channels to 1 (in case it was some dead stream channel)
3. Tested two controllers (Gamesir X2 Pro and 8BitDo SN30 Pro)
4. Downgrading the Moonlight-Android to (12.0 and 11.0)
5. Used Portable and Installed version of Moonlight 0.21
6. Used latest nightly builds.
7. Using diferent devices to connect to Sunshine.
8. Tried to change AV1 config to "Not advertise for AV1 support" (since my GPU also dont support its encoding)
9. Tried to disable/enable Touchscreen Xbox Controller

Each of those have been throughly tested, on and off, over and over with no affecting into the issue. It will always happen sometime, maybe at first connection, maybe at 4 connection, and sometimes restarting Sunshine service fixes it, sometimes it doesnt help.

Theres a LOG from the last time this happened, which will be added in 'Relevant log output'

### Expected Behavior

the number of virtual controllers should match the number of physical controllers connected to the Client.

### Host Operating System

Windows

### Operating System Version

Windows 10 22H2 (19045.3570)

### Architecture

64 bit

### Sunshine commit or version

0.21

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

NVIDIA GeForce RTX 3060 Laptop GPU

### GPU Driver/Mesa Version

546.08

### Config

```Shell
nvenc_preset = 4
always_send_scancodes = disabled
address_family = both
channels = 8
resolutions = [
    352x240,
    480x360,
    858x480,
    1280x720,
    1920x1080,
    2560x1080,
    3440x1440,
    1920x1200,
    3840x2160,
    3840x1600,
    2400x1080
]
fps = [10,30,60,90,120,165]
av1_mode = 0
ping_timeout = 500
```

### Relevant log output

```shell
[2023:11:13:22:45:58]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2023:11:13:22:45:58]: Info: 
[2023:11:13:22:45:58]: Info: Found H.264 encoder: h264_nvenc [nvenc]
[2023:11:13:22:45:58]: Info: Found HEVC encoder: hevc_nvenc [nvenc]
[2023:11:13:22:45:58]: Info: Executing [Desktop]
[2023:11:13:22:45:58]: Info: nvprefs: No need to modify application profile settings
[2023:11:13:22:45:58]: Info: nvprefs: No need to modify global profile settings
[2023:11:13:22:45:58]: Info: CLIENT CONNECTED
[2023:11:13:22:45:58]: Warning: QOSAddSocketToFlow() failed: 1168
[2023:11:13:22:45:58]: Warning: QOSAddSocketToFlow() failed: 1168
[2023:11:13:22:45:58]: Info: 
Device Description : NVIDIA GeForce RTX 3060 Laptop GPU
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002560
Device Video Mem   : 6010 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8055 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1080
Offset             : 0x0
Virtual Desktop    : 2560x1080
[2023:11:13:22:45:58]: Info: Active GPU has HAGS disabled
[2023:11:13:22:45:58]: Info: Using realtime GPU priority
[2023:11:13:22:45:58]: Info: Desktop resolution [2560x1080]
[2023:11:13:22:45:58]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:11:13:22:45:58]: Info: Display refresh rate [120Hz]
[2023:11:13:22:45:58]: Info: Requested frame rate [120fps]
[2023:11:13:22:45:58]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 10
Red Primary        : [0.651367,0.332031]
Green Primary      : [0.306641,0.630859]
Blue Primary       : [0.150391,0.0595703]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.3037 nits
Max Luminance      : 301.849 nits
Max Full Luminance : 243.056 nits
[2023:11:13:22:45:58]: Info: SDR color coding [Rec. 709]
[2023:11:13:22:45:58]: Info: Color depth: 10-bit
[2023:11:13:22:45:58]: Info: Color range: [JPEG]
[2023:11:13:22:45:58]: Info: Capture format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:11:13:22:45:58]: Info: NvEnc: created encoder P4 10-bit two-pass rfi
[2023:11:13:22:46:00]: Info: Gamepad 0 will be Xbox 360 controller (default)
[2023:11:13:22:46:01]: Error: Couldn't add Gamepad to ViGEm connection [E0000007]
[2023:11:13:22:46:01]: Info: Gamepad 0 will be Xbox 360 controller (default)
```

**Comment by cgutman** [comment]
In the cases where you see the duplicate devices, does the virtual controller appear on the host PC pretty much immediately when you connect to the host or does it only happen once you've pressed a button on the client controller?

Does the issue still occur if you don't have any physical controllers connected and only use the virtual on-screen controller in Moonlight?

You mentioned trying a couple of Android devices, but have you tried a totally different client like iOS or PC/Mac?

Also if you could get a log of the issue with the log verbosity increased in Sunshine that would be interesting too. My guess is that controller arrival message from the client is coming in too early and causing the `Error: Couldn't add Gamepad to ViGEm connection [E0000007]` message.

**Comment by NanDSi** [comment]
> In the cases where you see the duplicate devices, does the virtual controller appear on the host PC pretty much immediately when you connect to the host or does it only happen once you've pressed a button on the client controller?
> 
> Does the issue still occur if you don't have any physical controllers connected and only use the virtual on-screen controller in Moonlight?
> 
> You mentioned trying a couple of Android devices, but have you tried a totally different client like iOS or PC/Mac?
> 
> Also if you could get a log of the issue with the log verbosity increased in Sunshine that would be interesting too. My guess is that controller arrival message from the client is coming in too early and causing the `Error: Couldn't add Gamepad to ViGEm connection [E0000007]` message.

1. It happened when i pressed the button on the Client

2. Yes, it happened with the virtual on-screen controller alone

3. Sadly, i had not tested using iOS or PC, but i had tested many android versions of the Moonlight.

4. I put the logs in verbose, however i was not able to trigger the problem right now (funny enough, when i want it to happen, it refuses to). I will comment whenever i get the logs for you!

OBS: I also noticed it never happened using Phone Gyro (which makes PC recognize as a "Wireless Controller"/PS Controller).

**Comment by cmschmidt15** [comment]
Had similar issues on a recent upgrade to 0.21.  Controller inputs had no response when streaming (mouse mode worked though). 
 I'm using an Xbox Series S controller connected directly to a Nvidia Shield via BT and also tried using an 8BitDo adapter attached to the Shield to use VirtualHere to a Win10 PC running a i7-9700k/RTX 3800.  Same issue with both connection methods.

Whenever I tried to start a Moonlight stream using Sunshine 0.21 through Nvidia Shield to Steam Big Picture for example, the Xbox controller would be seen but there was no input response in normal controller mode.  Going into mouse mode worked fine but I couldn't get any of the normal controller button presses to do anything.  

Reverted back to 0.20 fixed all issues here.  One thing I noticed on 0.20 is when I would start a game steam with the Xbox controller on/connected, I would hear the Windows sound for a USB connection and after a few seconds of delay, all inputs would work fine with little to no latency.  I never heard that USB connection noise on 0.21 and not sure what is happening there but just wanted to give a data point.

**Comment by arogan** [comment]
I have the same issue.  Server is win 11.  Client varies.  Windows to windows seems to happen less often.  Fire tv cube happens the most so android client.  When it does happen control panel controllers shows 9 controllers.  Uninstalling and re-installing ViGEmBus did not help.  It might have something to do with sleep?  I'm not sure but I don't turn off my server.  I usually sleep it.  Will do more testing to see if I can reproduce more reliably but as of right now it happens every couple of days.  Rebooting always fixes it for a while.  I might have to roll back to 0.20 as this issue is quite annoying.

**Comment by cgutman** [comment]
Please try this build from PR #1975 and see if it resolves the issue. You'll need to be signed into GitHub for the download link to work.

https://github.com/LizardByte/Sunshine/actions/runs/7392451839/artifacts/1144325332

**Comment by NanDSi** [comment]
> Please try this build from PR #1975 and see if it resolves the issue. You'll need to be signed into GitHub for the download link to work.
> 
> https://github.com/LizardByte/Sunshine/actions/runs/7392451839/artifacts/1144325332

From initial testing, im not having such issue. 
I will be testing for more time (keeping this build as my main Sunshine instalation) and report if i have any issue.

**Comment by arogan** [comment]
Tested and so far it seems fixed for me too.  I will also keep using this nightly build.  Thanks for the fix!

**Comment by leonfers** [comment]
Going to leave this to help the next person. This problem is back (I use moonlight on android and sunshine on windows) updated to the latest version of both apps, also download ViGeM bus through the troubleshooting page.
The main issue is Steam seeing 2 controllers when using moonlight on android.
The only solution I could find that worked was disabling the HID device generated alongside the Xbox Controller (Also teste all options on moonlight for forcing or not xbox360 drivers and so on),

Block Driver Reinstallation via Group Policy (Windows Pro/Enterprise)

Open gpedit.msc and navigate to Computer Configuration > Administrative Templates > System > Device Installation > Device Installation Restrictions. 
Enable the policy Prevent installation of devices that match any of these device IDs. 
Click Show and enter the Hardware ID of the device (found in Device Manager > Properties > Details > Hardware Ids).  This prevents Windows from installing the driver, keeping the device disabled. 

Then disabling the HID device on device manager. 

This should keep the second controller from showing up
You will also need to enable steam input for Xbox or generic controllers on steam.
