### ISSUE TITLE
Touch input registers mouse key down before movement.

### ISSUE THREAD

**Issue by rutinoscorbin-abuser** [LizardByte/Sunshine#1854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

hey, i have a problem with streaming my pc via sunshine to moonlight on android
the "touch controls" seem to register the click a bit before it moves the cursor
ive noticed it when i wanted to stream the sims 4 to my phone
and its unplayable unless i use rewasd to map my controller especially for it
cant really move the camera because the left button is clicked way before the cursor has moved

### Expected Behavior

Dragging camera in sims without an issue.

### Additional Context

Video of the bug: 
https://streamable.com/13tvfb

Tried both nightly and stable releases. Honestly have no idea if its moonlights fault or sunshine's

### Host Operating System

Windows

### Operating System Version

10 21H2

### Architecture

64 bit

### Sunshine commit or version

Version 0.21.0.29a1b1539fb2e0e82d02e521954b163c6d9d55d1

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

Intel UHD 630 / GTX 1650 mobile

### GPU Driver/Mesa Version

537.42

### Config

```Shell
sunshine_name = chwdp
encoder = nvenc
nv_tune = lossless
resolutions = [
    352x240,
    480x360,
    858x480,
    1280x720,
    1920x1080,
    2560x1080,
    3440x1440,
    1920x1200,
    3840x2160,
    3840x1600,
    2400x1080,
    1600x720
]
```

**Comment by OlegAckbar** [comment]
I can confirm it on Plasma Wayland
