### ISSUE TITLE
Mousewheel or Middle mouse btn doesn't work in some games

### ISSUE THREAD

**Issue by cardil** [LizardByte/Sunshine#1873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

In some games, the mouse wheel doesn't work (in my case: Witcher 3, Black Mesa, Fallout 3). In some of those, the middle mouse button also doesn't work (Witcher 3). The Left and Right buttons work as expected.

Also, in other games, the mouse wheel works as expected. I've tested: Age of Wonders 3, Cities Skylines, Cyberpunk 2077 (works although only when scrolling v. fast), Master of Orion, Two Point Hospital, War For The Overworld.

Evidence:
- https://youtu.be/mDSpNM0RsVE - [Wither 3](https://steamdb.info/sub/124923/). Mouse scroll and MMB doesn't work at all. The video shows a console, on the client, showing inputs that don't affect the game (Witcher should shoot the crossbow, and menus should react to scroll)
- https://youtu.be/O6ozGoWlFhQ - [Fallout 3](https://steamdb.info/app/22370/). The mouse scrolling seems to be delivered in an endless loop, and extremely fast, making the game unplayable.
- https://youtu.be/HRCoiPH5Zr4 - [Black Mesa](https://steamdb.info/app/362890/). The mouse scroll is extremely fast, making the weapon switching very hard.

### Expected Behavior

The mouse scroll and the middle mouse button should work in every game.

### Additional Context

Uninstalling the Sunshine, and enabling streaming via GeForce Experience, resolves the described issues in all affected games.

The issue doesn't affect the desktop or web browsers when accessed via Sunshine.

### Host Operating System

Windows

### Operating System Version

Windows 10 Pro (22H2, build 19045.3693)

### Architecture

64 bit

### Sunshine commit or version

0.21.0.336062d467d5f48ba56d05a523c212f791421108

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

GeForce GTX 1060 6GB

### GPU Driver/Mesa Version

546.17

### Config

```Shell
min_log_level = 2
back_button_timeout = 2000
fps = [10,30,60]
nvenc_preset = 2
resolutions = [
    352x240,
    480x360,
    858x480,
    1280x720,
    1920x1080
]
```

### Apps

```json
{
    "env": {
        "PATH": "$(PATH);$(ProgramFiles(x86))\\Steam"
    },
    "apps": [
        {
            "name": "Desktop",
            "image-path": "desktop.png"
        },
        {
            "name": "Steam",
            "detached": [
                "steam steam:\/\/open\/bigpicture"
            ],
            "image-path": "steam.png",
            "exclude-global-prep-cmd": "false",
            "elevated": "false",
            "auto-detach": "true"
        },
        {
            "name": "Playnite",
            "output": "",
            "cmd": "D:\/programy\/Playnite\/Playnite.FullscreenApp.exe --startfullscreen --hidesplashscreen",
            "exclude-global-prep-cmd": "false",
            "elevated": "false",
            "auto-detach": "true",
            "image-path": "playnite.png"
        }
    ]
}
```

### Relevant log output

Nothing relevant found in the log output.

Attaching full for for completness: https://gist.github.com/cardil/6ab7d5466e57d1982803108441877853

**Comment by Bobbar** [comment]
Do you have a mouse physically plugged into the host?  I had the same problems with Witcher and solved it by connecting a mouse to the host.

**Comment by cardil** [comment]
> @Bobbar Do you have a mouse physically plugged into the host? I had the same problems with Witcher and solved it by connecting a mouse to the host.

No mouse at the host. I'll definitely try this walk-around...

**Comment by cardil** [comment]
I did some further debugging, and I saw some strange behavior. When the mouse scrolling, moonlight/sunshine sends multiple scroll packets (even for minimal mouse scroll) - 5 to be exact:

```
[2023:12:02:22:19:55]: Debug: --begin mouse scroll packet--
scrollAmt1 [-60]
--end mouse scroll packet--
[2023:12:02:22:19:55]: Debug: --begin mouse scroll packet--
scrollAmt1 [-15]
--end mouse scroll packet--
[2023:12:02:22:19:55]: Debug: --begin mouse scroll packet--
scrollAmt1 [-15]
--end mouse scroll packet--
[2023:12:02:22:19:55]: Debug: --begin mouse scroll packet--
scrollAmt1 [-15]
--end mouse scroll packet--
[2023:12:02:22:19:55]: Debug: --begin mouse scroll packet--
scrollAmt1 [-15]
--end mouse scroll packet--
```

In contrast, when the LMM is pressed, only one packet is sent (here is a long click and release example):

```
[2023:12:02:22:19:49]: Debug: --begin mouse button packet--
action [00000008]
button [01]
--end mouse button packet--
[2023:12:02:22:19:52]: Debug: --begin mouse button packet--
action [00000009]
button [01]
--end mouse button packet--
```

This could easily explain bad behavior in Black Mesa game, maybe others too.

**Comment by cgutman** [comment]
@cardil What's your client?

Moonlight will send high resolution scroll events to Sunshine if they are provided by the client OS and the mouse hardware, so you can see multiple scroll events for one "click" of the scroll wheel. A single click of the scroll wheel is defined as 120 units (`WHEEL_DELTA`), so the high resolution scroll events you note there all add up to a single click of the wheel, as expected.

Some applications (particularly old ones) may not correctly handle high resolution scroll events and incorrectly assume that they should scroll for every event instead of accumulating 120 units before scrolling. I wouldn't expect the behavior of these apps with Sunshine to be any different from physically connecting a mouse with a high resolution scroll wheel directly to the host though.

**Comment by ottelo9** [comment]
I have big problems with my mouse wheel in the game Snowrunner with Moonlight QT (5.0.1 Win10) + Sunshine (v0.21.0). I have no connected controllers (host + client) and disabled everything controller related inside moonlight and sunshine settings. 

I start the Stream and start Snowrunner. I can play for few minutes and zoom in/out the ingame map without problems. After few minutes the zoom (or the mouse wheel) is not working properly anymore. I can only zoom completly in or out, no Intermediate steps. If I slowly scroll my mouse wheel nothings happens.

Then I tried the nightly Sunshine build (last week Feb 2024) and disabled the high res scrolling. But with no success and the streams starts hanging/lagging, too. So I went back to Nvidia Gamestream, because with it I have no such problems.

**Comment by cardil** [comment]
The #1960 resolved my issue with the Black Mesa game (disabling the high-resolution scroll events).

It didn't fix the issues with Fallout 3 or Wither 3.

> _**Seculation:** Maybe the issues are related to how the virtual mouse drivers act?!_

**Comment by xz-dev** [comment]
Same in Rainbow Six, like Fallout 3
When you scroll the mouse wheel in one direction, it will continuously scroll in that direction indefinitely. If you scroll in the opposite direction, it will then continuously scroll in the new direction without stopping. This issue persists until you either exit the current game and restart it, or toggle the "Native Mouse and Keyboard Support" option in Rainbow Six (X) settings - enabling this option will disable mouse functionality, but disabling it afterwards will stop the mouse wheel from continuously scrolling.

**Comment by xz-dev** [comment]
> Do you have a mouse physically plugged into the host? I had the same problems with Witcher and solved it by connecting a mouse to the host.

When I plugin a physical mouse(no need to use it), bug fixed

**Comment by xz-dev** [comment]
More deep research:

If not enable [raw input](https://learn.microsoft.com/en-us/windows/win32/inputdev/about-raw-input) in game, Windows RDP also will got same bug.

If enable raw input in game, and then use Windows RDP to login host PC and open the game.

Then disconnect RDP, open moonlight to connect the host PC.

All working fine. no mouse scrolling forever bug.

So the key is raw input, and how can we let sunshine support raw input like RDP.
