### ISSUE TITLE
Since 0.21 time to initialize connection is doubled. 

### ISSUE THREAD

**Issue by Kobain-Seo** [LizardByte/Sunshine#1892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I measured time to initialize connection by versions.

By updates, it increases continuously. Especially 0.21 takes double comparing to 0.19. I don't know what causes these delays. 

0.19 - 3 secs
0.20 - 5 secs
0.21 - 6.5 secs

Host is NVIDIA 3060 and HEVC, FHD, 144fps. 

### Host Operating System

Windows

### Operating System Version

Windows 10 22H2

### Architecture

64 bit

### Sunshine commit or version

0.21

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

Geforce RTX 3060

### GPU Driver/Mesa Version

546.29

### Config

```Shell
hevc_mode = 3
fps = [10,30,60,90,120,144]
```

### Relevant log output

```shell
Not really.
```

**Comment by ReenigneArcher** [comment]
In v0.20.0 we started probing encoders before each stream instead of just the start of sunshine.

New encoders were added in v0.21.0.

You can speed it up by forcing the encoder you want to use.

**Comment by Kobain-Seo** [comment]
> In v0.20.0 we started probing encoders before each stream instead of just the start of sunshine.
> 
> New encoders were added in v0.21.0.
> 
> You can speed it up by forcing the encoder you want to use.

How can i force the encoder? I set it up via web management but no difference.

**Comment by ReenigneArcher** [comment]
Set the encoder in the web ui. https://docs.lizardbyte.dev/projects/sunshine/en/latest/about/advanced_usage.html#encoder

Then save, and restart Sunshine.

**Comment by Kobain-Seo** [comment]
> Set the encoder in the web ui. https://docs.lizardbyte.dev/projects/sunshine/en/latest/about/advanced_usage.html#encoder
> 
> Then save, and restart Sunshine.



config is below : 

fps = [10,30,60,90,120,144]
hevc_mode = 3
encoder = nvenc

----------------------

No difference at all. I think forcing encoder is not the key.

**Comment by Kobain-Seo** [comment]
Any other ways to force encoder or skip probing encoders?
