### ISSUE TITLE
[Nix] Include a package-lock.json in the repository

### ISSUE THREAD

**Issue by arduano** [LizardByte/Sunshine#1900]
Please consider taking the `package-lock.json` file out of gitignore. I understand that the package count is small enough where it doesn't really matter for most cases, but it's still generally standard practice to include it, and it will remove the need for Nix to include their own:
https://github.com/NixOS/nixpkgs/blob/592047fc9e4f7b74a4dc85d1b9f5243dfe4899e3/pkgs/servers/sunshine/default.nix#L65

The idea behind Nix is to have reproducible builds, so a package-lock is required to have a consistent build each time, and it's impossible to overwrite that without disabling sandboxing. So currently, Nix devs need to include their own package-lock for this project.

**Comment by ReenigneArcher** [comment]
At this time, I don't plan on including that. We hard pin our dependencies in the `package.json`, and I don't see it being value added to track dependencies of dependencies.

**Comment by ReenigneArcher** [comment]
Added in https://github.com/LizardByte/Sunshine/pull/5083
