### ISSUE TITLE
GPU fails to downclock

### ISSUE THREAD

**Issue by trudnorx** [LizardByte/Sunshine#1908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

The GPU Sunshine is running on fails to downclock sufficiently while a client is connected to the stream. It becomes energy inefficient, and causes much more heat and power usage than necessary. This is even when GPU usage (including VID usage) by the stream is extremely low so low clocks would be able to perform just fine. You can't just relax and leave the stream on in the background because of the reasons I mentioned, plus the fan staying on at a high setting as a consequence.

I am not 100% sure what causes it, but I hypothesize it's related to the feature implemented by #1308. The pull request noted that this feature intentionally keeps the clocks high. While it's understandable that some users prefer this feature because of the claimed latency improvements, others prefer for the GPU to be able to downclock as much as possible.

I fail to see any option to toggle it on/off. It should be made an option. And given these issues, it probably shouldn't be the default.

### Host Operating System

Windows

### Operating System Version

any

### Architecture

64 bit

### Sunshine commit or version

Latest

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

-

### GPU Driver/Mesa Version

-

### Config

```Shell
-
```

### Relevant log output

```shell
-
```

**Comment by ReenigneArcher** [comment]
I'll accept a PR to make this configurable if anyone wants to work on it.

**Comment by cgutman** [comment]
#1798 makes it configurable. I can address the comments there if @ns6089 is busy.

**Comment by ReenigneArcher** [comment]
@cgutman that's fine with me. This issue has come up more than a few times.

**Comment by SlimJim192** [comment]
Hi there,

I've recently moved over from windows to Linux, and notes that the clock speed option is not available.

Is it not possible on the Linux client currently?

Cheers

**Comment by ReenigneArcher** [comment]
It's Windows only.
