### ISSUE TITLE
Commands are unavailable, when running Sunshine (portable) from Task Scheduler

### ISSUE THREAD

**Issue by mostm** [LizardByte/Sunshine#1931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

When running Sunshine as a Scheduled Task, prep commands do not work and following error messages appear:
```
Error: Failed to launch process: 5
Error: Couldn't run [C:\sample.exe]: System: Invalid argument
```
When running Sunshine not as a Scheduled Task, but via simple "Right-Click -> Run as Administrator", bug does not appear, and application runs normally.

### Expected Behavior

Prep commands should execute as normal.

### Additional Context

I've tried a lot of methods to start Sunshine via Task Scheduler, using cmd.exe as a forwarder, or basic scripts on python and vbs.
No matter what I tried, the result is always the same, even though a Python script can launch a command, but sunshine somehow is unable to.

I've pinned it down to CreateProcessW function - https://github.com/LizardByte/Sunshine/blob/6b7b5996ccd040375b62d930e064abddcc533a72/src/platform/windows/misc.cpp#L654-L663

My first though was that maybe the environment was somehow different between the 2 launch methods, but it isn't.
The command and start_dir seem to be the same, so I'm unsure where issue lies.

### Host Operating System

Windows

### Operating System Version

10 22H2 (19045.3803)

### Architecture

64 bit

### Sunshine commit or version

6b7b5996ccd040375b62d930e064abddcc533a72

### Package

Windows - portable

### GPU Type

Nvidia

### GPU Model

GeForce RTX 3080

### GPU Driver/Mesa Version

537.38

### Config

```Shell
min_log_level = 0
```

### Apps

```json
{
    "env": {
        "PATH": "$(PATH);$(ProgramFiles(x86))\\Steam"
    },
    "apps": [
        {
            "name": "Desktop",
            "image-path": "desktop.png",
            "exclude-global-prep-cmd": "false",
            "elevated": "false",
            "auto-detach": "true",
            "prep-cmd": [
                {
                    "do": "C:\\sample.exe",
                    "undo": "",
                    "elevated": "false"
                }
            ]
        },
        {
            "name": "Steam Big Picture",
            "detached": [
                "steam steam:\/\/open\/bigpicture"
            ],
            "image-path": "steam.png"
        }
    ]
}
```

### Relevant log output

```shell
[2023:12:24:07:55:40]: Debug: Parsed executable [C:\sample.exe] from command [C:\sample.exe]
[2023:12:24:07:55:40]: Debug: Resolved executable [C:\sample.exe] to path ["C:\sample.exe"]
[2023:12:24:07:55:40]: Info: Executing Do Cmd: [C:\sample.exe]
[2023:12:24:07:55:40]: Error: Failed to launch process: 5
[2023:12:24:07:55:40]: Error: Couldn't run [C:\sample.exe]: System: Invalid argument
```

**Comment by ReenigneArcher** [comment]
Can you export the scheduled task and share the xml here?

**Comment by ReenigneArcher** [comment]
Closing due to no response.
