### ISSUE TITLE
v0.14.0 windows package issues

### ISSUE THREAD

**Issue by sitiom** [LizardByte/Sunshine#197]
### Describe the Bug

In https://github.com/SunshineStream/Sunshine/releases/tag/v0.14.0, `install-service.bat` and `uninstall-service.bat` is removed. 

### Expected Behavior

`install-service.bat` and `uninstall-service.bat` should exist

Windows Installer should automatically install the `sunshinevc service`

### Additional Context

https://github.com/SunshineStream/Sunshine/discussions/196

### Sunshine Host Operating System and Version

Windows 11

### Architecture

64 bit

### Sunshine Version

0.14.0

### GPU Type

Nvidia

### GPU Model

GeForce RTX 2070 SUPER

### GPU Driver/Mesa Version

512.95

**Comment by sitiom** [comment]
#198 is a feature request because it is something of a new feature than missing? Or did you really intend to make the Windows Installer automatically set up `sunshinevc`?

**Comment by ReenigneArcher** [comment]
Update tools component to include these: https://github.com/SunshineStream/Sunshine/blob/master/CMakeLists.txt#L466-L469

**Comment by ReenigneArcher** [comment]
This: https://cmake.org/cmake/help/latest/cpack_gen/nsis.html#variable:CPACK_NSIS_EXTRA_INSTALL_COMMANDS

might allow to install the service automatically. Not sure if it can be used on a single component, so may just need to first check if file exists.
