### ISSUE TITLE
can't get sunshine-git on manjaro arch

### ISSUE THREAD

**Issue by mrroot912** [LizardByte/Sunshine#1996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Cloning into 'enet'...
done.
==> Starting prepare()...
fatal: pathspec 'third-party/ffmpeg-windows-x86_64' did not match any files
==> ERROR: A failure occurred in prepare().
    Aborting...

getting this error while installing with Yay or pamac in manajaro

### Host Operating System

Linux

### Operating System Version

Manjaro Arch Linux

### Architecture

64 bit

### Sunshine commit or version

0.21

### Package

Linux - AUR (Third Party)

### GPU Type

Nvidia

### GPU Model

RTX 3080

### GPU Driver/Mesa Version

545

### Config

```Shell
can't install
```

### Relevant log output

```shell
can't install
```

**Comment by ReenigneArcher** [comment]
The maintainers need to update their build spec.

**Comment by ReenigneArcher** [comment]
We also publish a PKGBUILD to github releases, so very little value in using `sunshine-git`.

nightly version
```bash
wget https://github.com/LizardByte/Sunshine/releases/nightly-dev/download/PKGBUILD
makepkg -fi
```
