### ISSUE TITLE
Installation Failed On M2 MacOS

### ISSUE THREAD

**Issue by MidnightSong** [LizardByte/Sunshine#2015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I followed the steps in the official documentation to install it, but it failed. I tried uninstalling MacPorts and reinstalling it, but it still failed Here is the error log I saw  ( main.log details in Relevant log output )

--->  Fetching archive for glib2
--->  Attempting to fetch glib2-2.76.3_0+x11.darwin_23.arm64.tbz2 from https://pek.cn.packages.macports.org/macports/packages/glib2
--->  Attempting to fetch glib2-2.76.3_0+x11.darwin_23.arm64.tbz2 from https://kmq.jp.packages.macports.org/glib2
--->  Attempting to fetch glib2-2.76.3_0+x11.darwin_23.arm64.tbz2 from https://nue.de.packages.macports.org/glib2
--->  Configuring glib2
Error: Failed to configure glib2: consult /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_glib2/glib2/work/build/meson-logs/meson-log.txt
Error: Failed to configure glib2: configure failure: command execution failed
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_glib2/glib2/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug.
Error: Processing of port sunshine failed

  

### Host Operating System

macOS

### Operating System Version

14.2.1

### Architecture

64 bit

### Sunshine commit or version

last version

### Package

macOS - Portfile

### GPU Type

n/a

### GPU Model

m2

### GPU Driver/Mesa Version

m2

### Config

```Shell
I don't have it
```

### Apps

```json
I don't have it
```

### Relevant log output

```shell
Build started at 2024-01-12T20:53:08.952689
Main binary: /opt/local/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11
Build Options: -Ddefault_library=both -Dwarning_level=0 -Ddtrace=false -Dappinfo_backend=generic -Dprefix=/opt/local
Python system: Darwin
The Meson build system
Version: 1.1.1
Source dir: /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_glib2/glib2/work/glib-2.76.3
Build dir: /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_glib2/glib2/work/build
Build type: native build
Project name: glib
Project version: 2.76.3
-----
Detecting compiler via: /usr/bin/clang --version
compiler returned <Popen: returncode: 0 args: ['/usr/bin/clang', '--version']>
compiler stdout:
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: arm64-apple-darwin23.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

compiler stderr:
Running command: /usr/bin/clang -E -dM -
-----
Detecting linker via: /usr/bin/clang -Wl,--version -L/opt/local/lib -Wl,-headerpad_max_install_names -lresolv -bind_at_load -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -arch arm64 -pipe -Os -fstrict-aliasing -Wno-deprecated-declarations -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -arch arm64 -I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk
linker returned <Popen: returncode: 1 args: ['/usr/bin/clang', '-Wl,--version', '-L/opt/loca...>
linker stdout:

linker stderr:
ld: unknown options: --version
clang: error: linker command failed with exit code 1 (use -v to see invocation)

-----
Detecting Apple linker via: /usr/bin/clang -Wl,-v -L/opt/local/lib -Wl,-headerpad_max_install_names -lresolv -bind_at_load -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -arch arm64 -pipe -Os -fstrict-aliasing -Wno-deprecated-declarations -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -arch arm64 -I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk
linker stdout:

linker stderr:
ld: warning: -bind_at_load is deprecated on macOS
@(#)PROGRAM:ld  PROJECT:dyld-1022.1
BUILD 13:21:42 Nov 10 2023
configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h
will use ld-classic for: armv6 armv7 armv7s arm64_32 i386 armv6m armv7k armv7m armv7em
LTO support using: LLVM version 15.0.0 (static support for 29, runtime is 29)
TAPI support using: Apple TAPI version 15.0.0 (tapi-1500.0.12.8)
Library search paths:
        /opt/local/lib
tderr: ld: unknown options: --version
clang: error: linker command failed with exit code 1    /opt/local/lib
Framework search paths:
ld: Undefined symbols:
  _main, referenced from:
      <initial-undefines>
clang: error: linker command failed with exit code 1 (use -v to see invocation)


meson.build:1:0: ERROR: Unable to detect linker for compiler `/usr/bin/clang -Wl,--version -L/opt/local/lib -Wl,-headerpad_max_install_names -lresolv -bind_at_load -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -arch arm64 -pipe -Os -fstrict-aliasing -Wno-deprecated-declarations -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -arch arm64 -I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk`
stdout:
stderr: ld: unknown options: --version
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by ReenigneArcher** [comment]
This is an issue with glib2 port. It may be solved by now.

What version of xcode are you using? Upgrading meson to 1.2.0 may solve it.

I'd probably avoid using any beta software as build tools.

Here are some references for you.

https://trac.macports.org/ticket/67887#no1
https://github.com/mesonbuild/meson/issues/11958

Anyway, since this is not an issue with Sunshine, I'll be closing this.
