### ISSUE TITLE
Docker startup failure

### ISSUE THREAD

**Issue by HarryAnkers** [LizardByte/Sunshine#2021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I am trying to setup sunshine with docker (docker-desktop in particular). Though whenever I launch it no matter what I do it ends with a crash loop:
2024-01-14 19:48:34 /usr/bin/sunshine: error while loading shared libraries: libminiupnpc.so.17: cannot open shared object file: No such file or directory
I have tried installing various packages on my local machine and nothing has resolved it.

Please help

### Expected Behavior

I should be able to start the docker pod

### Additional Context

docker compose:
version: '3'
name: "sunshine"
services:
  sunshine:
    image: lizardbyte/sunshine:nightly-ubuntu-22.04
    container_name: sunshine
    restart: unless-stopped
    volumes:
      - /home/username/Services/Sunshine/config:/config
    environment:
      - TZ=Europe/London
    ports:
      - "47984-47990:47984-47990/tcp"
      - "48010:48010"
      - "47998-48000:47998-48000/udp"

### Host Operating System

Docker

### Operating System Version

Pop!_OS 22.04 LTS

### Architecture

64 bit

### Sunshine commit or version

525d77d41d31134847aec06e8de511af9f3e577cc17522da64e80df11b3cbe62

### Package

Linux - Docker

### GPU Type

Nvidia

### GPU Model

3060 ti founders

### GPU Driver/Mesa Version

545.29.06

### Config

```Shell
nothing yet. Waiting for startup
```

### Relevant log output

```shell
none other than one above attached
```

**Comment by ReenigneArcher** [comment]
> I have tried installing various packages on my local machine

That won't resolve it unless you volume map the installed files into your container. I have a fix in #2022 though. It will take a little while to make it up to the container registries.
