### ISSUE TITLE
DS5 is not recognized

### ISSUE THREAD

**Issue by ck2004ck** [LizardByte/Sunshine#2041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I chose the DS5 controller in Gamepades, but Moonlight only had the controller test page that recognized my controller, and Steam and Win11 didn't have it

Finally, I also installed the vigembus driver and it still couldn't be recognized, but after replacing it with 360, it was successfully recognized

### Host Operating System

Windows

### Operating System Version

win11

### Architecture

64 bit

### Sunshine commit or version

0.21.0

### Package

Windows - installer

### GPU Type

AMD

### GPU Model

3060

### GPU Driver/Mesa Version

Latest

### Config

```Shell
key_rightalt_to_key_win = enabled
external_ip = 49.77.65.2
fps = [10,30,60,90,120,165]
resolutions = [
    352x240,
    480x360,
    858x480,
    1280x720,
    1920x1080,
    2560x1080,
    3440x1440,
    1920x1200,
    3840x2160,
    3840x1600,
    2560x1440
]
upnp = enabled
origin_web_ui_allowed = wan
channels = 4
address_family = both
hevc_mode = 1
sunshine_name = 技嘉
gamepad = ds4
```

### Relevant log output

```shell
.
```

**Comment by ReenigneArcher** [comment]
Provide logs, or this will be closed.
