### ISSUE TITLE
[Windows] [Documentation] Unclear That Service Runs HTTPS instead of HTTP

### ISSUE THREAD

**Issue by erikvanderwerf** [LizardByte/Sunshine#2072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

The documentation states "The Sunshine user interface will be available on port 47990 by default.", but it does not indicate that the service is only listening on on HTTPS via a self-signed certificate. This is confusing to me (and I almost filed a different bug report that the service was not started) because I had only attempted to connect via HTTP, since that is the default behavior in Chrome when I type "localhost:47790" into my navigation bar.

I only saw https in the `sunshine.log` as a clue at the last minute before scrapping a previous bug report.

### Expected Behavior

I expect that the documentation indicates the service is only listening on HTTPS, or that the default behavior is to listen on HTTP and allow the user to configure HTTPS on their own time. As a localhost service with no configured certificate I did not even think about HTTPS.

### Additional Context

This is a compounding bug to #2071 which made it very hard to diagnose if the service was even operating at all. It is not directly relevant to this report, but that is why I filed two reports at the same time.

Chrome is also not very helpful here.
![image](https://github.com/LizardByte/Sunshine/assets/4553730/ccade64b-3107-4363-bbed-f5a3e28a7d47)

### Host Operating System

Windows

### Operating System Version

Windows 11 10.0.22621

### Architecture

64 bit

### Sunshine commit or version

0.21.0

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

RTX 3070

### GPU Driver/Mesa Version

546.01

### Config

```Shell
<empty file>
```

### Relevant log output

```shell
[2024:01:28:12:09:01]: Info: Open the Web UI to set your new username and password and getting started
[2024:01:28:12:09:01]: Info: File C:\Program Files\Sunshine\config\sunshine_state.json doesn't exist
[2024:01:28:12:09:01]: Info: Configuration UI available at [https://localhost:47990]
[2024:01:28:12:09:02]: Info: Registered Sunshine mDNS service
```

**Comment by ReenigneArcher** [comment]
It's not really necessary to make it clear. The tray icon will open the UI, as well as the start menu icon.

P.S. please do not open support requests as bug reports.
