### ISSUE TITLE
I encountered a problem where the ViGEm gamepad  will be disabled if  PC is connected to a controller receiver.

### ISSUE THREAD

**Issue by Envy271** [LizardByte/Sunshine#2093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I encountered a problem where the ViGEm gamepad  will be disabled if  PC is connected to a controller receiver.

### Host Operating System

Windows

### Operating System Version

10

### Architecture

64 bit

### Sunshine commit or version

0.21

### Package

Windows - portable

### GPU Type

AMD

### GPU Model

r9 fury

### GPU Driver/Mesa Version

27.20.20913.2000

### Config

```Shell
mouse = disabled
always_send_scancodes = disabled
keyboard = disabled
av1_mode = 1
install_steam_audio_drivers = disabled
encoder = amdvce
hevc_mode = 1
min_log_level = 2
origin_web_ui_allowed = pc
gamepad = x360
```

### Relevant log output

```shell
sorry,No relevant log information exists.
```

**Comment by ReenigneArcher** [comment]
We don't maintain ViGEmBus.
