### ISSUE TITLE
Error Installing RPM 0.14.0 on Fedora Silverblue 36 - '/usr/local' unsupported

### ISSUE THREAD

**Issue by dannymate** [LizardByte/Sunshine#210]
### Describe the Bug

When trying to install the rpm for sunshine 0.14.0 on Fedora Silverblue 36 (rpm-ostree install <sunshine.rpm>) I get the error:
```
error: Importing package 'sunshinestream': Analyzing /usr/local: Unsupported path; see https://github.com/projectatomic/rpm-ostree/issues/233
```

### Expected Behavior

RPM should be layered onto my install.

### Additional Context

As Silverblue is an immutable OS it currently doesn't support installing into the /usr/local. You can see the issue here: https://github.com/projectatomic/rpm-ostree/issues/233.

### Sunshine Host Operating System and Version

Fedora Silverblue 36

### Architecture

64 bit

### Sunshine Version

0.14.0

### GPU Type

AMD iGPU + nVIDIA dGPU

### GPU Model

Nvidia RTX 3050

### GPU Driver/Mesa Version

510.68.02

### Capture Method (Linux Only)

Pipewire

**Comment by ReenigneArcher** [comment]
You can set the destination paths yourself if you build yourself.

**Comment by jeremyvisser** [comment]
In fairness, it is pretty unusual for an RPM to install to `/usr/local`, so I think the implied proposal to install to /usr instead is reasonable. Would you accept a pull request that changes the prefix to `/usr`?

Another strange RPM behaviour is the postinstall logic in [`src_assets/linux/misc/postinst`](https://github.com/SunshineStream/Sunshine/blob/master/src_assets/linux/misc/postinst) which backs up and restores the config file. RPM has a built-in flag for this: `%config(noreplace)` ([doc](https://www.cl.cam.ac.uk/~jw35/docs/rpm_config.html)). But admittedly CPack makes doing this a bit harder than RPM itself ([`CPACK_RPM_USER_FILELIST`](https://cmake.org/cmake/help/latest/cpack_gen/rpm.html#variable:CPACK_RPM_USER_FILELIST) shenanigans).

**Comment by ReenigneArcher** [comment]
I will be changing the paths to `/usr/share/sunshine` based on discussion in another PR.

I don't know if cpack has an option for that, but we're sticking with cpack for the packages it supports as it greatly simplifies our packaging process.

**Comment by ReenigneArcher** [comment]
Working on updates to the paths in #330 . Will `/usr/share/sunshine/` be acceptable for RPM?
