### ISSUE TITLE
No automated Nightly builds

### ISSUE THREAD

**Issue by Billybishop** [LizardByte/Sunshine#2100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I'm having trouble locating automated builds of the nightly branch.

Is it absolutely necessary to fork or locally build nightly just get the nightly builds?  I would only expect someone to fork or locally build *my* prerelease projects if they're intending on making their own changes or contributions, otherwise a central automated build process is much more preferred - if even to avoid having people asking the kind of questions I just did.

I figured I would open an issue to get some public clarification about this, as I'm probably not the only one looking at the nightly branch and scratching my head.

I've been using the public October release version (v0.21.0), but this is quite a few revisions behind the nightly branch and frankly, in my eyes and in my opinion, it seems that the nightly branch has functionally replaced the main branch in a sense due to how stale release is.

Please direct or correct me if I'm wrong, but is there a purposeful reason why there *isn't* a central, publicly accessible automated build process for the nightly branch?  

### Expected Behavior

Central and publicly accessible nightly builds - or an optional patron subscription that allows patrons to receive them automatically.

### Host Operating System

Windows

### Operating System Version

n/a

### Architecture

64 bit

### Sunshine commit or version

latest nightly

### Package

n/a

### GPU Type

n/a

### GPU Model

n/a

### GPU Driver/Mesa Version

n/a

### Config

```Shell
n/a
```

### Relevant log output

```shell
n/a
```

**Comment by Billybishop** [comment]
I was able to answer my own question, the automated nightly builds are buried in the Jobs for each nightly commit, you'll need to navigate to the uploaded artifacts section.

The way this should *really* work, is fully successful nightly builds in the CI jobs should be automatically posted with a nightly tag to the release section of the github repo.

**Comment by ReenigneArcher** [comment]
The link to nightly builds is on our website. It's just like any other release. https://app.lizardbyte.dev/Sunshine

**Comment by Billybishop** [comment]
> The link to nightly builds is on our website. It's just like any other release. https://app.lizardbyte.dev/Sunshine

Thanks for the link, I had no idea there was a link for nightly release there.

I can see now that it's in the tags.  I had to go to the second page of the releases to find the nightly tag. 
https://github.com/LizardByte/Sunshine/tags?after=v0.17.0
