### ISSUE TITLE
Build fails with a javascript error

### ISSUE THREAD

**Issue by efifogel** [LizardByte/Sunshine#2117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

The build fails with the following error:

file:///home/efif/trees/xanadu/Sunshine/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word

### Expected Behavior

Well, I don't expect to get a compilation error.
It's the first time I'm trying to build Sunshine, so its' possible that I miss something.
However, the instructions are clear and I'm trying the minimal build; see below.

### Additional Context

Trying to build from sources:
> git clone https://github.com/lizardbyte/sunshine.git --recurse-submodules
> cd sunshine
> npm install
> mkdir build && cd build
> cmake .. # (ended successfully!)
> make

### Host Operating System

Linux

### Operating System Version

Ubuntu 22.04.3 LTS

### Architecture

64 bit

### Sunshine commit or version

Latest (Feb 8, 2024)

### Package

other (self built)

### GPU Type

Nvidia

### GPU Model

GeForce GTX 750 Ti

### GPU Driver/Mesa Version

nvidia 470.223.02 (5.15.0-94-generic)

### Config

```Shell
~
```

### Apps

```json
~
```

### Relevant log output

```shell
file:///home/efif/trees/xanadu/Sunshine/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
```

**Comment by ReenigneArcher** [comment]
It's cause you have `nightly` checked out, but are using the instructions from stable.

Either:

1. Checkout `master` branch and continue as you were.
2. Read the docs for the `nightly` version.

**Comment by efifogel** [comment]
Yep; this fixes it...thanks
I guess you can close the issue.
Less importantly,  not having "master" as the default is, I think, unconventional; not alerting the user (that is, a developer like I'm) about it is radical (:). 
I guess this is (at least one reason) for kind of forcing the developer to have the build directory under the root of the clone; however, this is another anomaly. I don't think that stating the version or the fact that the clone is "dirty" is worth it.  One (big) nice feature of cmake is out-of-source build. It is still possible, but annoying messages are generated. In my opinion build_version.cmake (called from the main CMakeLists.txt) should NOT be called by default.
