### ISSUE TITLE
The exception unknown software exception occured in the application

### ISSUE THREAD

**Issue by JMTK** [LizardByte/Sunshine#2156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

![image](https://github.com/LizardByte/Sunshine/assets/877114/918d55c5-52d6-4479-9d9f-f7528656edc5)

Not sure exactly what's causing this. It *might* be related to Helldivers 2, since the only time I've seen the error is when I was playing it. I use Sunshine regularly and haven't seen this before but it's been happening quite frequently recently. I have to go restart the service after this happens.

### Host Operating System

Windows

### Operating System Version

Windows 11

### Architecture

64 bit

### Sunshine commit or version

0.21.0

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

RTX 2060

### GPU Driver/Mesa Version

551.23

### Config

```Shell
channels = 2
nv_tune = ull
gamepad = x360
min_threads = 2
hevc_mode = 0
nv_rc = cbr
fps = [30,60,90,144]
min_log_level = 2
nv_preset = p4
upnp = enabled
nv_coder = auto
fec_percentage = 30
resolutions = [
    1920x1080,
    1280x720,
    2560x1440,
    2160x1620
]
origin_pin_allowed = pc
```

### Relevant log output

```shell
Unfortunately I wasn't able to grab the logs when this happened. I will update the issue if it happens again with the logs.
```

**Comment by ReenigneArcher** [comment]
Logs are required.
