### ISSUE TITLE
kscreen-doctor prep commands can't be applied

### ISSUE THREAD

**Issue by slagiewka** [LizardByte/Sunshine#2160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

As per `nightly` docs, I'm trying out the prep commands:
Do:
```
sh -c "kscreen-doctor output.DP-3.mode.${SUNSHINE_CLIENT_WIDTH}x${SUNSHINE_CLIENT_HEIGHT}@${SUNSHINE_CLIENT_FPS} output.DP-3.scale.1"
```

Undo:
```
kscreen-doctor output.DP-3.mode.3840x2160@144 output.DP-3.scale.2
```

I've added `scale` myself. This, however does not impact the issue.

The issue that happens:
* no indication that the save fails
* the console outputs:
```
SyntaxError: JSON.parse: expected ',' or '}' after property value in object at line 1 column 187 of the JSON data
    save https://localhost:47990/assets/config-e805b93f.js:3
    save https://localhost:47990/assets/config-e805b93f.js:3
    save https://localhost:47990/assets/config-e805b93f.js:3
    _n https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    kt https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    n https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    mn https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    yb https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    Cb https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    F https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    N https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    P https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    C https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    F https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    N https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    P https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    C https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    F https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    N https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    P https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    C https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    $ https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    P https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    U https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    run https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    update https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    Z https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    le https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    Y https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    P https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    ie https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    mount https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    mount https://localhost:47990/assets/_plugin-vue_export-helper-83ac5eeb.js:5
    <anonymous> https://localhost:47990/assets/config-e805b93f.js:3
_plugin-vue_export-helper-83ac5eeb.js:5:99696

```

At one point, I made a mistake and it did save, the command was ~~
```
kscreen-doctor output.DP-3.mode.3840x@144 output.DP-3.scale.2
```

So there was no number after `x`. In fact, any digit after `x`, e.g. `x2` seems to break the save option.

### Expected Behavior

A user should be able to store a command to undo resolution change. Without having to edit the config file manually.

### Additional Context

I have no idea why `do` is provided as a shell command and `undo` is not. 

Editing `~/.config/sunshine/sunshine.conf` actually works. Trying to save config from UI with the tricked commands still fails.

### Host Operating System

Linux

### Operating System Version

Fedora 38

### Architecture

64 bit

### Sunshine commit or version

0.21.0.d1a635809ac8cf7b16913479648d067159119e97

### Package

Linux - rpm

### GPU Type

AMD

### GPU Model

AMD Radeon 6800

### GPU Driver/Mesa Version

23.3.3

### Capture Method (Linux Only)

KMS

### Config

```Shell
global_prep_cmd = [{"do":"sh -c \"kscreen-doctor output.DP-3.mode.${SUNSHINE_CLIENT_WIDTH}x${SUNSHINE_CLIENT_HEIGHT}@${SUNSHINE_CLIENT_FPS} output.DP-3.scale.1\"","undo":"kscreen-doctor output.DP-3.mode.3840x@144 output.DP-3.scale.2"}]
min_log_level = 1
output_name = 0
resolutions = [
    352x240,
    480x360,
    858x480,
    1280x720,
    1920x1080,
    2560x1080,
    3440x1440,
    1920x1200,
    3860x2160,
    3840x1600,
    1280x800
]
```

### Relevant log output

```shell
Logs (grepped by `doctor`):



[2024:02:22:19:09:49]: Debug: Parsed target [sh] from command [sh -c "kscreen-doctor output.DP-3.mode.${SUNSHINE_CLIENT_WIDTH}x${SUNSHINE_CLIENT_HEIGHT}@${SUNSHINE_CLIENT_FPS} output.DP-3.scale.1"]
[2024:02:22:19:09:49]: Info: Executing Do Cmd: [sh -c "kscreen-doctor output.DP-3.mode.${SUNSHINE_CLIENT_WIDTH}x${SUNSHINE_CLIENT_HEIGHT}@${SUNSHINE_CLIENT_FPS} output.DP-3.scale.1"]
[2024:02:22:19:10:43]: Debug: Parsed target [kscreen-doctor] from command [kscreen-doctor output.DP-3.mode.3840x@144 output.DP-3.scale.2]
[2024:02:22:19:10:43]: Debug: Resolved target [kscreen-doctor] to path ["/usr/bin/kscreen-doctor"]
[2024:02:22:19:10:43]: Info: Executing Undo Cmd: [kscreen-doctor output.DP-3.mode.3840x@144 output.DP-3.scale.2]
```

This, however was when the command was missing stuff after `x` :)
```

**Comment by ReenigneArcher** [comment]
What client are you using? It's possible that client is not sending the height.

**Comment by slagiewka** [comment]
> What client are you using? It's possible that client is not sending the height.

The missing height was in the `undo` command. Not related to clients.

When bypassed the web UI, the config works OK - clients see downsized stream and when the session is closed - desktop is back to original resolution.

**Comment by slagiewka** [comment]
> Provide the logs without grep please.

It does not make sense to provide logs. Other than the browser console logs I've already provided. That's not the issue. The config is not parseable in browser. There's no request to Sunshine's back-end.

The command can't be applied in browser, the `SyntaxError` being thrown and seen in console is already in the report.

**Comment by ReenigneArcher** [comment]
> I have no idea why do is provided as a shell command and undo is not.

Doesn't matter, use whichever method you prefer.

**Comment by ReenigneArcher** [comment]
I think the cause of the problem is from here https://github.com/LizardByte/Sunshine/blob/d1a635809ac8cf7b16913479648d067159119e97/src_assets/common/assets/web/config.html#L1411-L1421

**Comment by ReenigneArcher** [comment]
Thanks for testing!

> tried adding a prep command to a specific entry in `Applications` ✔️ (I didn't check this before)

This probably worked fine before, as the bug was only with the config, not with the apps.
