### ISSUE TITLE
After enabling RTX HDR globally on 551.61 drivers, Sunshine cannot start.

### ISSUE THREAD

**Issue by LushanCloud** [LizardByte/Sunshine#2163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Today, after updating to the beta version of the driver, Sunshine cannot start after modifying the Alt key to replace the Win key and allowing local network connections in the web UI.

### Host Operating System

Windows

### Operating System Version

windows11

### Architecture

64 bit

### Sunshine commit or version

v0.21.0

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

RTX 3060

### GPU Driver/Mesa Version

551.61

### Config

```Shell
channels = 2
address_family = both
min_log_level = 0
origin_web_ui_allowed = wan
upnp = enabled
key_rightalt_to_key_win = enabled
```

### Relevant log output

```shell
+ System 

  - Provider 

   [ Name]  Application Error 
   [ Guid]  {a0e9b465-b939-57d7-b27d-95d8e925ff57} 
 
   EventID 1000 
 
   Version 0 
 
   Level 2 
 
   Task 100 
 
   Opcode 0 
 
   Keywords 0x8000000000000000 
 
  - TimeCreated 

   [ SystemTime]  2024-02-23T09:27:46.2384765Z 
 
   EventRecordID 7880 
 
   Correlation 
 
  - Execution 

   [ ProcessID]  6368 
   [ ThreadID]  1056 
 
   Channel Application 
 
   Computer DESKTOP-DQ5R9CA 
 
  - Security 

   [ UserID]  S-1-5-18 
 

- EventData 

  AppName Sunshine.exe 
  AppVersion 0.21.0.0 
  AppTimeStamp 652ca473 
  ModuleName nvwgf2umx.dll 
  ModuleVersion 31.0.15.5161 
  ModuleTimeStamp 65cdf06b 
  ExceptionCode c0000005 
  FaultingOffset 000000000139e799 
  ProcessId 0x9f0 
  ProcessCreationTime 0x1da663a8ecad17a 
  AppPath C:\Program Files\Sunshine\Sunshine.exe 
  ModulePath C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_830091b3ebd4b98a\nvwgf2umx.dll 
  IntegratorReportId 1e8136f1-2bf7-44c7-8705-4a4bf12e2f15 
  PackageFullName  
  PackageRelativeAppId
```

**Comment by LushanCloud** [comment]
After waiting for a while, Sunshine restarted successfully. Here is the log for Sunshine.
[sunshine.log](https://github.com/LizardByte/Sunshine/files/14383888/sunshine.log)

**Comment by LushanCloud** [comment]
I have confirmed that it is the RTX HDR option in the beta driver that causes this. If I enable this option and then modify any option in the sunshine web interface, and then restart, the phenomenon of sunshine repeatedly restarting will occur.

**Comment by romracer** [comment]
> I have confirmed that it is the RTX HDR option in the beta driver that causes this. If I enable this option and then modify any option in the sunshine web interface, and then restart, the phenomenon of sunshine repeatedly restarting will occur.

Just to help clarify, are you referring to the RTX HDR feature in the *beta* Nvidia App that was released yesterday?  Or the HDR option under Adjust video image settings -> RTX Video Enhancement in the legacy Nvidia Control Panel, which is included with and has been around for a few driver versions now?

I don't believe the 551.61 drivers released yesterday are beta, but the new Nvidia App is.  Is it the drivers, or the beta app?

**Comment by Xeio** [comment]
I don't believe the RTX HDR setting is available is the legacy control panel.

Personally, I have RTX HDR enabled globally for all applications, but selected sunshine.exe and turned it off just for that specific app which seems to work.

![image](https://github.com/LizardByte/Sunshine/assets/25418/ddb3fd7d-39db-4d82-8401-d4679feab49a)

**Comment by LushanCloud** [comment]
> > 我已经确认是 beta 驱动程序中的 RTX HDR 选项导致了这种情况。如果我启用此选项，然后在 sunshine web 界面中修改任何选项，然后重新启动，就会出现 sunshine 反复重启的现象。
> 
> 只是为了帮助澄清，您指的是昨天发布的_测试版_ Nvidia App 中的 RTX HDR 功能吗？或者旧版 Nvidia 控制面板中的“调整视频图像设置 -> RTX 视频增强”下的 HDR 选项，该选项包含在驱动程序版本中，并且已经存在了几个驱动程序版本？
> 
> 我不相信昨天发布的 551.61 驱动程序是测试版，但新的 Nvidia 应用程序是。是驱动程序，还是测试版应用程序？

It was my mistake. It should be the new beta version of the NVIDIA application, which includes the RTX HDR option.

**Comment by mitchmeister03** [comment]
Also confirming this, if you disable RTX HDR, Sunshine works fine. Enable it, constant reboots.

**Comment by cgutman** [comment]
The crash occurs deep inside Nvidia's driver during the call to `CreateTexture2D()` here - https://github.com/LizardByte/Sunshine/blob/d1a635809ac8cf7b16913479648d067159119e97/src/platform/windows/display_vram.cpp#L1461-L1468

Notably, it only seems to crash when we're creating a texture with initial data. It looks pretty clearly like a driver bug causing them to read outside the bounds of our initial data buffer. My bet is they're turning our `DXGI_FORMAT_B8G8R8A8_UNORM` texture into a `DXGI_FORMAT_R16G16B16A16_FLOAT` texture behind the scenes to do HDR upconversion, but they forgot to adjust the size of their data copy for the fact that the new format is twice as large as the old one.

Indeed, doubling the size of the initial data buffer resolves the crash.

**Comment by yungleballz** [comment]
might be a good idea to include "RTX HDR" in the title
