### ISSUE TITLE
Can't play embeded videos in some websites

### ISSUE THREAD

**Issue by Adelyann** [LizardByte/Sunshine#2169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I am trying to set up sunshine to replace my GFE setup. I got a problem when trying to play some embeded video : I see a black area where the video should be playing. I see the web interface in my browser and i can hear the sound. When I check the logs of sunshine I see this error : Windows is currently blocking DRM-protected content from capture How can I prevent this ?

### Expected Behavior

Video should appears

### Host Operating System

Windows

### Operating System Version

Windows 11

### Architecture

32 bit

### Sunshine commit or version

0.21.0

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

RTX 3090

### GPU Driver/Mesa Version

551.61

### Config

```Shell
encoder = nvenc
```

### Relevant log output

```shell
Warning: Windows is currently blocking DRM-protected content from capture. You may see black regions where this content would be.
```

**Comment by ReenigneArcher** [comment]
There is nothing we can do about this right now

**Comment by ReenigneArcher** [comment]
We cannot capture DRM protected content. It is intentionally blocked from being captured.

**Comment by iz8mbw** [comment]
OK, I unerstand/agree. But I don't udersrand why with Chrome it works.
