### ISSUE TITLE
Error: DuplicateOutput Failed, 0x80070005

### ISSUE THREAD

**Issue by rubin55** [LizardByte/Sunshine#217]
### Describe the Bug

I have Sunshine 0.14.0 set up, on a Windows 10 host, with a Radeon 6900XT. I access the host using Moonlight 3.2.0, on Linux (void, Linux kernel 5.18.5). 

I verified everything works ok: I can access the Windows desktop, 4k, 60fps. I can flawlessly work and stream audio, play some video through VLC. I also tested a few games, like Skyrim and Sekiro, which worked flawlessly also, no lag, super low latency.

When I try and play Assassin's Creed: Odyssey, I start from Steam. Looking at Process Explorer, I see the ACOdyssey.exe being suspended and "handed" over to Uplay (I.e., some weird stuff going on there with the Ubisoft launcher, the parent process changes essentially). After that, Assassin's Creed: Odyssey loads, I see a few movies that I can click-skip and I end up in the main game menu. 

If I click "Continue", "Benchmark", "Load" or "New Game" The loading screen shows. After that I crash to desktop and I see Uplay uploading some crash log (i.e., uplay detected that the game crashed). In the sunshine.log I see:

`[2022:06:20:22:06:42]: Error: DuplicateOutput Failed [0x80070005]`

### Expected Behavior

I expect Assassin's Creed: Odyssey to work as awesomely as everything else does using Sunshine and Moonlight!

### Additional Context

log:
```txt
[2022:06:20:21:52:32]: Info: Found encoder amdvce: [h264_amf, hevc_amf]
[2022:06:20:21:52:32]: Info: Configuration UI available at [https://localhost:47990]
[2022:06:20:21:52:33]: Info: Registered Sunshine Gamestream service
[2022:06:20:21:54:14]: Info: /CN=NVIDIA GameStream Client -- verfied
[2022:06:20:21:54:14]: Info: /CN=NVIDIA GameStream Client -- verfied
[2022:06:20:21:54:17]: Info: /CN=NVIDIA GameStream Client -- verfied
[2022:06:20:21:54:18]: Info: /CN=NVIDIA GameStream Client -- verfied
[2022:06:20:21:54:18]: Info: CLIENT CONNECTED
[2022:06:20:21:54:18]: Info:
Device Description : AMD Radeon RX 6900 XT
Device Vendor ID   : 0x00001002
Device Device ID   : 0x000073AF
Device Video Mem   : 16337 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16339 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160

[2022:06:20:21:55:48]: Info:
Device Description : AMD Radeon RX 6900 XT
Device Vendor ID   : 0x00001002
Device Device ID   : 0x000073AF
Device Video Mem   : 16337 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16339 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160

[2022:06:20:21:59:20]: Info:
Device Description : AMD Radeon RX 6900 XT
Device Vendor ID   : 0x00001002
Device Device ID   : 0x000073AF
Device Video Mem   : 16337 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16339 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160

[2022:06:20:22:06:42]: Info:
Device Description : AMD Radeon RX 6900 XT
Device Vendor ID   : 0x00001002
Device Device ID   : 0x000073AF
Device Video Mem   : 16337 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16339 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160
[2022:06:20:22:06:42]: Error: DuplicateOutput Failed [0x80070005]
[2022:06:20:22:06:43]: Info:
Device Description : AMD Radeon RX 6900 XT
Device Vendor ID   : 0x00001002
Device Device ID   : 0x000073AF
Device Video Mem   : 16337 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16339 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160
```

### Sunshine Host Operating System and Version

Windows 10 host, Linux client

### Architecture

x86_64

### Sunshine Version

0.14.0

### GPU Type

AMD

### GPU Model

AMD Radeon 6900XT

### GPU Driver/Mesa Version

AMD Software PRO Edition 22.Q2

**Comment by rubin55** [comment]
Here's the [sunshine.log](https://github.com/SunshineStream/Sunshine/files/8943487/sunshine.log).

**Comment by rubin55** [comment]
I ran across [this troubleshooting article](https://docs.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/error-when-dda-capable-app-is-against-gpu) on MSDN. It seems to be about this specific error, but I have no idea what they mean by a "Microsoft Hybrid" system. My PC is a beefy AMD Ryzen 9 5950x running the latest version of Windows 10.

**Comment by rubin55** [comment]
Talked to @ReenigneArcher about this on Discord. This issue seems to happen specifically with Assassin's Creed: Odyssey. In all cases the `DuplicateOutput` error is logged. 

I checked with about 10 other non-UbiSoft games which started normally and verified that this error is not logged.

I then enabled `Verbose` (it was a bit noisy) and later `Debug logging to see if there were relevant other log messages, but there were none. I then offered to dig into the code and go to this specific point where this (I assume exception) is logged and see if I can expand the logging there a bit to see what's going on at the DDA api level and/or what the driver might think at that moment.

I'll see if I can dig into this the coming week. I will also test other UbiSoft games, because I suspect Uplay could be a factor in this.

**Comment by rubin55** [comment]
So I verified a few things:

  * AC: Odyssey fails with DuplicateOutput in sunshine.log when client is connected before the game starts up, i.e. connect to Desktop session, start game, watch the game start to the main menu, select continue or new game, observe crash-to-desktop
  * AC: Odyssey starts correctly when no client is connected and sunshine is running. When the game is up, i.e., within the 3D engine so-to-speak, you can connect a client and you will be able to play (a quirky work-around right there)

**Comment by rubin55** [comment]
I found a previous issue in the old sunshine that looks remarkably similar: https://github.com/loki-47-6F-64/sunshine/issues/46

**Comment by Swany6mm** [comment]
I'm getting the same thing when just trying to connect Moonlight to the Sunshine host dekstop - Just keeps repeating the error over and over until it finally times out/crashes.

This is my first go with Sunshine and Moonlight - When I was running a bare metal system I had GFE and Moonlight working, then I switched to a Win10 host, Hyper V VM and have it working with Parsec. Just found out about Sunshine and am now trying to set it up - Moonlight sees the system no problem, just get that Duplicateoutput Failed error when tyring to connect

**Comment by ReenigneArcher** [comment]
@Swany6mm this is off topic, please reach out on discord

**Comment by agamkohli9** [comment]
I have this exact same issue with Counter Strike 2 and for some reason, using my HDMI/DP connected to my monitor instead of a dummy DP fixes this issue. Not sure how that even affects anything since the dummy DP should be acting exactly like a normal DP plug.
