### ISSUE TITLE
Macbook m2 cannot open web ui page

### ISSUE THREAD

**Issue by yuanjypku** [LizardByte/Sunshine#2170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

browser: Microsoft Edge

I've build sunshine from source on m2 macbook, the app seems to be run properly:

> macbook@bogon build% ./sunshine          
> [resolutions] -- [[
>     352x240,
>     480x360,
>     858x480,
>     1280x720,
>     1920x1080,
>     2560x1080,
>     3440x1440,
>     1920x1200,
>     3860x2160,
>     3840x1600,
>     2250x1500,
>     2256x1504
> ]]
> [mouse] -- [disabled]
> [controller] -- [disabled]
> [keyboard] -- [disabled]
> [sunshine_name] -- [Tenesysbook]
> [output_name] -- [1]
> [2024:02:24:23:14:49]: Info: Sunshine version: 0.21.0.dde804f
> [2024:02:24:23:14:49]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
> [2024:02:24:23:14:49]: Info: Trying encoder [videotoolbox]
> [2024:02:24:23:14:49]: Info: SDR color coding [Rec. 601]
> [2024:02:24:23:14:49]: Info: Color depth: 8-bit
> [2024:02:24:23:14:49]: Info: Color range: [JPEG]
> [2024:02:24:23:14:49]: Warning: [h264_videotoolbox @ 0x157609570] PrioritizeEncodingSpeedOverQuality property is not supported on this device. Ignoring.
> [2024:02:24:23:14:49]: Info: [h264_videotoolbox @ 0x157609570] This device does not support the AllowOpenGop option. Value ignored.
> [2024:02:24:23:14:49]: Info: SDR color coding [Rec. 601]
> [2024:02:24:23:14:49]: Info: Color depth: 8-bit
> [2024:02:24:23:14:49]: Info: Color range: [JPEG]
> [2024:02:24:23:14:49]: Info: SDR color coding [Rec. 601]
> [2024:02:24:23:14:49]: Info: Color depth: 8-bit
> [2024:02:24:23:14:49]: Info: Color range: [JPEG]
> [2024:02:24:23:14:49]: Error: Couldn't open [av1_videotoolbox]
> [2024:02:24:23:14:49]: Info: SDR color coding [Rec. 709]
> [2024:02:24:23:14:49]: Info: Color depth: 10-bit
> [2024:02:24:23:14:49]: Info: Color range: [JPEG]
> [2024:02:24:23:14:49]: Info: 
> [2024:02:24:23:14:49]: Info: // Ignore any errors mentioned above, they are not relevant. //
> [2024:02:24:23:14:49]: Info: 
> [2024:02:24:23:14:49]: Info: Found H.264 encoder: h264_videotoolbox [videotoolbox]
> [2024:02:24:23:14:49]: Info: Found HEVC encoder: hevc_videotoolbox [videotoolbox]
> [2024:02:24:23:14:49]: Error: Failed to create client: Daemon not running
> [2024:02:24:23:14:49]: Info: Configuration UI available at [https://localhost:47990]

>
however, when I try to open the url[https://localhost:47990] in my browser, It shows a totally blank page:
![image](https://github.com/LizardByte/Sunshine/assets/50740765/828ef0d6-630f-463d-ab5c-6312ab4afc13)

I've tried both Microsoft Edge and Safari, both shows blanck page.
I've tried to re run the command and clean the browser cache

### Host Operating System

macOS

### Operating System Version

14.1.1 (23B81)

### Architecture

arm

### Sunshine commit or version

0.21.0.dde804f

### Package

other (self built)

### GPU Type

n/a

### GPU Model

m2

### GPU Driver/Mesa Version

latest

### Config

```Shell
output_name = 1
sunshine_name = Tenesysbook
controller = disabled
keyboard = disabled
mouse = disabled
resolutions = [
    352x240,
    480x360,
    858x480,
    1280x720,
    1920x1080,
    2560x1080,
    3440x1440,
    1920x1200,
    3860x2160,
    3840x1600,
    2250x1500,
    2256x1504
]%
```

### Relevant log output

```shell
None
```

**Comment by yuanjypku** [comment]
I've found a [similar issue](https://github.com/loki-47-6F-64/sunshine/issues/148) on Linux, which is about Daemon not running
However, the solution is just for Linux, not workable on Mac.

**Comment by ReenigneArcher** [comment]
You need to run make install

**Comment by yuanjypku** [comment]
thanks, the issue is solved

**Comment by Geczy** [comment]
why is make install not part of the build docs? https://docs.lizardbyte.dev/projects/sunshine/en/latest/building/macos.html#macos

i also had to run `sunshine --creds {new-username} {new-password}` which should also be part of the build

**Comment by ReenigneArcher** [comment]
> why is make install not part of the build docs?

Because it's not required to build a package, which is what most people should do. There's no way to easily revert a `make install`

> i also had to run sunshine --creds {new-username} {new-password} which should also be part of the build

That's not necessary. You set credentials in the ui when it first opens.
