### ISSUE TITLE
[MacOS] port upgrade 0.21.0 -> 0.22.0 Failed

### ISSUE THREAD

**Issue by BlackdeerY** [LizardByte/Sunshine#2210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

sudo port upgrade sunshine,
sudo port install sunshine.

Failed. 0.21.0 -> 0.22.0.

**I attach main.log**
[main.log](https://github.com/LizardByte/Sunshine/files/14481254/main.log)

### Additional Context

[main.log](https://github.com/LizardByte/Sunshine/files/14481254/main.log)

### Host Operating System

macOS

### Operating System Version

Sonoma 14.3.1

### Architecture

arm

### Sunshine commit or version

0.22.0

### Package

macOS - Portfile

### GPU Type

none (software encoding)

### GPU Model

M2

### GPU Driver/Mesa Version

M2

### Config

```Shell
build error.
```

### Relevant log output

```shell
**I attach main.log**
[main.log](https://github.com/LizardByte/Sunshine/files/14481254/main.log)
```

**Comment by SansNom0** [comment]
Same problem on a M3 Pro
[main.log](https://github.com/LizardByte/Sunshine/files/14485629/main.log)

**Comment by darox** [comment]
Fresh installation also fails here:
```
:info:build 1 error generated.
:info:build make[2]: *** [CMakeFiles/sunshine.dir/src/main.cpp.o] Error 1
:info:build make[2]: *** Waiting for unfinished jobs....
:info:build make[2]: Leaving directory `/opt/local/var/macports/build/_Users_dario_ports_multimedia_sunshine/Sunshine/work/build'
:info:build make[1]: *** [CMakeFiles/sunshine.dir/all] Error 2
:info:build make[1]: Leaving directory `/opt/local/var/macports/build/_Users_dario_ports_multimedia_sunshine/Sunshine/work/build'
:info:build make: *** [all] Error 2
:info:build make: Leaving directory `/opt/local/var/macports/build/_Users_dario_ports_multimedia_sunshine/Sunshine/work/build'
:info:build Command failed:  cd "/opt/local/var/macports/build/_Users_dario_ports_multimedia_sunshine/Sunshine/work/build" && /usr/bin/make -j8 -w all VERBOSE=ON 
:info:build Exit code: 2
:error:build Failed to build Sunshine: command execution failed
:debug:build Error code: CHILDSTATUS 23559 2
:debug:build Backtrace: command execution failed
:debug:build     while executing
:debug:build "system {*}$notty {*}$callback {*}$nice $fullcmdstring"
:debug:build     invoked from within
:debug:build "command_exec -callback portprogress::target_progress_callback build"
:debug:build     (procedure "portbuild::build_main" line 10)
:debug:build     invoked from within
:debug:build "$procedure $targetname"
:error:build See /opt/local/var/macports/logs/_Users_dario_ports_multimedia_sunshine/Sunshine/main.log for details.

```
