### ISSUE TITLE
Sunshine Crashes when Ryujinx is Compiling Shaders

### ISSUE THREAD

**Issue by QuirkyKirkHax** [LizardByte/Sunshine#2219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

With the latest version of Ryujinx, Sunshine seems to crash when a game compiles shaders on launch, and if the stream is rejoined afterwards, it seems to crash after a bit of gameplay, presumably also from shader compilation.  I believe this was the same issue as #878.

I have the latest nightly Sunshine release, Moonlight is up to date, my GPU drivers are up to date, and so is Ryujinx.  I am unsure if the issue is from Ryujinx or Sunshine really, but Windows event viewer gives the following in regards to the crash:

Faulting application name: Sunshine.exe, version: 0.22.0.0, time stamp: 0x65e5b22f
Faulting module name: ntdll.dll, version: 10.0.19041.3996, time stamp: 0x39215800
Exception code: 0xc0000374
Fault offset: 0x00000000000ff349
Faulting process id: 0x4124
Faulting application start time: 0x01da6f0df7268e5f
Faulting application path: C:\Program Files\Sunshine\Sunshine.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 4422a667-5c72-4567-92e0-d13515516448
Faulting package full name: 
Faulting package-relative application ID:

### Expected Behavior

This change is recent, within the last few months I was able to play games on Ryujinx without issue.  This leads me to believe it is likely an issue with Ryujinx, but I figure it is better to post this bug here as well since Sunshine is what appears to be crashing.

### Host Operating System

Windows

### Operating System Version

01

### Architecture

64 bit

### Sunshine commit or version

0.22.0

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

Geforce RTX 3070 FE

### GPU Driver/Mesa Version

551.61

### Config

```Shell
min_log_level = 2
nv_rc = cbr
hevc_mode = 0
nv_tune = ull
nv_preset = p4
nv_coder = auto
gamepad = x360
resolutions = [
    352x240,
    480x360,
    858x480,
    1280x720,
    1920x1080,
    2560x1080,
    3440x1440,
    1920x1200,
    3860x2160,
    3840x1600
]
encoder = nvenc
channels = 2
```

### Apps

```json
{
    "env": {
        "PATH": "$(PATH);$(ProgramFiles(x86))\\Steam"
    },
    "apps": [
        {
            "name": "Desktop",
            "image-path": "desktop.png"
        },
        {
            "name": "Steam Big Picture",
            "detached": [
                "steam steam:\/\/open\/bigpicture"
            ],
            "image-path": "steam.png"
        },
        {
            "name": "BigBox",
            "output": "bigbox.log",
            "cmd": "",
            "working-dir": "",
            "image-path": "C:\\Users\\QUIRK\\Pictures\\Sunshine\\BigBox.png",
            "detached": [
                "C:\\Users\\QUIRK\\LaunchBox\\BigBox.exe"
            ]
        }
    ]
}
```

### Relevant log output

```shell
Because the stream crashes, I can't grab any logs...Best I have is the crash report from event viewer:

Faulting application name: Sunshine.exe, version: 0.22.0.0, time stamp: 0x65e5b22f
Faulting module name: ntdll.dll, version: 10.0.19041.3996, time stamp: 0x39215800
Exception code: 0xc0000374
Fault offset: 0x00000000000ff349
Faulting process id: 0x4124
Faulting application start time: 0x01da6f0df7268e5f
Faulting application path: C:\Program Files\Sunshine\Sunshine.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 4422a667-5c72-4567-92e0-d13515516448
Faulting package full name: 
Faulting package-relative application ID:
```

**Comment by cgutman** [comment]
I think this is our "hung encoder" breakpoint. Do you have Hardware Accelerated GPU Scheduling enabled on your PC?

**Comment by SPWizard01** [comment]
Same behavior here, and yes the setting is enabled for me:
![image](https://github.com/LizardByte/Sunshine/assets/27969609/6f8ec689-5400-47ab-ab5a-031618c98480)

**Comment by Rahzadan** [comment]
Same issue here. Using Sunshine 0.22.0. Seems to be new behavior within the last 1-2 releases of Ryujinx. I am using version 1.1.1217 and this Sunshine crash is present, with the very same error as @QuirkyKirkHax in Windows Event Viewer.

@cgutman  - I also tried disabling Hardware Accelerated GPU Scheduling as you suggested (followed by a reboot), but the crash is still present whether or not that setting is enabled.

**Comment by Rahzadan** [comment]
I have confirmed that using Sunlight 0.22.0, and rolling back to Ryujinx 1.1.1215 fixes/works around this issue. It appears as though something in the newest release(s) of Ryujinx (1.1.1216-1217) has caused this crash:

https://github.com/Ryujinx/Ryujinx/wiki/Changelog

Looking at the changelog for Ryujinx, 1.1.1216-1217 had a large number of changes. Once of which is "Added a game loading screen which displays PPTC and shader cache progress". I'm no expert, but I'm willing to bet that something with this new game loading screen is causing the crash.

I'm staying on Ryujinx 1.1.1215 until this is fixed. The question is, does the fix need to come from Sunshine or Ryujinx?

**Comment by cgutman** [comment]
I will try to reproduce this locally if possible, but I fear it's the same NVENC hang we've been dealing with for years.

- Does it require any game in particular to reproduce? Ideally I'd like the simplest possible repro.
- Is everyone affected using Nvidia cards?
- Can you monitor your VRAM consumption when the issue is occurring? One of the known cases where the NVENC hang will happen is if VRAM usage is near the maximum.
- If you adjust the "Use realtime priority in hardware accelerated gpu scheduling" option to Disabled on the NVENC tab, does the issue go away?
- If you change the encoder to Software on the Advanced tab, does the issue go away?

**Comment by DeltaJordan** [comment]
I am having the exact same issue, except I'm using AMD (RX 6700 XT)

**Comment by cgutman** [comment]
OK, I am able to reproduce the issue. It does indeed appear to be heap corruption. I'm not sure yet why Ryujinx seems to be the only app triggering the bug.

**Comment by cgutman** [comment]
Here's a test build that should resolve the issue: https://github.com/LizardByte/Sunshine/actions/runs/8184274229/artifacts/1304939263

Give that a try and see how it goes.

**Comment by SPWizard01** [comment]
yep, this does fixes it for me, as for the bug, it would make sense since they changed the default UI on windows, probably this is how the new UI handles the cursor hiding.

**Comment by Rahzadan** [comment]
@cgutman I can confirm that the test build completely fixes the crash! Thank you!

**Comment by JukeBoX87** [comment]
Hi! If you set the "Hide cursor" parameter to Never in Ryujinx then crashes disappear. The test version also corrected the problem for me. Thanks @cgutman

**Comment by flaki** [comment]
The recently (re-)released Red Alert 2 from the [C&C Ultimate Collection](https://store.steampowered.com/bundle/39394/Command__Conquer_The_Ultimate_Collection/) seems to trigger this same bug, that game starts up in 640x480, 16bit, I wonder if that has something to do with it.

Will try the test build and report back!

**Comment by P3rf3ctXZer0** [comment]
The test build for sure fixes this great job :D

**Comment by d3smo** [comment]
The test build link does not work, is it possible to have a new one ?

**Comment by ReenigneArcher** [comment]
> The test build link does not work, is it possible to have a new one ?

Just update Sunshine to v0.22.2
