### ISSUE TITLE
Mac installer is only a folder with loose files.

### ISSUE THREAD

**Issue by luckydonald** [LizardByte/Sunshine#2249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

The `.dmg` does not contain an installer, only loose files.

<img width="478" alt="Screenshot 2024-03-13 at 14 26 16" src="https://github.com/LizardByte/Sunshine/assets/2737108/897b87d7-fa87-41fe-b66f-131a90a71aa0">

My assumption is that you choose some wrong form of packaging.
Especially based on the fact that is has a simlink to the Applications folder, which is a usual drag-and-drop install way for Mac apps.
Maybe it must be configured to again create an `*.pkg` inside of the `*.dmg`, not just including the assets to install.

Note: There's no `*.dmg` in the nightly, so I couldn't test that.

### Expected Behavior

Be a installer or a app which can be dragged into applications folder.

### Additional Context

see above

### Host Operating System

macOS

### Operating System Version

13.2, but irrelevant to the packacking from your releases

### Architecture

arm

### Sunshine commit or version

v0.22.0

### Package

macOS - dmg

### GPU Type

n/a

### GPU Model

M1 mac

### GPU Driver/Mesa Version

How would I know that?

### Capture Method (Linux Only)

-

### Config

```Shell
Not present
```

### Apps

```json
-
```

### Relevant log output

```shell
-
```

**Comment by ReenigneArcher** [comment]
You can use Macports for any version prior to v0.22.1, otherwise wait a few hours for the next release and you can use Homebrew 🍺 

Anyway, this has already been documented in our documentation for a long time.

https://docs.lizardbyte.dev/projects/sunshine/en/v0.22.0/about/setup.html
![image](https://github.com/LizardByte/Sunshine/assets/42013603/08d022b8-30e2-4203-8aad-cd612d5f90d9)

https://github.com/LizardByte/Sunshine/issues/186

**Comment by luckydonald** [comment]
❤️

**Comment by luckydonald** [comment]
For reference:
```shell
brew tap LizardByte/homebrew
brew install sunshine
```
