### ISSUE TITLE
Sunshine doesn't handle missing libminiupnpc.so, which should be treated as an optional dependency

### ISSUE THREAD

**Issue by drws** [LizardByte/Sunshine#2271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Sunshine currently fails without `libminiupnpc.so` installed in the system. Also the [PKGBUILD](https://github.com/LizardByte/Sunshine/blob/nightly/packaging/linux/Arch/PKGBUILD) shouldn't force it as an explicit dependency since it is used in Sunshine in a manner of optional one.

### Expected Behavior

UPnP functionality is not crucial for Sunshine operation. It is also already [configurable](https://docs.lizardbyte.dev/projects/sunshine/en/latest/about/advanced_usage.html#upnp) and even turned off by default. Therefore the `sunshine` binary shouldn't depend on `libminiupnpc.so` directly. More appropriate behavior would be:

* UPnP not configured by user, so **disabled** by default. Sunshine could warn the user of missing optional dependency, but still work, since nothing is actually wrong.
* UPnP explicitly **disabled** by user. In this case Sunshine should suppress the warning (and possibly still print it when increased verbosity or debug options are set).
* UPnP **enabled** by user, dependency not available. Exit with an error. Similar to current behavior, but in a controlled way with a suitable exit code.
* UPnP **enabled** and available. Possibly still print an info/debug-level notice of dependency detection if deemed useful.

### Host Operating System

Linux

### Operating System Version

Arch rolling

### Architecture

64 bit

### Sunshine commit or version

0.22.1

### Package

Linux - PKGBUILD

### GPU Type

n/a

### GPU Model

n/a

### GPU Driver/Mesa Version

n/a

### Config

```Shell
n/a
```

### Relevant log output

```shell
n/a
```

**Comment by ReenigneArcher** [comment]
The dependency is required, as intended.

**Comment by drws** [comment]
Would you care to explain more? I went through docs last week and don't recall any of this. Also, as said in OP, **UPnP is disabled by default** in Sunshine. And secondly, you simply cannot rely on users' networks to offer this service.

So why would it be required?

**Comment by ReenigneArcher** [comment]
It's disabled by default, but the dependency is required in case the option is enabled.

Making the dependency optional, will make things unnecessarily complicated. Then we would have to provide a different UI to users who don't have the dependency, versus those who do?

We have enough actual bugs to deal with, without introducing unnecessary changes.

**Comment by drws** [comment]
I understand, especially since we're at somewhat early stages of development. However, reducing dependencies is still a welcome improvement that could be addressed in the long run. Hopefully Sunshine is here to stay and someday there will be time to polish even such minor issues. Please reconsider reopening this and tagging it for the long run.

**Comment by ReenigneArcher** [comment]
If this were CUDA, that would be a legitimate concern. miniupnpc is 131 KB in size. There isn't much to gain from making this optional, but there's a lot of potential downsides.
