### ISSUE TITLE
Pairing only one device after unpair all devices pair all of them again without the need of a PIN

### ISSUE THREAD

**Issue by MatheusJCastro** [LizardByte/Sunshine#2305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

After unpairing all devices in the web UI interface and them pairing only one device, sunshine pair all of the previously devices again. 
I have 3 paired devices through my lan using moonlight as client and sunshine as server. If I unpair all the devices in the Troubleshooting tab, then pair one device again, without removing the server in my moonlight clients, all of them are automatically paired again.
The only way to not have them paired without a pin again, is to forget the sunshine server in the moonlight client. If I do this, when pairing them, the pin is asked normally.
To reproduce it:
- Pair 2 or more devices in a sunshine server. Do as regular: type the pin for both in the sunshine web UI.
- Unpair all devices in the Troubleshooting tab. The server in all devices should have a locker. Do not forget the sunshine server in the devices.
- Pair only one device again, using the pin in the web UI.
- The other devices that were previously paired and forgotten by the sunshine server are now paired again without the need of a pin. i.e. the locker disappear and the connection to the stream is made successfully.  

### Expected Behavior

After unpairing all devices, they should not be paired again without a pin even if the server are still present in the client.

### Additional Context

I was planning to stream my server to friends, but with this, even if I remove all paired clients, they will gain access to my computer without the need of my authorization again. Making the use for this case impossible.

### Host Operating System

Linux

### Operating System Version

Arch Linux Kernel 6.7.5-arch1-1

### Architecture

64 bit

### Sunshine commit or version

0.22.2

### Package

Linux - AUR (Third Party)

### GPU Type

none (software encoding)

### GPU Model

Intel Alder Lake-S GT1 [UHD Graphics 730]

### GPU Driver/Mesa Version

mesa 1:24.0.1-1

### Capture Method (Linux Only)

X11

### Config

```Shell
channels = 2
key_rightalt_to_key_win = enabled
min_threads = 2
sw_tune = film
av1_mode = 0
upnp = enabled
resolutions = [
    352x240,
    480x360,
    858x480,
    1280x720,
    1920x1080,
    2560x1080,
    3440x1440,
    1920x1200,
    3840x2160,
    3840x1600,
    2560x1600
]
fps = [10,30,60,90,15,20]
```

### Relevant log output

```shell
Logs does not show anything about pairing info in my case.
```

**Comment by gschintgen** [comment]
If this is confirmed it's a rather grave security issue IMHO.

**Comment by ReenigneArcher** [comment]
I'll try to replicate this shortly.
