### ISSUE TITLE
If an application is already loaded when sunshine starts it will attempt to run (load) it again

### ISSUE THREAD

**Issue by KINGLIFER** [LizardByte/Sunshine#2334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

If you have say LaunchBox (Bigbox) as an application and it so happens to be running before sunshine loads it will attempt to load it again. Of course this will bring up an error that another instance of Launchbox is already running. 

There is no fix I can see for this. Keep in mind not everyone is a github user. This set up is for my family so it runs almost flawlessly. However if for some reason they do not exit out of moonlight and hours pass and someone tries to use Sunshine again the error can occur.

It should check to see if the application is already loaded and if so give that window focus. That is my opinion.

### Host Operating System

Docker

### Operating System Version

Windows 11

### Architecture

32 bit

### Sunshine commit or version

0.22.2

### Package

Linux - AppImage

### GPU Type

AMD

### GPU Model

GeForce 3090

### GPU Driver/Mesa Version

.

### Config

```Shell
.
```

### Apps

```json
LaunchBox
```

### Relevant log output

```shell
..
```

**Comment by ReenigneArcher** [comment]
IF it is detached AND you are starting a new session, it will it again. There is no way around this right now.

But IF it is detached AND you are resuming the session, it should not start again.

So, what you will need to do if you want to avoid starting multiple copies of the same application, you will need to properly end the application before you end your stream... or create your own application start script that checks if it's already running before starting a new one.

**Comment by KINGLIFER** [comment]
> IF it is detached AND you are starting a new session, it will it again. There is no way around this right now.
> 
> But IF it is detached AND you are resuming the session, it should not start again.
> 

Thank you but that is not what happened.
I believe you can recreate this bug. Add a program to sunshine. (I had Bigbox). Then IF the program is running twice (from say a child quitting and loading it back) and I decide to force quit that program (By going to the PC and stopping it) sunshine will give a notification popup that  the application has quit (since there is two running) but then if the person gets control of the application (focus) sunshine will attempt to load it again causing a conflict and then it will loop.

I will attempt to reproduce it with something smaller and more common to help with understanding the error.
