### ISSUE TITLE
0.23.0: CMake error when trying to build with tests disabled (-DBUILD_TESTS:BOOL=FALSE)

### ISSUE THREAD

**Issue by tgurr** [LizardByte/Sunshine#2383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Trying to build 0.23.0 (update our Exherbo Linux package from 0.22.2 to 0.23.0) with the newly introduced CMake variable for tests passing `-DBUILD_TESTS:BOOL=FALSE` results in a CMake configure error:

```
[...]
-- Tray icon disabled
-- Checking for module 'systemd'
--   Found systemd, version 255
CMake Error at cmake/targets/common.cmake:60 (set_source_files_properties):
  set_source_files_properties given non-existent DIRECTORY
  /var/tmp/paludis/build/net-remote-sunshine-0.23.0/work/sunshine-0.23.0/tests
Call Stack (most recent call first):
  CMakeLists.txt:56 (include)


CMake Error at cmake/targets/common.cmake:65 (set_source_files_properties):
  set_source_files_properties given non-existent DIRECTORY
  /var/tmp/paludis/build/net-remote-sunshine-0.23.0/work/sunshine-0.23.0/tests
Call Stack (most recent call first):
  CMakeLists.txt:56 (include)


CMake Error at cmake/targets/common.cmake:76 (set_source_files_properties):
  set_source_files_properties given non-existent DIRECTORY
  /var/tmp/paludis/build/net-remote-sunshine-0.23.0/work/sunshine-0.23.0/tests
Call Stack (most recent call first):
  CMakeLists.txt:56 (include)


-- Checking for module 'udev'
--   Found udev, version 255

-- Configuring incomplete, errors occurred!
```

Complete build log: [sunshine-0.23.0.log](https://github.com/LizardByte/Sunshine/files/14897193/sunshine-0.23.0.log)

### Expected Behavior

Do not fail to build when disabling building the tests.

### Additional Context

Passing `-DBUILD_TESTS:BOOL=TRUE` to have building the tests enabled makes CMake configure pass and the build of 0.23.0 succeed.

### Host Operating System

Linux

### Operating System Version

-

### Architecture

64 bit

### Sunshine commit or version

0.23.0

### Package

other (not listed)

### GPU Type

AMD

### GPU Model

RX 7800 XT

### GPU Driver/Mesa Version

mesa 24.04

### Capture Method (Linux Only)

PipeWire/X11/KMS

### Config

```Shell
-
```

### Relevant log output

```shell
-
```

**Comment by ReenigneArcher** [comment]
Should be `-DBUILD_TESTS=OFF`

**Comment by tgurr** [comment]
> Should be `-DBUILD_TESTS=OFF`

OFF/FALSE shouldn't matter as long it's a boolean, but here's a log with the same outcome passing `-DBUILD_TESTS=OFF` explicitly: 
[sunshine-0.23.0.log](https://github.com/LizardByte/Sunshine/files/14897487/sunshine-0.23.0.log)

> Although shouldn't you enable tests and verify they succeed before distributing a package?

Since we're a source-based distributions we're not distributing a classic "package" per se, building+running the tests is made optional where possible and in the hands of the users and thus may also be dependent on the specifics of the end users systems. Hence we provide the option and also default it to on, but restrict it for packages where it doesn't work for example which could be for various reasons like hardware related dependencies, doing fancy stuff which might be sandboxed in our build process, things that don't work on CI and so on. So to make it short in the best scenario we require the package to work with tests enabled AND disabled.

**Comment by ReenigneArcher** [comment]
I see the issue... but did you delete the `tests` directory?

Even with the build flag off I wouldn't expect the errors you are getting, unless you've removed the `tests` directory altogether.

**Comment by ReenigneArcher** [comment]
I see the issue. I'll try to put a fix out soon.

**Comment by ReenigneArcher** [comment]
Please try #2386 and let me know the results.
