### ISSUE TITLE
Web interface claims there is a new version, while running latest available

### ISSUE THREAD

**Issue by slagiewka** [LizardByte/Sunshine#2406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Same as https://github.com/LizardByte/Sunshine/issues/1103, but now with [0.22 and 0.23](https://github.com/LizardByte/Sunshine/issues/1103#issuecomment-2044233121).

Nightly is fine (yet I had to check the box)
![image](https://github.com/LizardByte/Sunshine/assets/11974489/e9be30fd-781e-4604-86e8-ac19e230f437)

### Host Operating System

Linux

### Operating System Version

Fedora

### Architecture

64 bit

### Sunshine commit or version

0.23.0

### Package

Linux - rpm

### GPU Type

AMD

### GPU Model

RX 6800

### GPU Driver/Mesa Version

24

### Config

```Shell
resolutions = [
    352x240,
    480x360,
    858x480,
    1280x720,
    1920x1080,
    2560x1080,
    3440x1440,
    1920x1200,
    3860x2160,
    3840x1600,
    1280x800
]
output_name = 0
min_log_level = 1
global_prep_cmd = [{"do":"sh -c \"kscreen-doctor output.DP-3.mode.${SUNSHINE_CLIENT_WIDTH}x${SUNSHINE_CLIENT_HEIGHT}@${SUNSHINE_CLIENT_FPS} output.DP-3.scale.1\"","undo":"kscreen-doctor output.DP-3.mode.3840x2160@144 output.DP-3.scale.2"},{"do":"loginctl unlock-session","undo":""}]
min_threads = 4
```

### Relevant log output

```shell
n/a
```

**Comment by gschintgen** [comment]
I noticed this too with 0.22.2 but for the `.deb`s built for Ubuntu 22.04. (Can't say right now if it's still the case with 0.23.)

**Comment by ReenigneArcher** [comment]
Hmm... I don't have this problem

![image](https://github.com/LizardByte/Sunshine/assets/42013603/042e487d-917e-4f3d-a747-d3e4fa4ceb26)

But I think I see the issue. My screenshot doesn't have the `v` prefix, while your old screenshot (from https://github.com/LizardByte/Sunshine/issues/1103#issuecomment-2044233121) does.

**Comment by gschintgen** [comment]
Ubuntu 22.04 with Sunshine 0.23 installed from he .deb:
![image](https://github.com/LizardByte/Sunshine/assets/11065156/36248b0e-4f1e-45b8-a61b-d86a951d44b5)
