### ISSUE TITLE
[Contains a solution.]Android Bluetooth mouse and keyboard remote access to PC, after a period of time, the mouse and keyboard input becomes unresponsive, but the screen transmission remains normal.

### ISSUE THREAD

**Issue by EnderCore** [LizardByte/Sunshine#2438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

在我使用安卓串流链接pc时，当我使用蓝牙键鼠远程控制pc一段时间后（通常在几十分钟到一个小时），无论是键鼠还是触摸屏都无法控制远程pc（此时无法重启sunshine服务端，通过任务管理器杀死进程后sunshine也无法手动重新启动（杀死后手动打开，但是没有如何反应，可能任务管理器没有杀死他），此时只能重启PC），此时如果我直接操作sunshine服务端所在的pc时会发现键盘会保持按下操控链接断开前我最后按下的那个按键，直至我在服务端用usb链接键盘再次按下才那个按键时，pc的控制才能恢复正常，此时，远程串流的控制才能恢复正常When using an Android streaming link to connect to my PC, after a period of remote control with a Bluetooth keyboard and mouse (typically ranging from several tens of minutes to an hour), neither the keyboard, mouse, nor touchscreen can control the remote PC.  At this juncture, restarting the Sunshine server is not feasible.  Even after terminating the process via the task manager, manual attempts to restart Sunshine prove futile (despite attempts to manually reopen it, there is no response, possibly indicating the task manager's failure to terminate it).  Hence, the only recourse is to reboot the PC.  Should I directly operate the PC where the Sunshine server resides during this time, I notice that the keyboard maintains the last pressed key until I press it again using a USB-connected keyboard at the server end.  Only then does control of the PC resume, and consequently, normal remote streaming control is restored.

### Host Operating System

Windows

### Operating System Version

11

### Architecture

64 bit

### Sunshine commit or version

0.23.0

### Package

Windows - installer

### GPU Type

Intel

### GPU Model

XE

### GPU Driver/Mesa Version

31.0.101

### Config

```Shell
upnp = enabled
nvenc_preset = 7
av1_mode = 3
address_family = both
hevc_mode = 3
locale = zh
wan_encryption_mode = 2
lan_encryption_mode = 1
```

### Relevant log output

```shell
[2024:04:18:10:44:48]: Warning: Couldn't discover any IPv4 UPNP devices
[2024:04:18:10:46:56]: Warning: Couldn't discover any IPv4 UPNP devices
[2024:04:18:10:48:10]: Info: CLIENT DISCONNECTED
```

**Comment by ReenigneArcher** [comment]
possible duplicate of #2432
