### ISSUE TITLE
Add documentation about nvidia-patch

### ISSUE THREAD

**Issue by acc029** [LizardByte/Sunshine#246]
### Describe the Bug

The docs don't tell you how to enable NvFBC.

### Expected Behavior

They should tell you that, if you get an error saying `This hardware does not support NvFBC` on a GeForce card, then you might be able to fix it by installing the patches from https://github.com/keylase/nvidia-patch

### Sunshine Host Operating System and Version

Ubuntu 22.04

### Architecture

x86-64

### Sunshine Version

0.14.0

### GPU Type

NVIDIA

### GPU Model

GeForce GTX 660 Ti (2GB)

### GPU Driver/Mesa Version

470.129.06

**Comment by ReenigneArcher** [comment]
You could open a PR instead of an issue...

Also, you could add a link to this: https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new
