### ISSUE TITLE
Flatpak config migration breaks cover images

### ISSUE THREAD

**Issue by gschintgen** [LizardByte/Sunshine#2466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

At startup Flatpak migrates an existing `~/.config/sunshine` folder to `/.var/app/dev.lizardbyte.sunshine/config/sunshine` but it neglects to update the file paths for the game cover images in `apps.json`.
All game cover images are missing after the migration.

### Expected Behavior

Sunshine either leaves the config files at their original location in `~./config` or it takes care to adapt the relevant file paths in `apps.json` while migrating. Better yet: for images stored in sunshine's config folder, it should probably use relative paths instead of absolute paths.

### Host Operating System

Linux

### Operating System Version

Ubuntu 22.04.4

### Architecture

64 bit

### Sunshine commit or version

0.23.1.8b21db64fb

### Package

Linux - flatpak

### GPU Type

AMD

### GPU Model

AMD RX6650XT

### GPU Driver/Mesa Version

mesa 23.3.6

### Capture Method (Linux Only)

X11

### Config

```Shell
address_family = both
min_log_level = 1
```

### Apps

```json
{
    "env": {
        "PATH": "$(PATH):$(HOME)\/.local\/bin"
    },
    "apps": [
        {
            "name": "Desktop",
            "image-path": "desktop.png"
        },
        {
            "name": "Steam Big Picture",
            "detached": [
                "setsid steam steam:\/\/open\/bigpicture"
            ],
            "image-path": "steam.png"
        },
        {
            "name": "Guacamelee! Super Turbo Championship Edition",
            "output": "",
            "cmd": "",
            "image-path": "\/home\/xxxxx\/.config\/sunshine\/covers\/igdb_8862.png",
            "detached": [
                "steam steam:\/\/rungameid\/275390"
            ]
        },
```

### Relevant log output

```shell
Warning: Couldn't find app image at path [/home/xxxxx/.config/sunshine/covers/igdb_xxxx.png]

(repeated for each entry in apps.json)
```

**Comment by ReenigneArcher** [comment]
Users should not put images inside the config directory...

**Comment by gschintgen** [comment]
Ah, right, I could have added that all cover images were saved at their default location by Sunshine's built-in cover search functionality. No image file was provided manually, neither did I edit `apps.json` manually.
