### ISSUE TITLE
Cannot install on Fedora 40

### ISSUE THREAD

**Issue by ultimategrandson** [LizardByte/Sunshine#2496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I updated to Fedora 40 and can no longer use Sunshine due to several dependency issues.

![image](https://github.com/LizardByte/Sunshine/assets/5469786/60d5b331-4453-41a3-8a6b-68c17826f7e0)

### Host Operating System

Linux

### Operating System Version

Fedora 40

### Architecture

64 bit

### Sunshine commit or version

latest

### Package

Linux - rpm

### GPU Type

Nvidia

### GPU Model

4070

### GPU Driver/Mesa Version

550

### Capture Method (Linux Only)

X11

### Config

```Shell
N/A
```

### Relevant log output

```shell
N/A
```

**Comment by ReenigneArcher** [comment]
We haven't created a Fedora 40 package yet. For now you can use this copr: https://copr.fedorainfracloud.org/coprs/matte-schwartz/sunshine/

**Comment by ultimategrandson** [comment]
Oh cool, didn't know about copr. 

Thanks
