### ISSUE TITLE
Sunshine blocks some applications Windows 10

### ISSUE THREAD

**Issue by DmitryPor** [LizardByte/Sunshine#2498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Windows 10. Sunshine blocks some applications (Agisoft Metashape, Topaz Labs, Houdini), nothing happens when I launch the application, but I see the application in the task manager. If you close Sunshine and start the application, it runs correctly.

### Host Operating System

Windows

### Operating System Version

10

### Architecture

64 bit

### Sunshine commit or version

0.23.1

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

2070

### GPU Driver/Mesa Version

552.22

### Config

```Shell
empty
```

### Relevant log output

```shell
empty
```

**Comment by ReenigneArcher** [comment]
No logs, closing. We use GitHub issues for actionable bug reports.
