### ISSUE TITLE
Cant access systray icon anymore with mouse after restarting Sunshine via systray icon

### ISSUE THREAD

**Issue by makedir** [LizardByte/Sunshine#2515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Connect to Sunshine. Click systray of Sunshine to restart. Connect again to Sunshine. Now you cant left right or double click anymore on the Sunshine systray icon, and nothing happens.

### Host Operating System

Windows

### Operating System Version

23h2

### Architecture

64 bit

### Sunshine commit or version

0.23.1

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

RTX4080

### GPU Driver/Mesa Version

552.22

### Config

```Shell
-
```

### Relevant log output

```shell
-
```

**Comment by ReenigneArcher** [comment]
Provide logs

**Comment by makedir** [comment]
No. Logs wont do anything for this issue.

**Comment by makedir** [comment]
Just happened again. Booted Sunshine host with Windows 11 auto login, connected via Moonlight, cant click on the Moonlight systray icon, nothing happens.

**Comment by suzikuo** [comment]
When I started using Moonlight streaming, the Sunshine right-click menu became invalid
After I closed the stream, the Sunshine right-click menu took effect.
But it's not a big deal.

**Comment by makedir** [comment]
Of course, like I said, this happening all the time and you cant access the systray anymore of Sunshine. No, it is a big issue. I want to be able to access it through the Moonlight stream obviously for restarting Sunshine for example.

**Comment by makedir** [comment]
Still happening.

**Comment by ReenigneArcher** [comment]
On beta?

**Comment by makedir** [comment]
I think the issue might be some old incompatible systray code, which is not fully compatible with Windows 11. The systray code was changed for Windows 11. I have systray issues with other older apps too which have not a proper systray menu.

**Comment by ReenigneArcher** [comment]
I repeat... On beta?
