### ISSUE TITLE
Framepacing issues under linux

### ISSUE THREAD

**Issue by adolfotregosa** [LizardByte/Sunshine#259]
### Describe the Bug

The feeling of motion in games is not fluid under linux.

I did the following experiment. Using sunshine for both windows and linux on the host, I recorded what is shown on the moonlight client with obs. 

Please download and watch the videos locally:

Arch Sunshine:
https://drive.google.com/file/d/1yE2qGHNKZpGGMNmSHkBt-1gVnw7a8v2T/view?usp=sharing

Windows Sunshine:
https://drive.google.com/file/d/1LLhAONqkWMERX52o2Exw1KNs4u5Q1RNi/view?usp=sharing

As you can hopefully focus on and see, the wind mill rotation under windows is really smooth but "stuttering" under linux, it really seams like some kind of frame pacing problem. Frame pacing option in moonlight does nothing for me.

Do you guys have any suggestions on how to fix this? Sunshine is using nvfbc screencast successfully.

thank you 

### Sunshine Host Operating System and Version

Arch

### Architecture

64bit

### Sunshine Version

0.14

### GPU Type

nvidia

### GPU Model

3060

### GPU Driver/Mesa Version

515.57

### Capture Method (Linux Only)

nvfbc

**Comment by KuleRucket** [comment]
Can't say I've noticed this with the same setup. I'll have to watch more closely for it. When are your settings for nv_preset, nv_rc and nv_coder?

I guess you only see this remotely and not when running on linux normally?

**Comment by adolfotregosa** [comment]
> Can't say I've noticed this with the same setup. I'll have to watch more closely for it. When are your settings for nv_preset, nv_rc and nv_coder?
> 
> I guess you only see this remotely and not when running on linux normally?

![image](https://user-images.githubusercontent.com/7437931/180458162-32a8737b-03df-4f8b-a901-60131b6bf312.png)

Yes, only remotely and only linux. If you download and play my videos locally it is really easy to see the difference. sunshine from windows is butter smooth, from linux it has that frame pacing jitters.

**Comment by N-Upchurch** [comment]
Can't see the vids (have to request access) but I also have bad stuttering on Linux (Manjaro) host (with AMD card).

**Comment by adolfotregosa** [comment]
> Can't see the vids (have to request access) but I also have bad stuttering on Linux (Manjaro) host (with AMD card).

Links should work now, sorry about that.

**Comment by adolfotregosa** [comment]
@ReenigneArcher , @KuleRucket could you have a look at the videos, please?

**Comment by KuleRucket** [comment]
I already did but I don't have anything else to add.

**Comment by entropicdrifter** [comment]
Try changing your preset from High Performance to one of the ll presets, either ll or llhp. LL in that context stands for low latency. High Performance is meant for encosing videos in general, not for streaming in particular. The low latency presets are designed for streaming so you get less stutter with them.

**Comment by adolfotregosa** [comment]
> Try changing your preset from High Performance to one of the ll presets, either ll or llhp. LL in that context stands for low latency. High Performance is meant for encoding videos in general, not for streaming in particular. The low latency presets are designed for streaming so you get less stutter with them.

Hi. I did try the LL profiles and it kinda does seam to help but it does not make it on par with windows

**Comment by Hekel1989** [comment]
Out of curiosity, has there been any progress on this? exact same situation as OP, and with Windows, on the exact same machine (dual boot), it's perfect.
I can't get rid of the stutter when the host is Linux

**Comment by gschintgen** [comment]
See also: #2286 and #2333

**Comment by shelterx** [comment]
Well, I have the same issue.
I have ran sunshine under Linux with both Nvidia and AMD GPUs, they both stutter in moonlight (running on Apple TV) but when I look at the game on the host computer, it's smooth.
