### ISSUE TITLE
Latest AppImage can't run on glibc 2.31 system

### ISSUE THREAD

**Issue by garywill** [LizardByte/Sunshine#2626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

- [X] This issue is present in the latest pre-release

### Describe the Bug

Since pre-release v2024.601.13612 it doesn't run on openSUSE 15.5 with glibc 2.31 (while v0.23.1 runs)

### Expected Behavior

Please use older linux distro to build AppImage

### Host Operating System

Linux

### Operating System Version

openSUSE 15.5

### Architecture

64 bit

### Sunshine commit or version

v2024.601.13612

### Package

Linux - AppImage

### GPU Type

n/a

### GPU Model

.

### GPU Driver/Mesa Version

.

### Config

```Shell
.
```

### Relevant log output

```shell
/tmp/.mount_sunshi1CYKZ1/usr/bin/sunshine: /lib64/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/.mount_sunshi1CYKZ1/usr/bin/sunshine)
/tmp/.mount_sunshi1CYKZ1/usr/bin/sunshine: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_sunshi1CYKZ1/usr/bin/sunshine)
/tmp/.mount_sunshi1CYKZ1/usr/bin/sunshine: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_sunshi1CYKZ1/usr/bin/sunshine)
/tmp/.mount_sunshi1CYKZ1/usr/bin/sunshine: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_sunshi1CYKZ1/usr/bin/../lib/libcurl.so.4)
/tmp/.mount_sunshi1CYKZ1/usr/bin/sunshine: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_sunshi1CYKZ1/usr/bin/../lib/libcurl.so.4)
/tmp/.mount_sunshi1CYKZ1/usr/bin/sunshine: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_sunshi1CYKZ1/usr/bin/../lib/libgtk-3.so.0)
/tmp/.mount_sunshi1CYKZ1/usr/bin/sunshine: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_sunshi1CYKZ1/usr/bin/../lib/libglib-2.0.so.0)
/tmp/.mount_sunshi1CYKZ1/usr/bin/sunshine: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_sunshi1CYKZ1/usr/bin/../lib/libglib-2.0.so.0)
......
```

**Comment by ReenigneArcher** [comment]
AppImage is now built with Ubuntu 22.04. That may break some compatibility. Building with 20.04 results in less performant ffmpeg, but mostly we moved to 22.04 in order to support compiling with C++20 which needs a newer version of boost than 20.04 supplies. Sorry for the inconvenience but this probably won't change back.

https://github.com/LizardByte/Sunshine/pull/2322
https://github.com/LizardByte/Sunshine/pull/2327
