### ISSUE TITLE
Sunshine portable, sunshine stop processing received input packets when open context menu by right click

### ISSUE THREAD

**Issue by xiakeng** [LizardByte/Sunshine#2630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

- [X] This issue is present in the latest pre-release

### Describe the Bug

for some complicated reason I need to use sunshine portable version, I run sunshine.exe as administrator manually

during stream, if I right click system tray icon to open some context menu, the input just freeze.
only input freeze, the screen still working.

when the input freeze I try to move mouse and hit keyboard, it generate log below
[sunshine.log](https://github.com/user-attachments/files/15526053/sunshine.log)
according to log sunshine host is still receiving keyboard packet and absolute mouse move packet, even the x&y of mouse position is changing, but it's not processing them

once I use parsec to stream and dismiss the context menu, stream on moonlight also unfreeze.

### Expected Behavior

it would be good if there is work around for the issue, without the need to unfreeze it using parsec or go to physical keyboard or mouse.

### Additional Context
Please note that only input freeze, If I play a video when reproduce the issue, the video still playing on the stream, only mouse and keyboard not working.
please note that not all context menu can trigger the freeze.
e.g. sunshine icon itself is ok, but parsec or nvidia panel, if I right click them the input just freeze

same freeze can also observe on UAC pop up. but this is acceptable I can disable the UAC directly.

this issue won;t happen on installer service version, it only happen on portable version

### Host Operating System

Windows

### Operating System Version

windows 11

### Architecture

64 bit

### Sunshine commit or version

v0.23.1

### Package

Windows - portable

### GPU Type

Nvidia

### GPU Model

GeForce 2060 super

### GPU Driver/Mesa Version

555.85

### Config

```Shell
min_log_level = 0
port = 46989
channels = 2
sunshine_name = HTPC
fec_percentage = 50
```

### Relevant log output

```shell
full log attached as file in description
```

**Comment by ReenigneArcher** [comment]
You can't capture UAC prompts, and probably a lot of other layers unless you use the service/installed version.

**Comment by xiakeng** [comment]
> You can't capture UAC prompts, and probably a lot of other layers unless you use the service/installed version.

I can accept that.
is there a way to make the service version stream target specific user?
currently service sunshine will stream whoever login first.

now I have 2 users logged via Aster, I want to stream specific user on demand.
this is why I need portable version.

currently I'm using parsec, but moonlight just have better experience.

**Comment by ReenigneArcher** [comment]
> is there a way to make the service version stream target specific user?

Not currently. PR welcome.
