### ISSUE TITLE
Sunshine web UI downloads too large size of logs repeatly on verbose log level

### ISSUE THREAD

**Issue by reallyimeric** [LizardByte/Sunshine#2645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

- [X] This issue is present in the latest pre-release

### Describe the Bug

Sunhine web UI repeatly (seems per 5 seconds?) requests logs on troubleshooting page, and if log level is set to verbose, this can be too much traffic even on LAN, and it slowed the web UI. In my case it produce a 110M logs during 30 seconds of streaming. I didn't send control but just watch during the 30s of streaming. I'm not sure if my hardware/encoding settings or something else are relevant.

### Expected Behavior

- Less traffic on troubleshooting page with verbose log level setting
- Web UI don't freeze when on trouble shooting page with verbose log level setting
- Incremental log fetching, paging, or some other solution to ease log loading issue on the trouble shooting page

### Additional Context

The web UI works fine on debug log level. I only noticed the large size of `/api/logs` http response on verbose level. 

### Host Operating System

Windows

### Operating System Version

22H2,19045.4412

### Architecture

64 bit

### Sunshine commit or version

v2024.607.215756

### Package

Windows - installer

### GPU Type

AMD

### GPU Model

Radeon RX 5700

### GPU Driver/Mesa Version

24.5.1

### Config

```Shell
locale = zh
lan_encryption_mode = 2
min_log_level = 0
wan_encryption_mode = 2
```

### Relevant log output

```shell
// It's just too large to paste... And I think it's not relevant to the topic.
```

**Comment by gschintgen** [comment]
Don't use verbose if it's too ... verbose.

If you *really* think it's necessary (most likely not!), leave the web ui closed and look directly at the actual log file.

**Comment by ReenigneArcher** [comment]
Verbose logging should only be used for troubleshooting purposes. In these cases it is recommended to enable verbose and manually open the log file.

Disable verbose when you are not troubleshooting.
