### ISSUE TITLE
macOS homebrew problem

### ISSUE THREAD

**Issue by kkllxxjg** [LizardByte/Sunshine#2655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

- [X] This issue is present in the latest pre-release

### Describe the Bug

<img width="697" alt="截屏2024-06-09 18 52 28" src="https://github.com/LizardByte/Sunshine/assets/131129837/0f62bee1-49f5-4574-8f1d-a118d92e4352">
macOS when installing homebrew, it shows that the c'ma'ke source cannot be found or for other reasons

### Host Operating System

macOS

### Operating System Version

12.7.5 (21H1222)

### Architecture

64 bit

### Sunshine commit or version

no

### Package

macOS - dmg

### GPU Type

Intel

### GPU Model

no

### GPU Driver/Mesa Version

no

### Config

```Shell
Sunshine has not been installed successfully
```

### Relevant log output

```shell
no
```

**Comment by ReenigneArcher** [comment]
This is a duplicate. You need to clear brew's cache.

**Comment by kkllxxjg** [comment]
Thank you. It has been resolved.
