### ISSUE TITLE
League of Legends - Can't move the mouse when loading game

### ISSUE THREAD

**Issue by s-thomas99** [LizardByte/Sunshine#2689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

- [X] This issue is present in the latest pre-release

### Describe the Bug

When you launch a game in League of Legends you can't move the mouse-coursur at all.
Any idea how to get it back to work?

### Expected Behavior

Mouse moves normaly

### Additional Context

Maybe there was a RIOT Vanguard updated that's the cause of this problem

### Host Operating System

Windows

### Operating System Version

Win 11 23H2

### Architecture

64 bit

### Sunshine commit or version

v0.23.1

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

RTX 3070

### GPU Driver/Mesa Version

555.99

### Config

```Shell
/
```

### Relevant log output

```shell
...
```

**Comment by ReenigneArcher** [comment]
Probably an anti-cheat blocking it. Nothing we can do about that.

**Comment by s-thomas99** [comment]
With Gamestreaming via Geforce Experience its working but not with Sunshine. Any idea why or how to fix it?
