### ISSUE TITLE
Virustotal shows 4 threats for windows installer and 2 threats for Portable (v0.23.1)

### ISSUE THREAD

**Issue by zexcster** [LizardByte/Sunshine#2777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

None

### Describe the Bug

Upload installer and "sunshine.exe" of the portable version (v0.23.1) to virustotal

it will show 4 threats  for the installer 

Bkav Pro
**W64.AIDetectMalware**

MaxSecure
**Win.MxResIcn.Heur.Gen**

Palo Alto Networks
**Generic.ml**

Trapmine
**Suspicious.low.ml.score**

and 2 threats for the portable version (sunshine.exe)

Bkav Pro
**W64.AIDetectMalware**

MaxSecure
**Win.MxResIcn.Heur.Gen**

### Expected Behavior

there should be not threats found

### Host Operating System

Windows

### Operating System Version

10

### Architecture

64 bit

### Sunshine commit or version

v0.23.1

### Package

n/a

### GPU Type

n/a

### GPU Model

na

### GPU Driver/Mesa Version

na

### Capture Method

None

### Config

```Shell
na
```

### Relevant log output

```shell
na
```

**Comment by ReenigneArcher** [comment]
This is normal with software that isn't popular. You can work with your antivirus software team to correct it, but they are false positives.
