### ISSUE TITLE
Couldn't spawn [..]: System: No such file or directory

### ISSUE THREAD

**Issue by sygi** [LizardByte/Sunshine#2802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

I'm too lazy to test

### Describe the Bug

I have a difficulty running a process after the connection. In my case, I'm trying to run `steam`, and I'm getting:

### Expected Behavior

To start steam.

### Additional Context

I tried:
1. adding `/usr/games` (where the binary is present) to PATH
2. changing working dir to `/usr/games`
3. Adding quotation marks to the command: `"\"steam steam:\/\/open\/gamepadui\""`
4. using the absolute path: `"\/usr\/games\/steam steam:\/\/open\/gamepadui"` as well as a local path.

### Host Operating System

Linux

### Operating System Version

Linux desktop 6.5.0-41-generic #41~22.04.2-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun  3 11:32:55 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Architecture

64 bit

### Sunshine commit or version

0.23.1.8b21db64fb8e8ffb9c24a412dbc66b7410699211

### Package

Linux - flatpak

### GPU Type

Nvidia

### GPU Model

irrelevant it seems, but 1070 Ti

### GPU Driver/Mesa Version

535.171.04

### Capture Method

X11 (Linux)

### Config

```Shell
it's empty?
```

### Apps

```json
{
    "env": {
        "PATH": "$(PATH):$(HOME)\/.local\/bin:\/usr\/games"
    },
    "apps": [
        {
            "name": "Desktop",
            "image-path": "desktop.png"
        },
        {
            "name": "Low Res Desktop",
            "image-path": "desktop.png",
            "prep-cmd": [
                {
                    "do": "xrandr --output HDMI-1 --mode 1920x1080",
                    "undo": "xrandr --output HDMI-1 --mode 1920x1200"
                }
            ]
        },
        {
            "name": "Steam Big Picture",
            "detached": [
                "\"steam steam:\/\/open\/gamepadui\""
            ],
            "image-path": "steam.png",
            "exclude-global-prep-cmd": "",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "working-dir": "\/usr\/games"
        }
    ]
}
```

### Relevant log output

```shell
Info: Spawning ["steam steam://open/gamepadui"] in ["/usr/games"]
[2024:07:04:12:11:23]: Warning: Couldn't spawn ["steam steam://open/gamepadui"]: System: No such file or directory
```

**Comment by ReenigneArcher** [comment]
steam is likely not in /usr/games ...

**Comment by sygi** [comment]
what do you mean:
```
$ which steam
/usr/games/steam
```
?

**Comment by sygi** [comment]
I dug a little bit deeper and realized that the issue is that flatpak has some sandboxing in place that prevents it from running steam (or anything else, really). I'm closing as this is not a sunshine issue, but a better UI (in particular no-steam app :) would be an improvement.
