### ISSUE TITLE
Error: Couldn't find any of the following libraries

### ISSUE THREAD

**Issue by ElYaiko** [LizardByte/Sunshine#2804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

None

### Describe the Bug

When starting sunshine in MacOS I get:
`Error: Couldn't find any of the following libraries: [libavahi-common.3.dylib, libavahi-common.dylib]`

### Expected Behavior

To start sunshine

### Additional Context

(UI starts ok)

### Host Operating System

macOS

### Operating System Version

MacOS Sonoma 14

### Architecture

arm

### Sunshine commit or version

0.23.1

### Package

macOS - Homebrew

### GPU Type

n/a

### GPU Model

M1

### GPU Driver/Mesa Version

M1

### Capture Method

AVCaptureScreen (macOS)

### Config

```Shell
(Default)
```

### Relevant log output

```shell
`Error: Couldn't find any of the following libraries: [libavahi-common.3.dylib, libavahi-common.dylib]`
```

**Comment by ReenigneArcher** [comment]
The error message indicates the code is working properly.

I believe the only downside of this is you would need to manually enter the IP address in Moonlight. Also, closing this since avahi will no longer be used on macOS after #2786 is merged.
