### ISSUE TITLE
[LINUX] ArchLinux. Connections don't terminate after close the steam apps

### ISSUE THREAD

**Issue by sh0ra1t** [LizardByte/Sunshine#2805]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your issue described in the documentation?

- [x] I have read the documentation

### Is your issue present in the latest beta/pre-release?

None

### Describe the Bug

The clients are able to join and play however after terminate one game the connection continue and they are able to navigate through the desktop. The timeout isn't working.

### Expected Behavior

I need always to "Force Close" to kick the clients.

### Host Operating System

Linux

### Operating System Version

Arch Linux

### Architecture

64 bit

### Sunshine commit or version

0.23.1

### Package

Linux - AUR (Third Party)

### GPU Type

AMD

### GPU Model

7900xtx

### GPU Driver/Mesa Version

vulkan

### Capture Method

X11 (Linux)

### Config

```Shell
min_log_level = 0
```

### Apps

```json
{
    "env": {
        "PATH": "$(PATH):$(HOME)\/.local\/bin"
    },
    "apps": [
        {
            "name": "Desktop",
            "image-path": "desktop.png"
        },
        {
            "name": "Low Res Desktop",
            "image-path": "desktop.png",
            "prep-cmd": [
                {
                    "do": "xrandr --output HDMI-1 --mode 1920x1080",
                    "undo": "xrandr --output HDMI-1 --mode 1920x1200"
                }
            ]
        },
        {
            "name": "Steam Big Picture",
            "detached": [
                "setsid steam steam:\/\/open\/bigpicture"
            ],
            "image-path": "steam.png",
            "exclude-global-prep-cmd": "",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5"
        },
        {
            "name": "Command and Conquer Generals",
            "output": "",
            "cmd": "setsid steam steam:\/\/rungameid\/2229870",
            "exclude-global-prep-cmd": "false",
            "elevated": "false",
            "auto-detach": "false",
            "wait-all": "false",
            "exit-timeout": "0",
            "image-path": "",
            "prep-cmd": [
                {
                    "do": "",
                    "undo": ""
                }
            ]
        }

```

### Relevant log output

```shell
Nothing special.
I created a curl command to kill the connection but its not the right way to do it.
```

**Comment by ReenigneArcher** [comment]
Detached commands do not terminate when the stream ends, and Sunshine does not keep track of detached processes.

**Comment by sh0ra1t** [comment]
What you mean ? Isn't suppose to terminate the stream after launching one game? Even moonshine have that settings into the applications path.

**Comment by ReenigneArcher** [comment]
Thumbs down all you want, but this is not a bug.

"detached" commands, like `steam` are run and forgetting about. We don't track them. https://docs.lizardbyte.dev/projects/sunshine/en/latest/about/setup.html#application-list

**Comment by sh0ra1t** [comment]
It's not strictly about detached commands. It also don't work in non detached "Commands".

**Comment by gardebreak** [comment]
I'm seeing the same behavior.

@ReenigneArcher  just to clarify, when running a Steam game by setting the "Command" (not Detached Command) to a Steam URI (i.e. `setsid steam steam://rungameid/397540`), it's actually still running as a Detached Command and thus won't terminate the stream when exiting the game?

**Comment by ReenigneArcher** [comment]
Yes if you have auto detach on, otherwise the command would probably fail altogether.
