### ISSUE TITLE
Cannot compile on windows - fatal error: winrt/Windows.Graphics.Capture.h: No such file or directory

### ISSUE THREAD

**Issue by chunsun21** [LizardByte/Sunshine#2823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

None

### Describe the Bug

I've tried build.

But, there were some errors with windows graphics capture code.

[ 62%] Building CXX object CMakeFiles/sunshine.dir/src/platform/windows/display_ram.cpp.obj
In file included from C:\msys64\test\sunshine\src\platform\windows\display_vram.cpp:15:
C:\msys64\test\sunshine\src\platform\windows\display.h:15:10: fatal error: winrt/Windows.Graphics.Capture.h: No such file or directory
   15 | #include In file included from C:\msys64\test\sunshine\src\platform\windows\display_ram.cpp:5:
C:\msys64\test\sunshine\src\platform\windows\display.h:15:10: fatal error: winrt/Windows.Graphics.Capture.h: No such file or directory
   15 | #include <winrt/Windows.Graphics.Capture.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
<winrt/Windows.Graphics.Capture.h>
      |          mingw32-make[2]: *** [CMakeFiles\sunshine.dir\build.make:516: CMakeFiles/sunshine.dir/src/platform/windows/display_ram.cpp.obj] Error 1
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~mingw32-make[2]: *** Waiting for unfinished jobs....

compilation terminated.
[ 63%] Building CXmingw32-make[2]: *** [CMakeFiles\sunshine.dir\build.make:501: CMakeFiles/sunshine.dir/src/platform/windows/display_vram.cpp.obj] Error 1
X object tests/CMakeFiles/test_sunshine.dir/__/src/confighttp.cpp.obj
[ 64%] Building CXX object tests/CMakeFiles/test_sunshine.dir/__/src/rtsp.cpp.obj
[ 65%] Building CXX object tests/CMakeFiles/test_sunshine.dir/__/src/stream.cpp.obj
In file included from C:\msys64\test\sunshine\src\platform\windows\display_base.cpp:15:
C:\msys64\test\sunshine\src\platform\windows\display.h:15:10: fatal error: winrt/Windows.Graphics.Capture.h: No such file or directory
   15 | #include <winrt/Windows.Graphics.Capture.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
mingw32-make[2]: *** [CMakeFiles\sunshine.dir\build.make:486: CMakeFiles/sunshine.dir/src/platform/windows/display_base.cpp.obj] Error 1
[ 65%] Building CXX object tests/CMakeFiles/test_sunshine.dir/__/src/video.cpp.obj
mingw32-make[1]: *** [CMakeFiles\Makefile2:232: CMakeFiles/sunshine.dir/all] Error 2
mingw32-make[1]: *** Waiting for unfinished jobs....
[ 66%] Building CXX object tests/CMakeFiles/test_sunshine.dir/__/src/video_colorspace.cpp.obj
[ 67%] Building CXX object tests/CMakeFiles/test_sunshine.dir/__/src/input.cpp.obj
[ 68%] Building CXX object tests/CMakeFiles/test_sunshine.dir/__/src/audio.cpp.obj
[ 69%] Building CXX object tests/CMakeFiles/test_sunshine.dir/__/src/process.cpp.obj
[ 69%] Building CXX object tests/CMakeFiles/test_sunshine.dir/__/src/network.cpp.obj
[ 70%] Building CXX object tests/CMakeFiles/test_sunshine.dir/__/src/system_tray.cpp.obj
[ 71%] Building CXX object tests/CMakeFiles/test_sunshine.dir/__/src/stat_trackers.cpp.obj
[ 72%] Building RC object tests/CMakeFiles/test_sunshine.dir/__/windows.rc.obj
[ 73%] Building CXX object tests/CMakeFiles/test_sunshine.dir/__/src/platform/windows/publish.cpp.obj
[ 73%] Building CXX object tests[/ C7M4a%k]e FiBlueisl/dtiensgt _CsXuXn sohbijneec.td itre/s_t_s//sCrMca/kpelFaitlfeosr/mt/ewsitn_dsouwnss/hmiinsec..dciprp/._o_b/js
rc/platform/windows/input.cpp.obj
[ 75%] Building CXX object tests/CMakeFiles/test_sunshine.dir/__/src/platform/windows/display_base.cpp.obj
[ 76%] Building CXX object tests/CMakeFiles/test_sunshine.dir/__/src/platform/windows/display_vram.cpp.obj
[ 77%] Building CXX object tests/CMakeFiles/test_sunshine.dir/__/src/platform/windows/display_ram.cpp.obj
In file included from C:\msys64\test\sunshine\src\platform\windows\display_vram.cpp:15:
C:\msys64\test\sunshine\src\platform\windows\display.h:15:10: fatal error: winrt/Windows.Graphics.Capture.h: No such file or directory
   15 | #include <winrt/Windows.Graphics.Capture.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from C:\msys64\test\sunshine\src\platform\windows\display_base.cpp:15:
C:\msys64\test\sunshine\src\platform\windows\display.h:15:10: fatal error: winrt/Windows.Graphics.Capture.h: No such file or directory
   15 | #include <winrt/Windows.Graphics.Capture.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from C:\msys64\test\sunshine\src\platform\windows\display_ram.cpp:5:
C:\msys64\test\sunshine\src\platform\windows\display.h:15:10: fatal error: winrt/Windows.Graphics.Capture.h: No such file or directory
   15 | #include <winrt/Windows.Graphics.Capture.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

### Host Operating System

Windows

### Operating System Version

Windows 11

### Architecture

64 bit

### Sunshine commit or version

master branch

### Package

Windows - portable

### GPU Type

Nvidia

### GPU Model

RTX 3090

### GPU Driver/Mesa Version

555.99

### Capture Method

None

### Config

```Shell
no config
```

### Relevant log output

```shell
no log
```

**Comment by cdjzzzz** [comment]
same error， though .i have install package -  mingw-w64-ucrt-x86_64-cppwinrt, but error remains.

**Comment by chunsun21** [comment]
Everything compiles and builds just fine when using MSYS2 UCRT64. The documentation really needs to be updated.

**Comment by chunsun21** [comment]
Everything compiles and builds just fine when using MSYS2 UCRT64. The documentation really needs to be updated.

**Comment by cdjzzzz** [comment]
Yeah,  using MSYS2 UCRT64 everything compiles , but one more thing, if you compiled with using MSYS2 MinGW, you must remove the build file first.

**Comment by ReenigneArcher** [comment]
Look at "master" docs instead of "latest". Latest points to the last stable.
