### ISSUE TITLE
Sunshine crash and reboot with Action!

### ISSUE THREAD

**Issue by matr0nix** [LizardByte/Sunshine#2836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

Hi

Sunshine is crashing and reboot if Action! (an app for record gameplay, by mirillis) is launched.

In action's parameters, process exclusion > add sunshine.exe

No crash now

### Host Operating System

Windows

### Operating System Version

11

### Architecture

64 bit

### Sunshine commit or version

v2024.710.151651

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

4070 super

### GPU Driver/Mesa Version

last

### Capture Method

None

### Config

```Shell
x
```

### Relevant log output

```shell
x
```

**Comment by ReenigneArcher** [comment]
I believe only one app can access the screen capture API at the same time. This is a windows limitation.

**Comment by matr0nix** [comment]
No it's a bug, with the exclusion I can capture gameplay without any pb, and stream with sunshine.
