### ISSUE TITLE
Nircmd commands fail

### ISSUE THREAD

**Issue by Sidelity** [LizardByte/Sunshine#2872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

I'm trying to use Nircmd to move the cursor to the edge of the screen when stream starts. However, it seems nircmd commands fail with an error code (which turned up no relevant search results), and stops the stream.

If I try to just launch nircmd with `path\to\nircmd\nircmdc` under Sunshine's command preparations, the stream successfully launches. But as soon as I add the `movecursor` command, nircmd fails to start and so does the stream. I also tried another command, `setdisplay`, and it also fails. I've tried running the command as elevated, but it still doesn't work. I can run `nircmdc movecursor 10000 10000` from both cmd and powershell, with both my regular user and as admin. Also, I've set up the game launcher Playnite to use nircmd commands, and it works perfectly. So as far as I know it's just Sunshine that has problems running nirmcd. 

### Host Operating System

Windows

### Operating System Version

22H2

### Architecture

64 bit

### Sunshine commit or version

v0.23.1

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

GTX 1660 Ti

### GPU Driver/Mesa Version

556.12

### Capture Method

None

### Config

```Shell
global_prep_cmd = [{"do":"D:\\Portable\\nircmd\\nircmdc movecursor 10000 10000","undo":"","elevated":"true"}]
min_log_level = 1
```

### Relevant log output

```shell
Debug: Parsed target [D:\Portable\nircmd\nircmdc] from command [D:\Portable\nircmd\nircmdc movecursor 10000 10000]
Debug: Resolved target [D:\Portable\nircmd\nircmdc] to path ["D:\Portable\nircmd\nircmdc"]
Info: Executing Do Cmd: [D:\Portable\nircmd\nircmdc movecursor 10000 10000]
Info: D:\Portable\nircmd\nircmdc movecursor 10000 10000 running with PID 15412
Error: [D:\Portable\nircmd\nircmdc movecursor 10000 10000] failed with code [1073757860]
```

**Comment by ReenigneArcher** [comment]
`nircmdc` is not part of Sunshine. You will need to troubleshoot this elsewhere.

**Comment by Sidelity** [comment]
For anyone with the same problem: it seems `nircmd` exits with a code even when run successfully. Sunshine interprets this as a crash, and cancels the stream.

A workaround is to run `nircmd` from a .bat file, with the final line being something that Sunshine doesn't interpret as a crash, e.g.:

```
@echo off
D:\Portable\nircmd\nircmdc movecursor 10000 10000
echo done
```
