### ISSUE TITLE
Settings disappeared in v2024.730.191523

### ISSUE THREAD

**Issue by profucius** [LizardByte/Sunshine#2941]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

After updating to v2024.730.191523, the dashboard no longer shows the settings tabs. See screenshot below.

![image](https://github.com/user-attachments/assets/340e1529-e593-4118-9242-aa3688272168)

### Host Operating System

Windows

### Operating System Version

Windows 11

### Architecture

64 bit

### Sunshine commit or version

v2024.730.191523

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

3080

### GPU Driver/Mesa Version

Latest

### Capture Method

None

### Config

```Shell
key_rightalt_to_key_win = enabled
qsv_coder = cavlc
min_log_level = 5
encoder = nvenc
min_threads = 1
channels = 3
notify_pre_releases = enabled
fps = [30,60,90]
qsv_preset = fast
nv_preset = p3
upnp = enabled
resolutions = [
    1920x1080,
    3860x2160,
    2560x1536
]
nv_coder = cavlc
nv_rc = vbr
```

### Relevant log output

```shell
.
```

**Comment by ReenigneArcher** [comment]
Nothing has changed in that regard.

![image](https://github.com/user-attachments/assets/05c41a0f-5aaa-4258-8e28-f2062c8725b8)

![image](https://github.com/user-attachments/assets/87151882-a813-451a-810a-ec62ff577d05)


Share your browser logs...

**Comment by profucius** [comment]
I downloaded another browser and it worked. It's fine now we can close this. Thanks
