### ISSUE TITLE
VR headset streaming support?

### ISSUE THREAD

**Issue by comsyspro** [LizardByte/Sunshine#2943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

None

### Describe the Bug

Would it be possible to stream a VR videostream from a VR application and view it on the client side with a VR headset?
Can you grab the videostream transfered by sunshine somehow with a python script or ffplay (from ffmpeg) so you can split this videostream for the left and right eye in the VR headset?

Could this be a starting point?
And can you grab a sunshine stream with ffplay or cv2 and what would be the right command and rtsp url?

```
import cv2
import openvr

def initialize_vr():
    openvr.init(openvr.VRApplication_Scene)
    vr_system = openvr.VRSystem()
    return vr_system

def shutdown_vr():
    openvr.shutdown()

def main():
    # RTSP Stream URL (is it possible to grab a sunshine stream like that?)
    rtsp_url = "rtsp://username:password@ip_address:port/path"

    # Connect to the RTSP stream
    cap = cv2.VideoCapture(rtsp_url)
    if not cap.isOpened():
        print("Error opening RTSP stream")
        return

    vr_system = initialize_vr()

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            print("Error reading frame")
            break

        # Display the frame (optional for checking)
        cv2.imshow('RTSP Stream', frame)

        # Send the frame to the VR headset
        # You need to insert your VR rendering logic here, such as rendering the frame as a texture
        # This is a placeholder, as the actual implementation depends on the VR headset and VR library

        # Wait for the 'q' key to be pressed to exit
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    # Release the capture objects and close the windows
    cap.release()
    cv2.destroyAllWindows()
    shutdown_vr()

if __name__ == "__main__":
    main()
```

### Host Operating System

Windows

### Operating System Version

Windows 10 / 11

### Architecture

64 bit

### Sunshine commit or version

0.23.1

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

RTX 3070

### GPU Driver/Mesa Version

latest

### Capture Method

None

### Config

```Shell
default
```

### Relevant log output

```shell
default
```

**Comment by TacoCake** [comment]
Just use ALVR at this point, it's made for it

**Comment by comsyspro** [comment]
Can I use ALVR for every VR application or is this only in combination for Steam VR? I want to have a universal solution which works with all kind of VR applications. Also the professional VR headsets do have cables (and do not have a wireless connection) and for these VR headsets I think you can't use ALVR, or can you? So my question is how you can get the sunshine stream in realtime to a VR headset, which is locally connected on the client side (with ffplay or other method)?

**Comment by ReenigneArcher** [comment]
![image](https://github.com/user-attachments/assets/d69edcf1-d223-4fc0-87a9-6817771aa843)
