### ISSUE TITLE
Key combination issue

### ISSUE THREAD

**Issue by rayhere** [LizardByte/Sunshine#3004]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

None

### Describe the Bug

The key combination S + J + 2 does not work, but S + J + 1 does work.

### Expected Behavior

open notepad, hold s, then hold j, then hold 1, it stop at 1 (work)
hold s, then hold j, then hold 2, it don't have  2, input j is keeep going (don't work)
for game, wasd, + ijkl, with number key, it will have problem.

windows 10 is streaming, using moonlight on macos.

### Host Operating System

Windows

### Operating System Version

windows 10 22H2

### Architecture

64 bit

### Sunshine commit or version

Version v0.23.1

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

RTX 3070

### GPU Driver/Mesa Version

560,70

### Capture Method

None

### Config

```Shell
channels = 6
min_log_level = 6
amd_quality = speed
upnp = enabled
```

### Relevant log output

```shell
N/A
```

**Comment by gschintgen** [comment]
This sounds like a limitation of your physical keyboard: https://en.m.wikipedia.org/wiki/Key_rollover (in particular the jamming part).

**Comment by rayhere** [comment]
> This sounds like a limitation of your physical keyboard: https://en.m.wikipedia.org/wiki/Key_rollover (in particular the jamming part).
I do online key rollover test on a MacBook Air M1. The problem that appears on a MacBook Air M1 (13.6.9) seems to be related to key rollover.

https://www.mechanical-keyboard.org/key-rollover-test/

Seems like a good idea to **test MacBook key combinations before making a purchase**, and the MacBook Air M1 doesn’t seem like a good choice for gaming.
