### ISSUE TITLE
Command can't take parameters

### ISSUE THREAD

**Issue by Atemu** [LizardByte/Sunshine#301]
### Describe the Bug

I'm trying to get Sunshine to end the session when Steam BPM is closed. In order to do that I entered `D:\Path\To\steam.exe steam://open/bigpicture` in the command field instead of the detached commands.

When I try to launch it though, the log says that it can't find the file.

Is it trying to open the file `"D:\Path\To\steam.exe steam://open/bigpicture"` as a path with space in it perhaps?

### Sunshine Host Operating System and Version

Windows 10

### Architecture

x86_64

### Sunshine Version

v0.14.0

### GPU Type

Nvidia

### GPU Model

1060 6GB

### GPU Driver/Mesa Version

Not relevant

**Comment by ReenigneArcher** [comment]
That's the wrong command.

`"your steam location/steam.exe" -bigpicture`

Also, this type of thing should not be created as a bug report.
