### ISSUE TITLE
Windows set to Japanese system locale results in bad installations

### ISSUE THREAD

**Issue by Dood345** [LizardByte/Sunshine#3063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

Installation while under Windows Japanese locale will cause application to fail to launch.
![image](https://github.com/user-attachments/assets/a5ec62ca-c61c-44f8-acf6-af547a2f3025)

### Expected Behavior

After installation with your locale Japanese the application will launch but fail then repeat this until you shut off your computer. Giving the command to sunshine to restart or quit does nothing to affect this loop.

### Host Operating System

Windows

### Operating System Version

Windows 11 23H2

### Architecture

64 bit

### Sunshine commit or version

23.1

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

NVIDIA 2070

### GPU Driver/Mesa Version

560.94

### Capture Method

None

### Config

```Shell
adapter_name = NVIDIA 2070
resolutions = [
    1280x720,
    1920x1080,
    2560x1440,
    3840x2160
]
fps = [30,60,90]
```

### Apps

```json
{
  "env": {},
  "apps": [
    {
      "name": "Desktop",
      "image-path": "desktop.png"
    },
    {
      "name": "Steam Big Picture",
      "cmd": "steam://open/bigpicture",
      "auto-detach": "true",
      "wait-all": "true",
      "image-path": "steam.png"
    }
  ]
}
```

### Relevant log output

```shell
I lost the log but this issue is easily repeatable and I am lazy, please forgive me and just be aware that non-unicode regional settings result in difficulties installing.
```

**Comment by Dood345** [comment]
Issue can be resolved by uninstalling Sunshine, changing system locale, then re-installing, may result in loss of configuration, app, and log files.

**Comment by ReenigneArcher** [comment]
Please do the following:

1. Test the latest pre-release and if the issue is present there, update the version number in your issue, otherwise let us know the issue is not present in the pre-release.
2. Disable the service and start Sunshine manually, then provide the logs. They will help us determine where the code is crashing.
