### ISSUE TITLE
Input doesnt register on mac during sleep

### ISSUE THREAD

**Issue by TheKidThatCodes** [LizardByte/Sunshine#3170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

if the mac goes to sleep, clicks no longer register, but the mouse can still be moved

### Expected Behavior

clicking wakes the mac up, or clicks work during sleep

### Additional Context

maybe the mac locks during sleep?

### Host Operating System

macOS

### Operating System Version

m2 pro macmini os 14.5

### Architecture

64 bit

### Sunshine commit or version

v2024.910.123325

### Package

other (not listed)

### GPU Type

Apple Silicon

### GPU Model

m2 pro

### GPU Driver/Mesa Version

tf

### Capture Method

None

### Config

```Shell
nothing there
```

### Relevant log output

```shell
no output
```

**Comment by ReenigneArcher** [comment]
A virtual mouse cannot wake up a computer.
