### ISSUE TITLE
Falls to low resolution 

### ISSUE THREAD

**Issue by skunk-funk** [LizardByte/Sunshine#3181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

After playing a while, after a network hiccup if I were to speculate, the resolution takes a dump. It does not recover until you quit the stream and re-engage. 

### Expected Behavior

Stream should recover to correct resolution. 

### Host Operating System

Linux

### Operating System Version

Arch

### Architecture

64 bit

### Sunshine commit or version

v2024.910.123325

### Package

Linux - flatpak

### GPU Type

AMD

### GPU Model

rx580

### GPU Driver/Mesa Version

amdgpu

### Capture Method

None

### Config

```Shell
Default
```

### Relevant log output

```shell
Can provide more if needed
```

**Comment by skunk-funk** [comment]
Didn't realize I was not on the latest beta build.

Attempting to test on Steam Deck client - having some issues getting that to work right for some reason. Please hold on anything until I post that I've finished testing

**Comment by skunk-funk** [comment]
This is fixed in the latest beta build

**Comment by skunk-funk** [comment]
Scratch that, it is still a problem in the latest beta. I had a bit less issue - takes longer to become a problem.

**Comment by skunk-funk** [comment]
I tested this with bg3 with both the amd dGPU and the intel iGPU. Using the iGPU (i5-8600k) it occasionally degraded to low resolution, but quickly recovered to look pretty good.

The AMD GPU degrades, and never recovers to an acceptable resolution until you quit out of moonlight and restart the stream.

There are no vaapi errors in the log with the iGPU.

**Comment by skunk-funk** [comment]
Apparently the same issue as this - I don't know how to merge them - https://github.com/LizardByte/Sunshine/issues/2948

**Comment by ReenigneArcher** [comment]
@skunk-funk thanks for the extra information. I can close this one. And you can add any relevant details to the other one.
