### ISSUE TITLE
WebUI login: use POST auth to support password managers

### ISSUE THREAD

**Issue by martijneken** [LizardByte/Sunshine#3220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

I'm too lazy to test

### Describe the Bug

Authentication to the Web UI works via:
https://en.wikipedia.org/wiki/Basic_access_authentication

This is not supported by some password managers, like Chrome's:
https://medium.com/@lmakarov/say-goodbye-to-urls-with-embedded-credentials-b051f6c7b6a3

Usually when I need the web UI it's because I am debugging things within a streaming session, without a keyboard, so a password manager would be very helpful to get to the UI in one click.

The password change page (/password) already supports a form that's compatible with password managers. Could we use that for the main Sunshine login too?

---
P.S. Alternatively I could encode the creds in a bookmark, e.g.
https://user:pass@ip:port/

But when using this method the home page fails to load with a JS error:
```
Hello, Sunshine!
_plugin-vue_export-helper-fe085d29.js:57 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': Request cannot be constructed from a URL that includes credentials: /api/configLocale
    at p0 (_plugin-vue_export-helper-fe085d29.js:57:52788)
    at index-1d511c0f.js:1:2015
```

A reload does fix it (no auth popup), so this is a fair workaround.

### Host Operating System

Windows

### Operating System Version

Windows 11 Pro -- build 22631.4169

### Architecture

64 bit

### Sunshine commit or version

v0.23.1

### Package

Linux - AppImage

### GPU Type

Nvidia

### GPU Model

GeForce RTX 3070

### GPU Driver/Mesa Version

560.94

### Capture Method

None

### Config

```Shell
resolutions = [
    1920x1080,
    2560x1080,
    2560x1440,
    3440x1440,
    1920x1200,
    3840x2160,
    3840x1600,
    1280x720
]
always_send_scancodes = disabled
gamepad = x360
```

### Relevant log output

```shell
n/a
```

**Comment by ReenigneArcher** [comment]
We use GitHub issues for bug reports, not feature requests.

With that said, there is already work being done to improve this. https://github.com/LizardByte/Sunshine/pull/2995
