### ISSUE TITLE
Your Discord forums are inaccessable. 

### ISSUE THREAD

**Issue by MichaelLudeo** [LizardByte/Sunshine#3221]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Is your issue described in the documentation?

- [ ] I have read the documentation

### Is your issue present in the latest beta/pre-release?

None

### Describe the Bug

Hi. 
Sorry for posting it here but I found no other way to reach the devs of this project. I signed into the project's support Discord, but any channel  I am trying to access in order to ask questions produces error:

> Error loading forum posts
> We are currently connecting to Discord, please try again in a moment. GraphQL error: We are currently connecting to Discord, please try again in a moment.

Could you take a look at this issue?

Thanks.

### Host Operating System

other, n/a

### Operating System Version

Windows

### Architecture

64 bit

### Sunshine commit or version

N/A

### Package

n/a

### GPU Type

n/a

### GPU Model

N/A

### GPU Driver/Mesa Version

N/A

### Capture Method

None

### Config

```Shell
N/A
```

### Relevant log output

```shell
N/A
```

**Comment by ReenigneArcher** [comment]
If you're using the widget bot, this can happen periodically due to api limitations. You can use an official discord app and everything should work.

**Comment by MichaelLudeo** [comment]
I was able to get into your discord but you don't allow asking questions.

**Comment by ReenigneArcher** [comment]
You have to wait 10 minutes
