### ISSUE TITLE
Is AppImage support dropped?

### ISSUE THREAD

**Issue by Rikitik** [LizardByte/Sunshine#3222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

There is no appimage for v2024.922.10353
Was support for this format dropped?

### Expected Behavior

An Appmiage for the latest build v2024.922.10353

### Additional Context

It does exist for the previous build v2024.921.45031

### Host Operating System

Linux

### Operating System Version

Fedora

### Architecture

32 bit

### Sunshine commit or version

v2024.922.10353

### Package

Linux - AppImage

### GPU Type

n/a

### GPU Model

N/A

### GPU Driver/Mesa Version

N/A

### Capture Method

None

### Config

```Shell
N/A
```

### Relevant log output

```shell
N/A
```

**Comment by ReenigneArcher** [comment]
No, there are just intermittent build issues with the runner running out of space.
