### ISSUE TITLE
Can't start if $HOME/.config/sunshine folder doesn't exists

### ISSUE THREAD

**Issue by Gr3q** [LizardByte/Sunshine#324]
### Describe the Bug

Running Sunshine the first time will result in an error.

The problem is that `/home/gr3q/.config/sunshine/` folder doesn't exist, so it fails to copy the config. Manually creating the folder solves the issue.

### Expected Behavior

it should create the folders in the path if they don't exist and then copy the config.

### Host Operating System

Linux

### Operating System Version

Arch Linux

### Architecture

64

### Sunshine Version

0.14.1

### GPU Type

AMD

### GPU Model

RX 580

### GPU Driver/Mesa Version

mesa 22.1.4-1

### Relevant log output

```Shell
~> sunshine 
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot copy file: No such file or directory [/usr/share/sunshine/config/sunshine.conf] [/home/gr3q/.config/sunshine/sunshine.conf]
fish: Job 1, 'sunshine' terminated by signal SIGABRT (Abort)
```

**Comment by ReenigneArcher** [comment]
Thanks for the report.

**Comment by Crystal4276** [comment]
Hi,

Same issue here on Arch + lightdm + Cinnamon.
I'm using the AUR package

**Comment by ReenigneArcher** [comment]
I've replicated the issue.
