### ISSUE TITLE
NVENC Intra Refresh

### ISSUE THREAD

**Issue by woiza** [LizardByte/Sunshine#3323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

Compression artifacts forming when left on the same scene for a while:

[Moonlight Xbox Issue](https://github.com/TheElixZammuto/moonlight-xbox/issues/117)

### Expected Behavior

No artifacts

### Additional Context

Could you please allow NVENC intra refresh? Maybe as a configuration option in the UI (not sure if this is possible though).

Something like this:

[NVENC intra refresh diff](https://github.com/LizardByte/Sunshine/compare/master...TheElixZammuto:Sunshine-1:nvenc-add-intra-refresh)

If I understand it correctly, then intra refresh is recommended for game streaming:

[Nvidia recommended NVENC settings ](https://docs.nvidia.com/video-technologies/video-codec-sdk/12.0/nvenc-video-encoder-api-prog-guide/index.html#recommended-nvenc-settings)

[Nvidia Intra Refresh](https://docs.nvidia.com/video-technologies/video-codec-sdk/12.0/nvenc-video-encoder-api-prog-guide/index.html#error-resiliency-features__section_klf_nr1_nlb)

### Host Operating System

Windows

### Operating System Version

Win 11

### Architecture

amd64/x86_64

### Sunshine commit or version

latest

### Package

n/a

### GPU Type

Nvidia

### GPU Model

all supported NVIDIA GPUs

### GPU Driver/Mesa Version

all supported NVIDIA drivers

### Capture Method

None

### Relevant log output

```shell
n/a
```

**Comment by cgutman** [comment]
Intra-refresh isn't relevant for us because we do not request periodic intra frames. We only request a key frame when a frame is lost, and we do really need the full key frame at that point rather than a slice of intra-coded blocks.
