### ISSUE TITLE
Windows service started as SYSTEM user.

### ISSUE THREAD

**Issue by Pival81** [LizardByte/Sunshine#333]
### Describe the Bug

I installed the service through the install-service.bat script, and it seemed to work fine until I started Spider-Man Remastered, where it crashed due to being run as the SYSTEM user. (I assume that's the problem, but either way it showed up as being run with that user and that's troublesome enough, I don't want my games to have that kind of access to my system).

I also tried to make the service run with my local user, but it wouldn't even start. Of course everything works as intended if I start Sunshine normally through the start menu.

### Host Operating System

Windows

### Operating System Version

11

### Architecture

64bit

### Sunshine Version

0.14.1

### GPU Type

AMD

### GPU Model

Reference 6800 xt

### GPU Driver/Mesa Version

30.0.21023.1015

**Comment by ReenigneArcher** [comment]
It's intentional to run as administrator / system account, in order to capture the login screen and elevation prompts. If you don't want to run as admin, then don't setup the service, and just use a scheduled task instead.
