### ISSUE TITLE
Broken Discord support link

### ISSUE THREAD

**Issue by fragtion** [LizardByte/Sunshine#336]
### Describe the Bug

The link for discord questions @ https://github.com/LizardByte/Sunshine/issues/new/choose, is not working

### Expected Behavior

Should open discord to the correct server

### Operating System Version

11

### Architecture

not really relevant

### Sunshine Version

not really relevant

### GPU Type

not really relevant

### GPU Model

not really relevant

### GPU Driver/Mesa Version

not really relevant

**Comment by ReenigneArcher** [comment]
Thanks z this is a duplicate, so closing.
