### ISSUE TITLE
Detached Processes launched by sunshine end up as zombies on linux after closing them

### ISSUE THREAD

**Issue by MNarath1** [LizardByte/Sunshine#3378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

When you start applications on a linux host with sunshine trough detached command with setsid like setsid steam or setsid gamescope -e -- steam steam://open/bigpicture it will not be truely detached from the parent process meaning when you try to stop the application launched by sunshine it will leave a zombie process that will keep using up pid's until you stop sunshine or restart your pc.

### Expected Behavior

Launching an application detached from the parent process should actually detach it and not keep it in a semi attached state were it then just doesn't get a response by the parent process when it tries to die (that results in a zombie process).

### Additional Context

Either something has to change how detached commands work or the parent has to actually allow the child process to die instead of leaving it in a limbo.

### Host Operating System

Linux

### Operating System Version

Fedora 41 KDE

### Architecture

amd64/x86_64

### Sunshine commit or version

v2024.1107.45727

### Package

Linux - Fedora Copr

### GPU Type

Nvidia

### GPU Model

Nividia RTX2070 Super

### GPU Driver/Mesa Version

565.57.01

### Capture Method

None

### Apps

```json
{
    "env": {
        "PATH": "$(PATH):$(HOME)\/.local\/bin"
    },
    "apps": [
        {
            "name": "Desktop",
            "image-path": "desktop.png",
            "exclude-global-prep-cmd": "false",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5"
        },
        {
            "name": "Low Res Desktop",
            "image-path": "desktop.png",
            "prep-cmd": [
                {
                    "do": "xrandr --output HDMI-1 --mode 1920x1080",
                    "undo": "xrandr --output HDMI-1 --mode 1920x1200"
                }
            ]
        },
        {
            "name": "MoonDeckStream",
            "output": "",
            "cmd": "",
            "exclude-global-prep-cmd": "false",
            "elevated": "false",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5",
            "detached": [
                "\/home\/user\/.Appimages\/moondeckbuddy.appimage --exec MoonDeckStream"
            ],
            "image-path": "",
            "prep-cmd": [
                {
                    "do": "sh -c \"kscreen-doctor output.HDMI-A-1.mode.${SUNSHINE_CLIENT_WIDTH}x${SUNSHINE_CLIENT_HEIGHT}@${SUNSHINE_CLIENT_FPS}\"",
                    "undo": "kscreen-doctor output.HDMI-A-1.mode.1920x1080@60"
                }
            ]
        },
        {
            "name": "Steam Big Picture",
            "detached": [
                "setsid gamescope -e -- steam steam:\/\/open\/bigpicture"
            ],
            "image-path": "steam.png",
            "exclude-global-prep-cmd": "",
            "auto-detach": "true",
            "wait-all": "true",
            "exit-timeout": "5"
        }
    ]
}
```

### Relevant log output

```shell
Nothing like that.
```

**Comment by Billones142** [comment]
happends to me too. Arch Linux, Nvidia GPU, i dont think it's relevant info. you can try to solve it with a post script to kill the zombie process after the sunshine session end while they fix it.
