### ISSUE TITLE
Does not start as system service on WIndows 11 

### ISSUE THREAD

**Issue by snipah** [LizardByte/Sunshine#340]
### Describe the Bug

sunshine.exe works properly on my PC, but as this is a shared PC, I'd like to start Sunshine as early a possible as a system service to be able to stream the user selection screen in Windows 11. Combined with the WOL-feature this would be the perfect solution for me. How to achieve this? I did not find any working how-tos...

### Expected Behavior

Start sunshine.exe as a system-service on boot. Ideally the option should be given upon installation, as i. e. parsec does.

### Host Operating System

Windows

### Operating System Version

Windows 11

### Architecture

64Bit

### Sunshine Version

latest

### GPU Type

Intel

### GPU Model

Intel Iris Plus Graphics 655

### GPU Driver/Mesa Version

latest

**Comment by ReenigneArcher** [comment]
duplicate of #197
