### ISSUE TITLE
Provide RPM Packages for current life fedora / Support Fedora 40/41

### ISSUE THREAD

**Issue by peeweek** [LizardByte/Sunshine#3435]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Is your issue described in the documentation?

- [ ] I have read the documentation

### Is your issue present in the latest beta/pre-release?

None

### Describe the Bug

Currently, provided RPM Packages target respectively fedora 38 and 39 which are both versions that are already end-of-life (https://docs.fedoraproject.org/en-US/releases/eol/) :
- Fedora 38 support has ended 2024-05-21
- Fedora 39 support has ended 2024-11-26

This poses a security threat as it discourages sunshine users running fedora from taking the leap from upgrading their systems to versions 40 and 41, putting their computers at risk as the operating system does not receive security updates anymore.

Still, We already know that there is a COPR (https://copr.fedorainfracloud.org/coprs/matte-schwartz/sunshine/) that references packages of sunshine, probably built from modified source. As they are stating that CUDA is currently disabled for compatibility with f40.

Actions would require (at least) dropping support for distributing f38 and f39 RPMs, and eventually work on making it functional on fedora 40/41.

### Expected Behavior

Provide RPMs for install on Fedora 40/41

### Host Operating System

Linux

### Operating System Version

Fedora

### Architecture

amd64/x86_64

### Sunshine commit or version

Not relevant

### Package

Linux - Fedora Copr

### GPU Type

n/a

### GPU Model

Not relevant

### GPU Driver/Mesa Version

Not relevant

### Capture Method

None

### Relevant log output

```shell
----
```

**Comment by ReenigneArcher** [comment]
This is already done. Check copr for LizardByte.

**Comment by peeweek** [comment]
Ooops sorry, I totally overlooked it. Thank you for pointing that out. I'll remove older copr and use yours instead :)

**Comment by Heus-Sueh** [comment]
> This is already done. Check copr for LizardByte.

Installing sunshine from the copr repository still requires entering commands in the terminal for KMS Display capture to work, or does this only affect flatpak and AppImage?

If it still requires it, how can I do this in fedora atomic, since it is a read-only system?

And why doesn't the stable repository have any builds of the sunshine package?
https://copr.fedorainfracloud.org/coprs/lizardbyte/stable/

only the beta has recent builds:
https://copr.fedorainfracloud.org/coprs/lizardbyte/beta/

**Comment by t184256** [comment]
Could they also, please, target f42/rawhide? This currently holds me off upgrading to f42 beta; tracking rawhide gives the benefit of automatically doing such branching.

**Comment by ReenigneArcher** [comment]
rawhide gives too many problems with our builds, so it has been disabled.

There's also this discussion (https://github.com/orgs/LizardByte/discussions/677#discussioncomment-12270247) which I am looking for feedback on before continuing.
