### ISSUE TITLE
It is no longer possible to use Sunshine without ViGEmBus

### ISSUE THREAD

**Issue by Swarkin** [LizardByte/Sunshine#3442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

I'm too lazy to test

### Describe the Bug

Unchecking the vigembus option makes a red warning pop up that its missing. I dont even have gamepad input enabled...
Device cant be connected to.

### Host Operating System

Windows

### Operating System Version

Windows 11 IoT Enterprise LTSC 24H2 26100.1457

### Architecture

amd64/x86_64

### Sunshine commit or version

0.23.1

### Package

Windows - installer (recommended)

### GPU Type

Intel

### GPU Model

intel uhd graphics 615

### GPU Driver/Mesa Version

intel uhd graphics 615

### Capture Method

None

### Relevant log output

```shell
Fatal: ViGEmBus is not installed or running. You must install ViGEmBus for gamepad support!
```

**Comment by ReenigneArcher** [comment]
I don't believe the vigembus error message has anything to do with your connection issue.
