### ISSUE TITLE
Fedora Copr repo stable never built

### ISSUE THREAD

**Issue by linkion** [LizardByte/Sunshine#3448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

The copr repo provided by Lizardbyte has two repos for Sunshine; the [beta](https://copr.fedorainfracloud.org/coprs/lizardbyte/beta/packages/) package is being actively built; however, the [stable](https://copr.fedorainfracloud.org/coprs/lizardbyte/stable/packages/) branch has never been built.

### Expected Behavior

Both lizardbyte/stable and lizardbyte/beta would have functioning build systems with automatic building based on the GitHub repo.

### Host Operating System

other, n/a

### Operating System Version

N/A

### Architecture

other, n/a

### Sunshine commit or version

N/A

### Package

Linux - Fedora Copr

### GPU Type

n/a

### GPU Model

N/A

### GPU Driver/Mesa Version

N/A

### Capture Method

None

### Relevant log output

```shell
N/A
```

**Comment by ReenigneArcher** [comment]
It hasn't been built because it was introduced AFTER the last stable release, v0.23.1. It will automatically start building when we make the next stable release.

**Comment by linkion** [comment]
Ah, okay

Thanks
