### ISSUE TITLE
Sunshine should wake up display instead of refusing connection

### ISSUE THREAD

**Issue by Damglador** [LizardByte/Sunshine#3450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

I'm too lazy to test

### Describe the Bug

I know this is technically a duplicate of #2494, but it was closed without any reason, so I would at least like to know why, because this is kinda a big issue.

If Plasma turns off the monitor, Moonlight just stops being able to connect to Sunshine, instead of waking it up it just gives an error. So I would either need to have my monitor always on, find a way to remotely wake it up or find another unreasonably complicated workaround like a virtual monitor or something. 

### Expected Behavior

If a monitor is sleeping, Sunshine should just try to wake it up instead of refusing a connection.

### Additional Context

My system:

- Kernel: Linux 6.12.4-zen1-1-zen
- DE: KDE Plasma 6.2.4
- WM: KWin (Wayland)
- Monitor: 1920x1200 @ 60 Hz in 14" [Built-in]
- CPU: 12th Gen Intel(R) Core(TM) i7-1265U (12) @ 4.80 GHz

### Host Operating System

Linux

### Operating System Version

Arch Linux

### Architecture

amd64/x86_64

### Sunshine commit or version

v0.23.1

### Package

Linux - AUR (Third Party)

### GPU Type

Intel

### GPU Model

Intel Iris Xe Graphics

### GPU Driver/Mesa Version

mesa 1:24.3.1-3 | vulkan-intel 1:24.3.1-3

### Capture Method

KMS (Linux)

### Relevant log output

```shell
[2024:12:14:18:42:34]: Info: Screencasting with KMS
[2024:12:14:18:42:34]: Info: /dev/dri/card1 -> i915
[2024:12:14:18:42:34]: Error: Couldn't find monitor [0]
[2024:12:14:18:42:34]: Info: Encoder [software] failed
[2024:12:14:18:42:34]: Fatal: Unable to find display or encoder during startup.
[2024:12:14:18:42:34]: Fatal: Please check that a display is connected and powered on.
```

**Comment by ReenigneArcher** [comment]
It was closed when it was converted to a feature request, which is what this is. https://github.com/orgs/LizardByte/discussions/439
