### ISSUE TITLE
No VAAPI settings tab on fedora/amd system

### ISSUE THREAD

**Issue by volo-thomas** [LizardByte/Sunshine#3451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

I have fedora 41 installed on 2 different machines. A prime laptop with an i5 7300HQ and Nvidia 1050 mobility and then another system with an RX 580. On both systems vaapi is detected as supporting x264 and hevc as you'd expect. On the Intel/Nvidia system there is a vaapi config tab, but there is not one on the AMD system

![image](https://github.com/user-attachments/assets/7cd5f8f1-a945-4095-91fd-41ab6f0023ef)

### Expected Behavior

I would expect to see the vaapi settings tab if it's available

### Additional Context

I'm using KDE plasma on wayland and here's the output of vainfo

thomas@fedora:~$ vainfo
Trying display: wayland
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib64/dri-nonfree/radeonsi_drv_video.so
libva info: Trying to open /usr/lib64/dri-freeworld/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.22 (libva 2.22.0)
vainfo: Driver version: Mesa Gallium driver 24.2.8 for AMD Radeon RX 580 Series (radeonsi, polaris10, LLVM 19.1.0, DRM 3.59, 6.11.4-301.fc41.x86_64)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
thomas@fedora:~$ vainfo --display drm --device /dev/dri/renderD128 
Trying display: drm
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib64/dri-nonfree/radeonsi_drv_video.so
libva info: Trying to open /usr/lib64/dri-freeworld/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.22 (libva 2.22.0)
vainfo: Driver version: Mesa Gallium driver 24.2.8 for AMD Radeon RX 580 Series (radeonsi, polaris10, LLVM 19.1.0, DRM 3.59, 6.11.4-301.fc41.x86_64)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc

### Host Operating System

Linux

### Operating System Version

fedora 41

### Architecture

amd64/x86_64

### Sunshine commit or version

2024.629.13903.copr

### Package

Linux - Fedora Copr

### GPU Type

AMD

### GPU Model

rx  580

### GPU Driver/Mesa Version

Mesa Gallium driver 24.2.8

### Capture Method

KMS (Linux)

### Config

```Shell
global_prep_cmd = [{"do":"sh -c \"kscreen-doctor output.DP-2.mode.${SUNSHINE_CLIENT_WIDTH}x${SUNSHINE_CLIENT_HEIGHT}@${SUNSHINE_CLIENT_FPS}\"","undo":"kscreen-doctor output.DP-2.mode.2560x1440@144"}]
output_name = 1
sunshine_name = Thomas Desktop
```

### Relevant log output

```shell
[2024:12:14:11:34:03]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2024:12:14:11:34:03]: Info: 
[2024:12:14:11:34:03]: Info: Found H.264 encoder: h264_vaapi [vaapi]
[2024:12:14:11:34:03]: Info: Found HEVC encoder: hevc_vaapi [vaapi]
[2024:12:14:11:34:03]: Info: Adding avahi service Sunshine
[2024:12:14:11:34:03]: Info: Configuration UI available at [https://localhost:47990]
[2024:12:14:11:34:04]: Info: Avahi service Sunshine successfully established.
```

**Comment by ReenigneArcher** [comment]
The vaapi tab was added in November, your version is from June.
