### ISSUE TITLE
Add config to change the web UI from port 47990 to a custom one

### ISSUE THREAD

**Issue by jmriego** [LizardByte/Sunshine#3456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

Right now it's not possible (or I haven't found any config or docs) to change the web UI from the port 47990. The docs just mention that "it's open on 47990 by default" but I cannot figure out how to change that

### Expected Behavior

I'd like to change it to a custom port

### Additional Context

Nothing specific, but it would help in my case as I'm using a VPN that requires that port to be functional

### Host Operating System

Linux

### Operating System Version

24.04

### Architecture

amd64/x86_64

### Sunshine commit or version

v0.18.1

### Package

Linux - AppImage

### GPU Type

AMD

### GPU Model

NVIDIA Corporation TU117GLM [Quadro T1000 Mobile] 

### GPU Driver/Mesa Version

Unsure

### Capture Method

X11 (Linux)

### Config

```Shell
key_rightalt_to_key_win = disabled
vt_realtime = enabled
vt_software = auto
amd_quality = balanced
origin_web_ui_allowed = pc
min_log_level = 2
nv_rc = cbr
hevc_mode = 0
amd_rc = vbr_latency
vt_coder = auto
encoder = nvenc
dwmflush = enabled
amd_coder = auto
nv_preset = p4
upnp = disabled
nv_coder = auto
gamepad = x360
qsv_coder = auto
resolutions = [
    352x240,
    480x360,
    858x480,
    1280x720,
    1920x1080,
    2560x1080,
    3440x1440,
    1920x1200,
    3860x2160,
    3840x1600
]
origin_pin_allowed = wan
qsv_preset = medium
fps = [10,30,60,90,120]
nv_tune = ll
```

### Relevant log output

```shell
[2024:12:16:19:04:51]: Info: Configuration UI available at [https://localhost:47990]
```

**Comment by ReenigneArcher** [comment]
Changing the config port changes the ui port.

**Comment by jmriego** [comment]
I never noticed that! Yes, that worked perfectly. The UI port seems to always be the next one after the Sunshine port. Thanks a lot!

**Comment by ReenigneArcher** [comment]
It still might be good to allow having the config port able to be configured separately. It's kind of a weird default port number 47990.
