### ISSUE TITLE
Unknown Monitor connector type [Virtual]

### ISSUE THREAD

**Issue by rhjdvsgsgks** [LizardByte/Sunshine#347]
### Describe the Bug

sunshine failed to start when using virtual monitor created by amdgpu driver

### Expected Behavior

start normally

### Additional Context

```
modinfo amdgpu 
...
parm:           virtual_display:Enable virtual display feature (the virtual_display will be set like xxxx:xx:xx.x,x;xxxx:xx:xx.x,x) (charp)
...
```

### Host Operating System

Linux

### Operating System Version

linux 5.19.4

### Architecture

x86_64

### Sunshine Version

0.14.1

### GPU Type

amd

### GPU Model

navi

### GPU Driver/Mesa Version

22.3.0

### Relevant log output

```Shell
Info: Found display [wayland-0]
Info: Found interface: zxdg_output_manager_v1(30) version 3
Info: Found interface: wl_output(42) version 3
Warning: Missing Wayland wire for wlr-export-dmabuf
Info: Found display [wayland-0]
Info: Found display [wayland-0]
Info: Found interface: zxdg_output_manager_v1(30) version 3
Info: Found interface: wl_output(42) version 3
Info: Offset: 0x0
Info: Resolution: 3840x2160
Info: Name: Virtual-1
Info: Found monitor:  Virtual-1-unknown
Info: Virtual-1:  Virtual-1-unknown
Error: Unknown Monitor connector type [Virtual]: Please report this to the Github issue tracker
```

**Comment by ReenigneArcher** [comment]
The kernel version isn't really helpful... we need to know the distro and version if possible. Which package are you using?

**Comment by lylythechosenone** [comment]
I have the same issue. I'm trying to set up a virtual monitor with `krfb-virtualmonitor`. The monitor works fine in VNC, as expected, but sunshine can't figure it out for some reason.

**Comment by Anti-Iridium** [comment]
Please let me know if you need any more information.

**Comment by Anti-Iridium** [comment]
I came to the realization I have an extra GPU (Another Instinct MI25) that I am willing to send to the developer, if it would make fixing the issue easier.
