### ISSUE TITLE
Update docs for Fedora install

### ISSUE THREAD

**Issue by Neurofibromin** [LizardByte/Sunshine#3470]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your issue described in the documentation?

- [x] I have read the documentation

### Is your issue present in the latest beta/pre-release?

None

### Describe the Bug

The Fedora COPR install is not described int the docs at https://docs.lizardbyte.dev/projects/sunshine/en/latest/about/setup.html nor is it mentioned at the third party packages section: https://docs.lizardbyte.dev/projects/sunshine/en/latest/about/third_party_packages.html

The getting started page in the repo https://github.com/LizardByte/Sunshine/blob/master/docs/getting_started.md does have the information, but it would be nice if the official (?) docs had it as well.

### Expected Behavior

-

### Additional Context

-

### Host Operating System

Linux

### Operating System Version

Fedora 41

### Architecture

amd64/x86_64

### Sunshine commit or version

latest

### Package

Linux - Fedora Copr

### GPU Type

NVIDIA

### GPU Model

-

### GPU Driver/Mesa Version

-

### Capture Method

None

### Config

```Shell

```

### Apps

```json

```

### Relevant log output

```shell
-
```

**Comment by ReenigneArcher** [comment]
https://github.com/LizardByte/Sunshine/blob/master/docs/getting_started.md will become "latest" after the next stable release.
