### ISSUE TITLE
Web UI is not loading vue template (pre-release only)

### ISSUE THREAD

**Issue by petrhanak** [LizardByte/Sunshine#3491]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your issue described in the documentation?

- [x] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

Web UI is broken when I click on the logs page.
![Image](https://github.com/user-attachments/assets/930126ec-b7b4-4f4f-b742-dacde6788847)

### Expected Behavior

The logs are displayed

### Additional Context

This issue is happening ONLY on pre-release version. Latest stable release (v0.23.1) works fine.

### Host Operating System

Windows

### Operating System Version

Windows 11, Windows Server 2025, Windows Server 2022

### Architecture

amd64/x86_64

### Sunshine commit or version

v2024.1223.230344

### Package

Windows - installer (recommended)

### GPU Type

AMD

### GPU Model

-

### GPU Driver/Mesa Version

-

### Capture Method

None

### Config

```Shell

```

### Apps

```json

```

### Relevant log output

```shell
-
```

**Comment by petrhanak** [comment]
![Image](https://github.com/user-attachments/assets/efc86101-4e2a-4e61-9956-c6943a56d3bc)

**Comment by ReenigneArcher** [comment]
Are other pages working?

**Comment by petrhanak** [comment]
This button causes the issue. Opening Troubleshooting from menu works just fine.
<img width="831" alt="Image" src="https://github.com/user-attachments/assets/fc9998f2-4c55-45a1-bc68-794566d3b081" />

OK
https://localhost:47990/troubleshooting

Broken
https://localhost:47990/troubleshooting/#logs

I checked with stable version (v0.23.1) and the URL has not changed.

**Comment by ReenigneArcher** [comment]
Can you take out the last slash? Probably just a typo
