### ISSUE TITLE
PS5 Controller (CFI-ZCT1W) is not working even though client recognizes normally

### ISSUE THREAD

**Issue by testerbeta2** [LizardByte/Sunshine#3497]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your issue described in the documentation?

- [x] I have read the documentation

### Is your issue present in the latest beta/pre-release?

None

### Describe the Bug

I'm streaming my desktop from my PC (host) to my Nvidia Shield Pro (client). Mouse and keyboard work fine, but my PS5 controller doesn't.

Note that the PS5 controller is recognized and pairs fine with Nvidia Shield Pro (client), and I can use it to control everything in Nvidia Shield Pro, up to the point where I go to moonlight and try to run desktop through Sunshine. As soon as my desktop shows up, the controller does nothing. None of the buttons work EXCEPT for the playstation button which just takes terminates the session (seems like it acts as a back button and it takes me back to moonlight).

The logs in sunshine only show this relevant part:

[2024:12:28:15:27:22]: Warning: Gamepad 0 is emulating a DualShock 4 controller, but the client gamepad doesn't have motion sensors active
[2024:12:28:15:27:22]: Warning: Gamepad 0 is emulating a DualShock 4 controller, but the client gamepad doesn't have a touchpad

I tried both with Gamepad setting set to automatic, and set to DS4. Both have exactly the same issue.

Any ideas?

### Expected Behavior

To be able to control my mouse on my desktop with the PS5 controller connected to my Nvidia Shield Pro (client)

### Host Operating System

Windows

### Operating System Version

10

### Architecture

amd64/x86_64

### Sunshine commit or version

v0.23.1

### Package

Windows - installer (recommended)

### GPU Type

NVIDIA

### GPU Model

RTX 3060

### GPU Driver/Mesa Version

No idea sorry

### Capture Method

None

### Config

```Shell

```

### Apps

```json

```

### Relevant log output

```shell
[2024:12:28:15:27:22]: Warning: Gamepad 0 is emulating a DualShock 4 controller, but the client gamepad doesn't have motion sensors active
[2024:12:28:15:27:22]: Warning: Gamepad 0 is emulating a DualShock 4 controller, but the client gamepad doesn't have a touchpad
```

**Comment by ReenigneArcher** [comment]
Normally you have to hold start for 2 seconds (depending on which Moonlight client you are using) to switch to mouse mode.

**Comment by testerbeta2** [comment]
@ReenigneArcher It worked! Thank you
