### ISSUE TITLE
Latest Moonlight Client cannot render NVENC Sunshine Hosts (Win 4.2.0, Android 10.8)

### ISSUE THREAD

**Issue by cyphercolt** [LizardByte/Sunshine#364]
### Describe the Bug

**Tested on Windows Moonlight Client 4.2.0, and Android Moonlight Client 10.8**

When hosting with Sunshine in NVENC, the September update to the Moonlight Client is unable to render the video from the host.
On Windows Client, the screen is white, audio and inputs are working. On the Android Client, the screen is black, audio and inputs are working.
After a bit of time, the client disconnects from the host with an error. "Your network connection isn't performing well, Reduce your video bitrate setting or try a faster connection" (Windows error) similar error on Android about Poor connections.

The workaround for now is to downgrade the client version, and everything functions normally. (I'm back on Windows Client 4.1.0 and Android Client 10.7)

### Expected Behavior

The video renders correctly on any version of the Moonlight Client.

### Host Operating System

Windows

### Operating System Version

Windows 11, Android 13

### Architecture

64 Bit for Windows, Arm for Android.

### Sunshine Version

0.14.0

### GPU Type

Nvidia

### GPU Model

GeForce RTX 3070

### GPU Driver/Mesa Version

516.94

**Comment by codevski** [comment]
argh should of checked this first, factory reset my nvidia shield and reset my switch thinking it was net work problem changed ethernet connection and the lot!

**Comment by KuleRucket** [comment]
There is a moonlight fix for this:
"v4.2.1 is a hotfix release to address a bug in v4.2.0 that prevented streaming from hosts running [Sunshine](https://github.com/LizardByte/Sunshine). The original release notes for v4.2.0 are below."

**Comment by cgutman** [comment]
This is fixed in Moonlight PC v4.2.1 and Moonlight Android v10.8.1

**Comment by ReenigneArcher** [comment]
> This is fixed in Moonlight PC v4.2.1 and Moonlight Android v10.8.1

Thanks for the quick fix!
