### ISSUE TITLE
Virtual Input devices are always attached to seat0

### ISSUE THREAD

**Issue by remenic** [LizardByte/Sunshine#371]
### Describe the Bug

When starting sunshine on a second X11 seat, it creates virtual input devices for seat0. Moving the mouse in moonlight will move the mouse on the first seat, not on the seat that is displayed in moonlight.

### Expected Behavior

The new virtual input devices are attached to the current $XDG_SEAT

### Host Operating System

Linux

### Operating System Version

Arch Linux

### Architecture

64 bit

### Sunshine Version

0.14.1-1

### GPU Type

NVidia (for the second seat)

### GPU Model

GeForce RTX 2070 Super

### GPU Driver/Mesa Version

515.65.01

### Capture Method (Linux Only)

X11

**Comment by einhander** [comment]
The same for VNC servers. Xinput gives the following  list:
xinput --list
Virtual core pointer                    	id=2	[master pointer  (3)]
Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
TurboVNC pointer                        	id=6	[slave  pointer  (2)]
Virtual core keyboard                   	id=3	[master keyboard (2)]
Virtual core XTEST keyboard             id=5	[slave  keyboard (3)]
TurboVNC keyboard                       	id=7	[slave  keyboard (3)]
