### ISSUE TITLE
We don't support old versions. Do you have the same exact issue in v0.14.1?

### ISSUE THREAD

**Issue by Keksimus69** [LizardByte/Sunshine#381]
We don't support old versions. Do you have the same exact issue in v0.14.1?

_Originally posted by @ReenigneArcher in https://github.com/LizardByte/Sunshine/issues/377#issuecomment-1257326819_
      My mistake I actually have v0.14.1. I guess I typed it wrong

**Comment by ReenigneArcher** [comment]
I re-opened your other issue. In the future please do not open issues like this. We have GitHub discussions and discord if you need to communicate with us.
