### ISSUE TITLE
Low FPS/High delay on desktop

### ISSUE THREAD

**Issue by JFMugen** [LizardByte/Sunshine#387]
### Describe the Bug

While writing something or just browsing images for example, delay increases as much as 1-2 seconds.

### Expected Behavior

Constant 60 fps without any delay. 

### Additional Context

I am using Cat6 wire to connect client and host so I have no network limit. 

### Host Operating System

Windows

### Operating System Version

Win10 Home 21H2  -  19044.2006

### Architecture

64

### Sunshine Version

0.14.1

### GPU Type

Nvidia

### GPU Model

3060

### GPU Driver/Mesa Version

516.94

**Comment by Jake-Jensen** [comment]
Just commenting here, but this: "I am using Cat6 wire to connect client and host so I have no network limit." means functionally nothing. If your NIC is only 10/10, it doesn't matter what wire you're using, it's 10/10.

**Comment by ReenigneArcher** [comment]
While correct, I don't believe this is a network issue. This is a known issue on Windows desktops when few pixels are changing.

**Comment by ReenigneArcher** [comment]
This is a duplicate of #412 and #122 so closing.
