### ISSUE TITLE
Publish to AUR using aurpublish

### ISSUE THREAD

**Issue by ReenigneArcher** [LizardByte/Sunshine#39]
**Describe the bug**

There are two sunshine packages on AUR, manually maintained.
  - https://aur.archlinux.org/packages/sunshine
  - https://aur.archlinux.org/packages/sunshine-git

**Expected behavior**

- Build the AUR package on PRs into nightly and master.
- Automate the AUR package update when a push is made into master branch.
  - Hopefully `pkgver` can be automated easily (we already get version automatically from the CHANGELOG file)
    - https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=sunshine#n4
    - https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=sunshine-git#n5
  - url also should be updated to match this repo
- This file needs to be updated (https://github.com/SunshineStream/Sunshine/blob/nightly/.github/workflows/CI.yml)

**Comment by ReenigneArcher** [comment]
@hadogenes Would you be interested in helping with this issue?

**Comment by hadogenes** [comment]
has @loki-47-6F-64 abandoned its project?
Previously he took a break for about a year and then made a lot of changes

**Comment by loki-47-6F-64** [comment]
I haven't abandoned it yet.
Been busy with personal stuff. :p

**Comment by hadogenes** [comment]
@loki-47-6F-64 do you want to contribute to this repo or use your?

**Comment by loki-47-6F-64** [comment]
This one's fine.

**Comment by ReenigneArcher** [comment]
> I haven't abandoned it yet. Been busy with personal stuff. :p

Glad to see you Loki! The goal of this repo is to make the repo more manageable (with github workflows) and community driven. Cheers!

**Comment by hadogenes** [comment]
aur repo are pinned to SunshineStream

**Comment by ReenigneArcher** [comment]
> aur repo are pinned to SunshineStream

Cool! Do you have any ideas for how to update it automatically with our CI.yml?

**Comment by KuleRucket** [comment]
@hadogenes please can you orphan the AUR?

**Comment by ReenigneArcher** [comment]
@KuleRucket the current "maintainer" is afterSt0rm https://aur.archlinux.org/packages/sunshine

I don't think they are even interested in sunshine to be honest.
https://aur.archlinux.org/account/afterSt0rm

**Comment by IceDBorn** [comment]
@ReenigneArcher Should we use sunshine-git instead?

**Comment by ReenigneArcher** [comment]
@IceDBorn I have control of that one currently and this PR is setup to automatically publish to there... There are currently 2 requests to have the main one orphaned... I don't know how long the AUR maintainers take to respond though or if they'll even do anything.

**Comment by KuleRucket** [comment]
"sunshine" without git will be what people go to first so either it should be removed all together or updated to 0.14.0. Either way, it requires the current maintainer to do something.

**Comment by esistgut** [comment]
sunshine-git doesn't seem to work over here:
```
[ 98%] Building C object CMakeFiles/sunshine.dir/third-party/glad/src/gl.c.o
[100%] Linking CXX executable sunshine
make[2]: Leaving directory '/home/esistgut/.cache/yay/sunshine-git/src/build'
[100%] Built target sunshine
make[1]: Leaving directory '/home/esistgut/.cache/yay/sunshine-git/src/build'
make: Leaving directory '/home/esistgut/.cache/yay/sunshine-git/src/build'
==> Entering fakeroot environment...
==> Starting package()...
/home/esistgut/.cache/yay/sunshine-git/PKGBUILD: line 68: pushd: sunshine-git/assets: No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
```

**Comment by ReenigneArcher** [comment]
> sunshine-git doesn't seem to work over here:
> ```
> [ 98%] Building C object CMakeFiles/sunshine.dir/third-party/glad/src/gl.c.o
> [100%] Linking CXX executable sunshine
> make[2]: Leaving directory '/home/esistgut/.cache/yay/sunshine-git/src/build'
> [100%] Built target sunshine
> make[1]: Leaving directory '/home/esistgut/.cache/yay/sunshine-git/src/build'
> make: Leaving directory '/home/esistgut/.cache/yay/sunshine-git/src/build'
> ==> Entering fakeroot environment...
> ==> Starting package()...
> /home/esistgut/.cache/yay/sunshine-git/PKGBUILD: line 68: pushd: sunshine-git/assets: No such file or directory
> ==> ERROR: A failure occurred in package().
>     Aborting...
> ```

Right... Because the AUR hasn't been updated yet ....
