### ISSUE TITLE
Capturing images by callback, rather than pulling Causes Desktop issues.

### ISSUE THREAD

**Issue by Theo-Technologies** [LizardByte/Sunshine#412]
### Describe the Bug

The Commit Capturing images by callback, rather than pulling seen here: https://github.com/LizardByte/Sunshine/commit/7ddf8bbe94ceb31dcc411dc28206399d81396a05

Causes issues when using the desktop. If the mouse is not moving the fps will drop dramatically and extreme lag will occur. If the mouse is constantly moving then there is no lag. This only occurs on the desktop or using non GPU intensive applications like the web browser or Microsoft Word. Previous to this commit, the desktop would function fine.

### Expected Behavior

We need the desktop to be stable at all times. Whether this be a different callback method or a small fix.

### Host Operating System

Windows

### Operating System Version

Windows 10 Pro

### Architecture

64 bit.

### Sunshine Version

0.14.0

### GPU Type

Nvidia

### GPU Model

A4000

### GPU Driver/Mesa Version

n/a

**Comment by OliverJFedorko** [comment]
> This seems relevant. [loki-47-6F-64/sunshine#253](https://github.com/loki-47-6F-64/sunshine/issues/253)

I have seen this before. I have noticed that the callback method is far superior on slower internet connections with better stability when gaming though.

**Comment by ReenigneArcher** [comment]
@Theo-Technologies while I asked you to open this, it appears to be a duplicate. Can you add your details to #122 ?
