### ISSUE TITLE
Sunshine should not require Static boost libs for Unix based builds.

### ISSUE THREAD

**Issue by GavinDarkglider** [LizardByte/Sunshine#434]
### Describe the Bug

Most linux distros dont ship everything as static libs, On gentoo, you specifically have to specify if you want a package to also build static libs. this if statement should be fixed to include unix builds in cmakelists.txt

https://github.com/LizardByte/Sunshine/blob/master/CMakeLists.txt#L71-L73

This should not just be for apple, but unix based builds as well.

### Expected Behavior

Being able to build on systems that dont supply boost libs as static libs

### Additional Context

Gentoo doesnt seem to build/install static boost libs, if you change this statement, and build against the shared libs, it builds, and runs fine, if you dont, it wont build at all

### Host Operating System

Linux

### Operating System Version

Gentoo

### Architecture

x86_64

### Sunshine Version

Master

### GPU Type

Intel/Nvidia

### GPU Model

Irrelevant

### GPU Driver/Mesa Version

Irrelevant

### Relevant log output

```Shell
Cmake Fails when looking for static boost libs, on unix/linux when shared lib version is installed, with out also having static lib version.
```

**Comment by GavinDarkglider** [comment]
Not sure why you added the help wanted flag to this, as this isnt something I want help with, I linked you the if statement in the CMakeLists.txt that causes the issue, Just not sure how you want to handle that, and as far as I am concerned it is an issue and not my project. Personally just removed the need for static libs and built it anyway, and runs fine. A simple added arg for using shared boost lib would suffice if building for linux..... I was more pointing it out as a potential issue, and one I am surprised no one has brought up before.

**Comment by ReenigneArcher** [comment]
> Not sure why you added the help wanted flag

I'm not a c++ expert, just doing my best to keep this project alive. I'm happy to make a change if someone submits a PR and all our tests/builds pass.

From my understanding building with static libraries is preferred since it doesn't require extra libraries to be installed along side the final binary.

> I am surprised no one has brought up before

Most users are using more popular distros. Only seen a few cases of Sunshine users using Gentoo.

Anyway, this change was introduced here. https://github.com/LizardByte/Sunshine/commit/fed329568ca44993d9cc0a8fe145e73a332fb111

**Comment by GavinDarkglider** [comment]
I will work something up then, and submit it......Not really an issue, as it is a simple change to make that a user settable variable, that keeps current properties, but also can be changed without editing the file.

**Comment by ReenigneArcher** [comment]
Sounds good, thank you!
