### ISSUE TITLE
AMDVCE encoder not working

### ISSUE THREAD

**Issue by syq7970** [LizardByte/Sunshine#449]
### Describe the Bug

AMDVCE encoder always got error.
Tried 1.11.0 ~ nightly build, but no luck.
can only use software encoder with poor performance.

![微信截图_20221029182233](https://user-images.githubusercontent.com/12478505/198826259-10a65439-055c-4485-ad56-8fbc31aa828f.png)

### Expected Behavior

can use AMD hardware encoder

### Host Operating System

Windows 11

### Operating System Version

Windows 11 22h2

### Architecture

64bit

### Sunshine Version

0.14.1

### GPU Type

AMD

### GPU Model

AMD Radeon RX 6900 XT

### GPU Driver/Mesa Version

22.10.1

### Relevant log output

 Failed to create input shader resource view [0x80070057]

**Comment by zerkz** [comment]
I'm running into this issue too, and have a similar setup. I'm working backwards to see if a earlier version works.

**Comment by zerkz** [comment]
aha! I think I figured this out, atleast for my case! 

@syq7970 Do you have HDR turned on in Windows 11? If so, turn it off, and try the hardware decoder again 😁 

(related: HDR support https://github.com/LizardByte/Sunshine/issues/375)

**Comment by xfury94** [comment]
Can confirm it's a issue with amd drivers, last known working driver is 22.5.1.

Tested on a RX 6600 with 22.5.1 until the latest 22.11.2.

Also tested with parsec and it gave the same issue.
