### ISSUE TITLE
Package libavdevice58 is not available - Ubuntu 22.10

### ISSUE THREAD

**Issue by ryanrambharose** [LizardByte/Sunshine#465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Describe the Bug

The dependency libavdevice58 is not included in ubuntu 22.10 and is upgraded to libavdevice59 in the repositories.

### Operating System Version

Ubuntu 22.10

### Sunshine commit or version

0.15

### Package

Linux - deb

### GPU Model

RTX 3050

### GPU Driver/Mesa Version

515

**Comment by levouh** [comment]
The `libavdevice5X` version distributed with 22.10 is `59` (versus `58` for the currently distributed `.deb`) and the linker is obviously not happy. Easiest way around this for now is to build it yourself while 22.10 is on its way to becoming more "mainstream" (and having packages distributed specifically for it, etc.):

```sh
#! /bin/bash

set -eo pipefail

install-sunshine() {
    local dir=""

    dir="$(mktemp -d)"

    cd "$dir" || return 1
    git clone --recurse-submodules git@github.com:LizardByte/Sunshine.git
    cd Sunshine || return 1
    mkdir build && cd build || return 1
    sudo apt update && \
    sudo apt install \
        build-essential \
        cmake \
        libavdevice-dev \
        libboost-filesystem-dev \
        libboost-log-dev \
        libboost-thread-dev \
        libcap-dev \
        libdrm-dev \
        libevdev-dev \
        libpulse-dev \
        libopus-dev \
        libssl-dev \
        libwayland-dev \
        libx11-dev \
        libxcb-shm0-dev \
        libxcb-xfixes0-dev \
        libxcb1-dev \
        libxfixes-dev \
        libxrandr-dev \
        libxtst-dev \
        nvidia-cuda-dev \
        nvidia-cuda-toolkit
    cmake -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 ..
    make -j "$(nproc)"

    sudo usermod -aG input "$USER"

    echo 'KERNEL=="uinput", GROUP="input", MODE="0660", OPTIONS+="static_node=uinput"' | \
    sudo tee /etc/udev/rules.d/85-sunshine-input.rules

    mkdir -p ~/.config/systemd/user
    echo "[Unit]
Description=Sunshine Gamestream Server for Moonlight

[Service]
ExecStart=/usr/local/bin/sunshine

[Install]
WantedBy=graphical-session.target" | \
    sudo tee ~/.config/systemd/user/sunshine.service

    sudo setcap cap_sys_admin+p "$(readlink -f "$(which sunshine)")"

    cd /tmp || return 1
    rm -rf "$dir"
}

install-sunshine
```

Once this completes, you will need to reboot, and then start/enable (one-time vs persisting with reboot respectively) the service with something like:

```sh
systemctl --user enable --now sunshine
```

Make sure you have rebooted before doing this, and then you can verify the status with:

```sh
systemctl --user status sunshine
```

The above is mostly just ripped directly from [here](https://github.com/LizardByte/Sunshine/blob/master/docs/source/building/linux.rst) for the building steps, as well as the extra setup information from [here](https://docs.lizardbyte.dev/projects/sunshine/en/latest/about/usage.html#setup).

Dumping this here incase anyone else might find it useful. This is the first time I've ever even touched `sunshine`, so I am not 100% sure where to go from here, but this should at least get you going as far as getting the service started goes.

**Comment by ReenigneArcher** [comment]
@levouh thanks... I only quickly scanned your script, but it seems right.

We also have AppImage and Flatpak. I'm not sure how long we're going to continue distributing a deb (and rpm) package to be honest, since they're always riddled with annoying issues like this.

There's also this PR which would build both 20.04 and 22.04. https://github.com/LizardByte/Sunshine/pull/468

**Comment by levouh** [comment]
@ReenigneArcher absolutely agree - distributions can be a complete PITA to deal with. I just wanted to post this in case anyone else has issues and this shows up in their Google search, however it is likely far easier to just recommend/use the AppImage. My main motivation for trying the "raw" binary was to see if there was a performance difference, as I've seen a minor delay when using FUSE in the past.

**Comment by yousefamar** [comment]
Thanks for the script! I think it's missing a `sudo make install` after the `make`.

**Comment by levouh** [comment]
> Thanks for the script! I think it's missing a `sudo make install` after the `make`.

Fixed, thanks.
