### ISSUE TITLE
Sunshine.exe always running even with app closed

### ISSUE THREAD

**Issue by Heeervas** [LizardByte/Sunshine#474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Describe the Bug

When I was closing sunshine I realized I could still access via moonlight to my pc, so I checked and it was because there is a sunshine.exe still running even with app closed. 

Would love to know how to stop it.
I have uninstall and did a clean install and also happening.

Thanks in advance.

### Operating System Version

Windows 11

### Sunshine commit or version

v0.15.0

### GPU Model

6900 XT

### GPU Driver/Mesa Version

22.Q3

**Comment by ReenigneArcher** [comment]
You're running sunshine as a service. Pay attention to the installation options.
