### ISSUE TITLE
Win11 Login Screen Delay

### ISSUE THREAD

**Issue by NolanWelser** [LizardByte/Sunshine#494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Describe the Bug

When connecting to a host that is at the Windows 11 login screen, keyboard input is not shown until something else happens, such as another keyboard input, moving the mouse, or waiting long enough

Example: Typing in a username, I press 'N' and there is no change on screen, I then press 'O' and 'N' appears but 'O' does not.

### Expected Behavior

A key is pressed and the character appears on screen immediately

### Additional Context

This seems to only happen at the Windows login screen, once you are in a user session it is not a problem

### Host Operating System

Windows

### Operating System Version

11

### Architecture

64 bit

### Sunshine commit or version

0.15.0

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

Quadro RTX 6000

### GPU Driver/Mesa Version

512.95

**Comment by ReenigneArcher** [comment]
#122
