### ISSUE TITLE
Cant copy or Paste

### ISSUE THREAD

**Issue by w4itey** [LizardByte/Sunshine#519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Describe the Bug

I cant copy or paste, in moonlight the shortcut is Ctrl-Alt-Shift-v and c to copy and past to the host but they do not function in sunshine.

### Expected Behavior

for the shortcut to paste the host clipboard.

### Host Operating System

Windows

### Operating System Version

11

### Architecture

64 bit

### Sunshine commit or version

0.15.0

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

Geforce 3070

### GPU Driver/Mesa Version

526.98

**Comment by ReenigneArcher** [comment]
Please test the artifact from this build. https://github.com/LizardByte/Sunshine/actions/runs/3537538942

**Comment by w4itey** [comment]
yep that fixed it, thank you so much

**Comment by ReenigneArcher** [comment]
This is fixed in `nightly`, but note that there was an issue with the nightly release build so it is not in the current nightly release.
