### ISSUE TITLE
it does not work on Ubuntu 22.04

### ISSUE THREAD

**Issue by dnet890** [LizardByte/Sunshine#523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Describe the Bug

it does not worked with appimage and deb file

### Additional Context

![image](https://user-images.githubusercontent.com/29157187/205191046-23250eab-50b7-41b2-9209-a1a20e308b0c.png)

### Host Operating System

Linux

### Operating System Version

Ubuntu 22.04

### Architecture

64 bit

### Sunshine commit or version

0.15

### Package

None

### GPU Type

None

### GPU Model

RTX 3070

### GPU Driver/Mesa Version

515.65.01

**Comment by ReenigneArcher** [comment]
Duplicate of https://github.com/LizardByte/Sunshine/issues/185
