### ISSUE TITLE
sunshine caches box images

### ISSUE THREAD

**Issue by ReenigneArcher** [LizardByte/Sunshine#551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Describe the Bug

Box images are cached by Sunshine. The current resolution is to remove the sunshine host from moonlight, and re-add it.

### Expected Behavior

Images are refreshed automatically in moonlight.

### Additional Context

The image is served here:
https://github.com/LizardByte/Sunshine/blob/nightly/src/nvhttp.cpp#L770-L773

We can probably set cache time to 0 for images, or a relatively low value.

https://gitlab.com/eidheim/Simple-Web-Server/blob/master/https_examples.cpp#L139-L140

```cpp
header.emplace("Cache-Control", "max-age=60");
```

### Host Operating System

None

### Operating System Version

-

### Architecture

None

### Sunshine commit or version

b5896c8f2668086ecf93fee71e0ea23b17827c71

### Package

None

### GPU Type

None

### GPU Model

-

### GPU Driver/Mesa Version

-

**Comment by cgutman** [comment]
Moonlight doesn't actually obey the cache control headers for box art (and GFE doesn't send any). All Moonlight clients assume the box art will be constant for a given app ID.

The way GFE handles this is that it changes the app ID when the box art changes. A similar approach should work with all existing Moonlight clients.
