### ISSUE TITLE
AMD failed to stream fullscreen Vulkan app

### ISSUE THREAD

**Issue by Isalight** [LizardByte/Sunshine#553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Describe the Bug

When launching any full-screen application with Vulkan API (test Dota 2, 3DMark Wild Life, Gravity Mark) the stream closes with a connection error.

### Additional Context

Found similar post with the problem in the previous repository (https://github.com/loki-47-6F-64/sunshine/issues/302). Rage 2 use Vulkan API too.

### Host Operating System

Windows

### Operating System Version

Windows 11

### Architecture

64 bit

### Sunshine commit or version

0.15.0

### Package

Windows - portable

### GPU Type

AMD

### GPU Model

Vega 6 (Ryzen 5 4500U)

### GPU Driver/Mesa Version

22.9.1

### Relevant log output

```Shell
Error: Failed to create input shader resource view [0x80070057]
```

**Comment by ShadF0x** [comment]
Can confirm the same behavior on Windows 10 with 6900XT running 22.11.2 driver.

**Comment by cgutman** [comment]
Can you test out the build from #609 and see if that resolves it for you?

https://github.com/LizardByte/Sunshine/suites/10017585595/artifacts/486772452

**Comment by Isalight** [comment]
It works now! But encoder performance is poor if Vulkan is used. It doesn't reach 60 fps.

Also stream works if HDR is enabled in Windows and sunshine don't crash.
