### ISSUE TITLE
sunshine not launching if HMDI EDID Emulator is connected

### ISSUE THREAD

**Issue by kimeikato** [LizardByte/Sunshine#573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

![image](https://user-images.githubusercontent.com/13108952/208239994-90bebc5f-c732-4f89-837f-a5312e9dc6d1.png)
The third monitor is an HDMI-EDID Emulator plug, which simulates a monitor with HDR. If I enable it, it crashes on launch...
![image](https://user-images.githubusercontent.com/13108952/208240108-63fbede3-f7f3-414a-8666-60c0c3abcbb3.png)
If the plug is disabled it works.

### Expected Behavior

I expected it to work like in nvidia gamestream

### Host Operating System

Windows

### Operating System Version

Windows 11 22H2 Build 22521.819

### Architecture

64 bit

### Sunshine commit or version

0.16.0

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

RTX 3070

### GPU Driver/Mesa Version

527.56

### Relevant log output

```Shell
[amd_coder] -- [auto]
[upnp] -- [disabled]
[nv_preset] -- [default]
[encoder] -- [nvenc]
[hevc_mode] -- [0]
[nv_rc] -- [auto]
[fps] -- [[30,60,120]]
[vt_coder] -- [auto]
[amd_rc] -- [auto]
[min_log_level] -- [2]
[vt_realtime] -- [enabled]
[key_rightalt_to_key_win] -- [disabled]
[origin_pin_allowed] -- [pc]
[resolutions] -- [[
    1280x720,
    1920x1080,
    3860x2160,
    2560x1440
]]
[nv_coder] -- [auto]
[gamepad] -- [ds4]
[dwmflush] -- [enabled]
[origin_web_ui_allowed] -- [lan]
[vt_software] -- [auto]
[amd_quality] -- [default]
[2022:12:17:12:39:07]: Info: Compiling shaders...
[2022:12:17:12:39:07]: Info: Compiled shaders
[2022:12:17:12:39:07]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2022:12:17:12:39:07]: Info: Trying encoder [nvenc]
[2022:12:17:12:39:07]: Info:
Device Description : NVIDIA GeForce RTX 3070
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002484
Device Video Mem   : 8031 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8152 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1440
Offset             : 5120x0
Virtual Desktop    : 7680x1445
```

**Comment by ReenigneArcher** [comment]
Specifically set the output/display in the config.
