### ISSUE TITLE
0.16 rpm can not install on Fedora 37 due to dependency issue with libcurl

### ISSUE THREAD

**Issue by bergmannf** [LizardByte/Sunshine#577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Attempting to install the new 0.16 rpm on fedora fails, due to a dependency issue for libcurl:

```
sudo dnf install ./sunshine.rpm     
Last metadata expiration check: 0:10:36 ago on Sat 17 Dec 2022 09:51:37 PM CET.
Error: 
 Problem: conflicting requests
  - nothing provides libcurl.so.4(CURL_OPENSSL_4)(64bit) needed by sunshine-0.16.0-1.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

However the library required exists on the system:

```
ls /lib64/libcurl*        
/lib64/libcurl.so.4  /lib64/libcurl.so.4.8.0
```

This might be, because `sunshine` requires the `CURL_OPENSSL_4` library that is not provided by the `libcurl` package:

```
rpm -q --provides libcurl
libcurl = 7.85.0-4.fc37
libcurl(x86-64) = 7.85.0-4.fc37
libcurl-full = 7.85.0-4.fc37
libcurl-full(x86-64) = 7.85.0-4.fc37
libcurl.so.4()(64bit)
libcurl = 7.85.0-4.fc37
libcurl(x86-32) = 7.85.0-4.fc37
libcurl-full = 7.85.0-4.fc37
libcurl-full(x86-32) = 7.85.0-4.fc37
libcurl.so.4
```

### Expected Behavior

Sunshune 0.16 should be installable from the rpm on Fedora 37.

```
cat /etc/os-release 
NAME="Fedora Linux"
VERSION="37 (Workstation Edition)"
ID=fedora
VERSION_ID=37
VERSION_CODENAME=""
PLATFORM_ID="platform:f37"
PRETTY_NAME="Fedora Linux 37 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:37"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f37/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=37
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=37
SUPPORT_END=2023-11-14
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

### Host Operating System

Linux

### Operating System Version

Fedora 37

### Architecture

64 bit

### Sunshine commit or version

0.16.0

### Package

Linux - rpm

### GPU Type

AMD

### GPU Model

Radeon 6700 XT

### GPU Driver/Mesa Version

22.2.3

### Capture Method (Linux Only)

Pipewire

### Relevant log output

```Shell
sudo dnf install ./sunshine.rpm     
Last metadata expiration check: 0:10:36 ago on Sat 17 Dec 2022 09:51:37 PM CET.
Error: 
 Problem: conflicting requests
  - nothing provides libcurl.so.4(CURL_OPENSSL_4)(64bit) needed by sunshine-0.16.0-1.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

**Comment by Extarys** [comment]
Similar with the AppImage on Fedora 36:
```
/usr/bin/AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
```

**Comment by dolandemort** [comment]
Can also confirm this for the `rpm` version with Fedora 37.

**Comment by gitrmarx** [comment]
Confirmed with `flatpak`, `rpm` and `AppImage` on Fedora 37.

**Comment by mbellitti** [comment]
Is there any approach that works? I'm on Fedora 37 and having the same issues.

**Comment by kstorbakken** [comment]
The libcurl package on Fedora is not built with version symbols which I believe leads to this issue. I think the best way for this to be solved will be to do some work on the build/package process in that the RPM will need to be built on Fedora or something similar rather than Ubuntu. 

You can always force install an RPM by ignoring all dependencies with `rpm -ivh packagename.rpm --nodeps`. This is not advised unless you're knowledgeable in satisfying the dependencies yourself. I haven't tested it with Sunshine but some others have reported they have it running. Otherwise you need to wait for a fix.
