### ISSUE TITLE
[Bug] Discover Application Crashes after Sunshine Installation on Steam Deck 

### ISSUE THREAD

**Issue by Eisa01** [LizardByte/Sunshine#586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

**Issue Description:**
Installing Sunshine causes Discover application to crash on Steam Deck.
Crash only occurs when accessing the `Installed` tab inside Discover application.

Also, the following error is printed when accessing Discover after Sunshine is installed.
`Error updating appstream2: no such ref 'appstream2/x86_64' in remote sunshine-origin.`

**System Information:**
Steam OS 3.3.3
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Graphics Platform: X11

### Host Operating System

Linux

### Operating System Version

SteamOS 3.3.3

### Architecture

None

### Sunshine commit or version

0.16.0

### Package

None

### GPU Type

AMD

### GPU Model

AMD Custom GPU 0405

### GPU Driver/Mesa Version

Mesa 22.0.2

**Comment by ReenigneArcher** [comment]
Where did you install sunshine from?

**Comment by Nonary** [comment]
We have not received reports recently about this issue, can you confirm if this is still present?

**Comment by Eisa01** [comment]
No crash anymore.
