### ISSUE TITLE
Blurry, shimmery text on AMD

### ISSUE THREAD

**Issue by RichardMore** [LizardByte/Sunshine#608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

When I connect to the desktop every text is blurred, shimmery
I have a screenshot of it in my Reddit post [Sunshine on AMD 7900 cards](https://www.reddit.com/r/cloudygamer/comments/zlwhrm/sunshine_on_amd_7900_cards/)
In game I have not noticed it as much but any overlay has the issue as well
Moonlight client doesn't seem to matter, TV and Windows has the same issue.
VNC connection is clear and crisp

### Expected Behavior

Clear picture when it comes to text as well as in game

### Host Operating System

Windows

### Operating System Version

Windows 11

### Architecture

64 bit

### Sunshine commit or version

0.16

### Package

Windows - installer

### GPU Type

AMD

### GPU Model

7900 XT

### GPU Driver/Mesa Version

22.12.1

**Comment by psyke83** [comment]
Just chiming in to say that the same happens to me (RX 6600). It seems to be a problem with the colour conversion and/or scaling done via shaders. It's probably beyond my capabilities to fix.

It is possible to workaround the issue by starting the encoder in a software context so it does the same colour conversion as `libx264`, but it results in higher CPU usage, capture FPS drops at times, and probably a latency increase due for the need for each frame to be transferred from GPU to system memory.

**Comment by vRobM** [comment]
I have the same issue where the text is fuzzy.

AMD 7800X3D w/ integrated GPU
Win11 w/ Sunshine and Moonlight client.

Tried various bitrate settings which all work fine, but text is not crisp and clear.
