### ISSUE TITLE
Retroarch doesn’t seem to recognize any network drives

### ISSUE THREAD

**Issue by cjnolet** [LizardByte/Sunshine#612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I’m having some major issues trying to run custom commands with Subshine. Steam seems to work great but, for example, trying to execute Retroarch as a detached command doesn’t seem to recognize any of the attached network drives (which is where all of my content lives). 

What’s strange is that if I launch a steam session and manually close steam and launch RetroArch in that same remote session, the network drives all work as usual. 

I’m also encountering issues launching Origin games, such as Battlefield V. If I run the command locally it works fine but if it run it in Sunshine then it tries to open another origin instance (which causes issues with the existing origin login session).

For the RetroArch issue, I’ve tried switching the owner of the sunshine directory (recursively) to the logged in user. I’ve also tried setting the working directory of the “Applicstion”  in Sunshine’s config to both the user’s home directory and to the directory of the RetroArch binary. 

Any ideas here? Is there something special I need to do in windows to have the detached commands recognize and run as the currently logged in user? (Using `runas` doesn’t seem to be an option here as it requires manually typing in a password at least once each session). 

 

### Expected Behavior

I’d expect that a command executed through sunshine will behave the same as if I execute the command locally on the computer’s keyboard. 

### Host Operating System

Windows

### Operating System Version

11

### Architecture

64 bit

### Sunshine commit or version

Most recent stable release

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

RTX

### GPU Driver/Mesa Version

A6000, 3090, 3080 Ti, 3070

**Comment by cjnolet** [comment]
Is it possible this could be fixed by https://github.com/LizardByte/Sunshine/pull/600?

**Comment by ReenigneArcher** [comment]
Yes, that PR will aim to fix these types of issues. The current workaround is to not use sunshine as a service.
