### ISSUE TITLE
Sunshine (With Moonlight on Nvidia Shield) can not exit BigBox on Windows (Launchbox)

### ISSUE THREAD

**Issue by KINGLIFER** [LizardByte/Sunshine#621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

If you exit out of moonlight (for whatever reason) and try to resume a session Sunshine will restart the program instead of resuming. This will intern create more than one instance. If you exit out of BigBox and attempt to relaunch the same thing also happens. the program does not quit.

There are a few other bugs when using BigBox that did not happen in GFE. If you quit an emulator or game the stream does not default back to BigBox (Launchbox). 

### Expected Behavior

If you exit out of a stream you should be able to resume the stream, not restart the program that initiated the stream. Also if you quit a stream the initiated program should end. 

### Additional Context

Using Nvidia Shield and PC with Nvidia Graphics hardware. 

### Host Operating System

Windows

### Operating System Version

11

### Architecture

64 bit

### Sunshine commit or version

Nightly 2022-12-23T03:47:48Z

### Package

Windows - portable

### GPU Type

Nvidia

### GPU Model

GeForce 

### GPU Driver/Mesa Version

latest

**Comment by ReenigneArcher** [comment]
You need to use "command" instead of "detached".
