### ISSUE TITLE
Debian packages shipping with node_modules folder

### ISSUE THREAD

**Issue by Max-Might** [LizardByte/Sunshine#636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I had the previous version deb package and it was around 3 MB and the current is ~10MB.
I did a simple `dpkg -c sunshine-22.04.deb` to list the contents of the package before I install it and it seems to be shipping the whole `node_modules` folder. I am not much of a web guy but I think this is not needed once the JS stuff is compiled and minified.
 
### Expected Behavior

node_modules not included in the debian packages

### Host Operating System

Linux

### Operating System Version

22.04

### Architecture

64 bit

### Sunshine commit or version

0.16.0

### Package

Linux - 22.04-deb

### GPU Type

AMD

### GPU Model

RX 580

### GPU Driver/Mesa Version

Default for 22.04

**Comment by ReenigneArcher** [comment]
Certainly not everything in `node_modules` is needed, but it will probably be more effort than it's worth to determine which files are not necessary.

**Comment by TheElixZammuto** [comment]
@ReenigneArcher We should probably introduce Webpack or Vite in our toolchain, this way we don't have to ship as binaries all the node_modules folder and the build process can be then automated
