### ISSUE TITLE
Drop in performance when changing refresh rate

### ISSUE THREAD

**Issue by zetalex** [LizardByte/Sunshine#641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

While playing a game, the performance depends on which refresh rate is selected. For instance, in Marvels SpiderMan main menu withouth any frame cap if 60 Hz is chosen then the game goes up to 170 fps. If 100 Hz, it gets down to 150 and if 144 Hz is selected it stays at 132 fps more or less. While not streaming, the game reaches 187 fps.
Here is a proof of it while selecting 144 Hz, going out of the stream (the peak to 187 fps) and then going back in.

![Framerate](https://user-images.githubusercontent.com/60352641/209737198-40515320-71bc-4095-8b5c-21c026073a5a.PNG)

### Expected Behavior

The fps shouldnt dip as much just by changing the refresh rate, which is a setting that doesnt affect games while playing locally.

### Host Operating System

Windows

### Operating System Version

Windows 10 22H2

### Architecture

64 bit

### Sunshine commit or version

nightly automated nightly release - 2022-12-27T20:53:10Z - 05f5370

### Package

Windows - installer

### GPU Type

AMD

### GPU Model

RX 7900 XTX

### GPU Driver/Mesa Version

AMD Adrenalin 22.12.2

**Comment by brengard0125** [comment]
There is a bug on sunshine with AMD cards. You’ll always lose about 50fps from running sunshine.

**Comment by zetalex** [comment]
Really? And should this bug be fixed from AMD or from Sunshine developers side? Latest drivers (23.4.1) brought a hefty performance improvement specially when streaming at 60 fps. You only drop from 230 to 210 fps for example at 1080p in Crysis remastered on my GPU. However, at 120 fps it loses much more and there are other games (and higher resolution) that the GPU doesn't have as much headroom.

**Comment by brengard0125** [comment]
Since parsec doesn’t lose nearly as many frames on the same encoder with the same bitrate and quality I’m going to say it’s due to either moonlight or sunshine.

**Comment by zetalex** [comment]
Mmm... Can it be related to this issue? #1040 Maybe this is causing the performance drop, as the overshot  for encoding bitrate will take more resources for encoding the video.

**Comment by brengard0125** [comment]
I don’t think so unless it’s some huge amount of bandwidth it’s trying to encode.

I just tested it and both VBR and CBR use the same amount of GPU load percentage. 

I put both parsec and sunshine on the same 150mbps bitrate, double checked parsec is indeed running at that bitrate and wiggled the sunshine command prompt box around. 

I’m getting 57% usage with sunshine and 13% usage with parsec.
