### ISSUE TITLE
Sunshine is trying to find `assets/sunshine.conf` on the current directory in Windows

### ISSUE THREAD

**Issue by sitiom** [LizardByte/Sunshine#70]
### Describe the Bug

I just installed Sunshine from [Scoop](https://github.com/ScoopInstaller/Extras/blob/master/bucket/sunshine.json) and tried to run it when I got this error:
```console
$ sunshine
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot copy file: No such file or directory [assets/sunshine.conf] [assets/sunshine.conf]
```

When I cd to the directory containing Sunshine, it works. It looks like sunshine is trying to find `assets/sunshine.conf` relative to the current directory rather than in the executable directory.

### Expected Behavior

It's supposed to find `assets/sunshine.conf` in the executable directory.

### Sunshine Host Operating System and Version

Windows 11

### Architecture

64 bit

### Sunshine Version

0.12.0

### GPU Type

Nvidia

### GPU Model

GeForce RTX 2070 SUPER

### GPU Driver/Mesa Version

511.79

**Comment by ReenigneArcher** [comment]
Here are some options for you.

- cd into binary directory before starting sunshine, `cd /d <path to sunshine> && sunshine.exe`
- create a shortcut and set the working directory to the path of your sunshine binary
- select the path of the conf file when starting sunshine, `sunshine.exe <path_to_sunshine_config>/sunshine.conf`

Most likely this is an issue with the way scoop was configured.

I'm thinking this section: https://github.com/ScoopInstaller/Extras/blob/6a6a3e8ee8cbe73f7a906a8b396974abcda4c276/bucket/sunshine.json#L21

should probably just be:
```json
    "persist": [
        "assets"
    ],
```

Not really sure though. Perhaps there are some other options that will get it working the way you intend. https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests
