### ISSUE TITLE
Playing games in windowed mode causes AMD driver timeout error

### ISSUE THREAD

**Issue by Patryk27** [LizardByte/Sunshine#718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Hi,

After playing Portal 2 for a few minutes, the streaming stops abruptly, hangs for a minute, then AMD's "driver timeout error" message appears, and the streaming continues (for another few moments, repeating this cycle); when this happens, the Windows' event log says `Display driver amdwddmg stopped responding and has successfully recovered`.

(also, it's not just the streaming - the entire system hangs as well, which I've confirmed by looking at an external display connected to the PC directly through HDMI - when this hanging happens, nothing can be done on the machine.)

I've fiddled with this for a while, checking different resolutions (didn't help) and other games (e.g. The Sims 4 works without any problems), and narrowed this issue down to (what I think is) somewhat peculiar behavior of Portal 2 - by default it starts in a seamless windowed mode -- switching the game to use fullscreen mode (just in the game's settings, nothing special) seems to resolve the issue as I've been able to play for more than an hour without witnessing any crashes.

If there's anything I can do to help in narrowing down this peculiarity, I'd be glad to help - at the very least I wanted to report it, so that fellow AMD users looking for issues can see it.

### Host Operating System

Windows

### Operating System Version

10 (22H2, 19045.2364)

### Architecture

x86-64

### Sunshine commit or version

0.16.0

### Package

Windows - installer

### GPU Type

AMD

### GPU Model

Radeon RX Vega

### GPU Driver/Mesa Version

22.11.2

**Comment by ReenigneArcher** [comment]
Is the issue present in this build? https://github.com/LizardByte/Sunshine/releases/tag/nightly-dev

**Comment by Patryk27** [comment]
Yes, I've just re-checked - the issue appears after around 6 minutes of playing Portal 2 (4k, window-less).

**Comment by Patryk27** [comment]
After searching a bit, this might be actually caused by:
https://www.reddit.com/r/Amd/comments/r05abr/help_determining_source_of_vega_64_black_screen/
... since e.g. trying to stream Cyberpunk 2077 (in fullscreen mode) fails as well, also randomly after a few minutes 👀

**Comment by Patryk27** [comment]
Okie, looks like it's related to my PSU - limiting GPU's frequency to 1408 MHz (which, in turn, makes the GPU's power draw not exceed ~220 W for prolonged periods of time) seems to have helped 🤔 

For posterity, what I've done as well was (where neither of those steps was on its own sufficient to solve the issue, but all are applied as I'm writing this comment):
- switched from daisy-chained GPU power cable to two separate power cables, attached to two separate outputs on the PSU,
- upgraded Windows 10 to Windows 11,
- switched from AMD Adrenalin Edition to AMD PRO Edition.

Anyway, since this seems to be entirely caused by something on my side, I'm just going to go ahead and close this issue.
