### ISSUE TITLE
Gamestream works with Moonlight on LG TV but Sunshine doesn't

### ISSUE THREAD

**Issue by thehhmdb** [LizardByte/Sunshine#722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

When the host is running standard Gamestream (without Sunshine), both NDL and SMP decoders work.
When the same host is running Sunshine, SMP works (but performs very poor) but NDL doesn't. NDL seems to display one frame as a still picture. Inputs are still working e.g. you can see a mouse pointer moving around on the host, but the client is frozen on that one frame.

Is there a difference between how the Gamestream and Sunshine streams are constructed and would be decoded by the TV?

### Expected Behavior

The video stream works like with Gamestream

### Additional Context

Devices and software:
Sunshine: Stable and Nightly (automated nightly release - 2023-01-07T14:43:16Z)
Moonlight version: 1.5.3
Model: CX48
webOS version 5.4.1-10
GPU: Nvidia 3080

### Host Operating System

None

### Operating System Version

Win 11

### Architecture

64 bit

### Sunshine commit or version

0.16.0

### Package

None

### GPU Type

Nvidia

### GPU Model

3080

### GPU Driver/Mesa Version

527.56

**Comment by ReenigneArcher** [comment]
You indicated the issue is present in the nightly release... which nightly release did you test?

**Comment by thehhmdb** [comment]
> 

automated nightly release - 2023-01-07T14:43:16Z

**Comment by h4de5** [comment]
similar issue here. not sure if it is related. some games work fine, some are playing for a while, but at some point, it freezes for about minute until it shows another single frame. sound continues to play as well.
it does freeze on the host as well.

if i play the same game over steams remote play, it does work without issues.

client is a lg oled tv with webos 5.

**Comment by ReenigneArcher** [comment]
Does it work with an official moonlight client?

**Comment by thehhmdb** [comment]
> Does it work with an official moonlight client?

It doesn't work with the client LG webos client from the page here (which I think is official as it's on the website):
https://moonlight-stream.org/

The same settings work with a Windows client and Sunshine server.

The nvidia gamestream server also works with the LG webos client fine.

**Comment by ReenigneArcher** [comment]
It's not an official client.

**Comment by h4de5** [comment]
just testet it with the moonlight app on android and I see the same issue there. not sure if that is official tbh.

i can test it with the moonlight client on windows only later this week.

trying the same game using the steam link android app, works fine.

**Comment by ReenigneArcher** [comment]
Thank you...

> trying the same game using the steam link android app, works fine.

This part is irrelevant.

**Comment by beatcracker** [comment]
I can confirm this, specs below.

---
**Sunshine:** Stable (0.17.0) and Nightly (automated nightly release - `2023-01-22T22:14:07Z` - `fa6c279e`)
**Moonlight version:** 1.5.3 (https://github.com/mariotaku/moonlight-tv/releases/tag/v1.5.3)
**TV Model:**  LG OLED65C25LB
**webOS version:** 7.1.0-63 mullet-maria
**GPU:** NVIDIA GeForce GTX 1070
**Host Operating System:** Windows Server
**Operating System Version:** 2022
**Architecture:** 64 bit
**GPU Driver/Mesa Version:** 528.02

**Comment by thehhmdb** [comment]
I've found that the frozen single frame won't happen if you launch moonlight with something moving on the screen. E.g. if you play a video whilst connecting with moonlight or opening steam big picture mode with it's intro video.

So for me:
Launching Moonlight with a static desktop = failure (stuck on one frame)
Launching Moonlight with a video playing = works (streams normally)

**Comment by andybloke** [comment]
Also ran into this issue. Desktop stream freezes on the first frame. Seems to be the WebOS Moonlight client as Moonlight Android functions as expected.

Steam stream works fine, and exiting Big Picture gives a working desktop stream. Seems to agree with the non static desktop thing

**Comment by RossDanbyGamer** [comment]
Appears to be an audio related issue when using LG webOS NDL + NDL Audio (Decoder Provided). If the user selects a different audio decoder other than the one provided by the video decoder such as ALSA or PulseAudio, the stream has no issues starting.

When audio is already playing before connecting, the user may switch back to using NDL Audio without the frozen static image.

**Comment by farika** [comment]
Same issue on my side.

**Comment by thehhmdb** [comment]
.
