### ISSUE TITLE
Sunshine does not start on Windows 10 with hybrid intel/nvidia graphics

### ISSUE THREAD

**Issue by kelvie** [LizardByte/Sunshine#737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Sunshine won't start on windows 10 machines with hybrid graphics (Intel/Nvidia in this case).

Pretty sure it's this:

https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/error-when-dda-capable-app-is-against-gpu

### Expected Behavior

It calls DuplicateOutput1 on the integrated card, but still uses the nvidia encoder on the discrete card.

### Host Operating System

Windows

### Operating System Version

10

### Architecture

64 bit

### Sunshine commit or version

nightly and v0.17.0

### Package

Windows - portable

### GPU Type

Nvidia

### GPU Model

GTX970M / intel integrated

### GPU Driver/Mesa Version

528.02

### Relevant log output

```Shell
[2023:01:08:23:46:06]: Warning: DuplicateOutput1 Failed [0x887A0004]
[2023:01:08:23:46:07]: Info: 
Device Description : NVIDIA GeForce GTX 970M
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x000013D8
Device Video Mem   : 3026 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16323 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:01:08:23:46:07]: Warning: DuplicateOutput1 Failed [0x887A0004]
[2023:01:08:23:46:08]: Info: 
Device Description : NVIDIA GeForce GTX 970M
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x000013D8
Device Video Mem   : 3026 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16323 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:01:08:23:46:08]: Warning: DuplicateOutput1 Failed [0x887A0004]
[2023:01:08:23:46:08]: Info: 
Device Description : NVIDIA GeForce GTX 970M
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x000013D8
Device Video Mem   : 3026 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16323 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:01:08:23:46:09]: Warning: DuplicateOutput1 Failed [0x887A0004]
[2023:01:08:23:46:09]: Info: Encoder [software] failed
[2023:01:08:23:46:09]: Fatal: Couldn't find any working encoder
```

**Comment by kcajjones** [comment]
I have a laptop with Intel i7 8750h integrated GPU Intel UHD 630 and discrete GPU Nivida GTX 1070 and have the same issue.

**Comment by kelvie** [comment]
I found a workaround -- in the nvidia control panel, add "sunshine.exe" as a "specific program", then make sure it always uses integrated graphics.

If it's set to use nvidia graphics it won't work.

**Comment by kcajjones** [comment]
> I found a workaround -- in the nvidia control panel, add "sunshine.exe" as a "specific program", then make sure it always uses integrated graphics.
> 
> If it's set to use nvidia graphics it won't work.

I didn't need this workaround as by default the program uses the integrated GPU. Forcing the program to use integrated graphics doesn't enable using nvencoder on the gpu.

**Comment by Ge082** [comment]
Same issue here, AMD iGPU and RTX 3060 laptop, Sunshine always falls back to software encoder, it sometimes see the AMD  iGPU but it always choose software encoding which kills performance, especially on emulators
