### ISSUE TITLE
ipv6 Unable to work  wish ipv6 Merge to Nightly

### ISSUE THREAD

**Issue by a396889843** [LizardByte/Sunshine#779]
wish ipv6 Merge to Nightly

Add IPv6 streaming support #571
 Draft
[cgutman](https://github.com/cgutman) wants to merge 1 commit into [LizardByte:nightly](https://github.com/LizardByte/Sunshine/tree/nightly) from [cgutman:ipv6](https://github.com/cgutman/LB_Sunshine/tree/ipv6)

**Comment by ReenigneArcher** [comment]
DO NOT open issues like this.

**Comment by a396889843** [comment]
你好，本人已经收到你邮件，谢谢！！
