### ISSUE TITLE
Keyboard layout wrong language

### ISSUE THREAD

**Issue by jackydany** [LizardByte/Sunshine#780]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

German keyboard layout is not passed to streming host - wrong character-set is used

my setup:
windows 10 VM on proxmox host. sunshine server installed, also tightVNC as backup remote solution
i am from germany, so my keyboard layout is set to german on my client and on the Win10 VM (host) as well.
but z and y are switched, also the special characters are not present. the keyboard layout through sunshine / moonlight is englisch (uk or us o dont know). There is no setting i can use to adjust this.
if i use tightVNC, everything is as expected.... german. so shit is not a client - host problem itself but should be a problem in shunshine or moonlight.

i hope someone can help me out.
thanks a lot

### Expected Behavior

use Z on keyboard and z will appear on streming host as well

### Host Operating System

Windows

### Operating System Version

10 pro

### Architecture

64 bit

### Sunshine commit or version

v0.16.0

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

nvidia P4

### GPU Driver/Mesa Version

15.0 Grid

**Comment by ReenigneArcher** [comment]
`latest` is not a version

**Comment by jackydany** [comment]
i added the version

**Comment by ReenigneArcher** [comment]
Use v0.17.0

**Comment by jackydany** [comment]
LOL ok didnt know that there was just a release last week!
ill try that in an hour or two and give some feedback!

thanks for the hint

**Comment by jackydany** [comment]
It works! Also another "error" is gone, i can start with a nvidia vGPU AND basic MS display, 2 displays.
on 0,16 it wasnt possible until i deactivated the MS display 

thanks a lot!
