### ISSUE TITLE
NSIS installer /S for chocolatey and winget

### ISSUE THREAD

**Issue by AeliusSaionji** [LizardByte/Sunshine#790]
Just making a track-able item for the changes we discussed in discord.

When the installer is invoked in silent mode (sunshine-installer.exe /S), the following should be suppressed:
https://github.com/LizardByte/Sunshine/blob/master/CMakeLists.txt#L561
https://github.com/LizardByte/Sunshine/blob/master/CMakeLists.txt#L567

specifically, launching the browser and asking the user about vigem.

Thanks!

**Comment by ReenigneArcher** [comment]
This will probably be faster if you modify CMakeLists and create a PR. https://github.com/LizardByte/Sunshine/blob/fa14b6ead7d2b7b11d466e4444631d9480aef492/CMakeLists.txt#L636
