### ISSUE TITLE
Regression: Streaming to multiple simultaneous clients seems to be broken

### ISSUE THREAD

**Issue by cathyjf** [LizardByte/Sunshine#795]
### Describe the Bug

With `channels > 1` in `sunshine.conf`, Sunshine is supposed to allow multiple devices to connect to the same stream. However, this appears to be currently broken on Windows. If one client is already in the stream, and then a second client joins, _both_ clients show nothing but black after that. The Sunshine log is flooded with this message when this occurs:

```
[2023:01:17:03:52:37]: Error: Failed to acquire encoder mutex [0x887A0001]
```

This is a recent regression. I was able to fix the problem by reverting the following three commits in order: e2fce257b53626b4f21cfc7132a1e94f781a24e1, 00aa23b3424701bbae1fa73315a22ea3d10231ed, and 0439d7a83a0deac7578043cfdf8fddadd4b46799 The reverts all apply cleanly to b2fe0423d2894aed889dd51a83dd361a72bb4231, when done in the right order. The oldest of these commits is only about two weeks old, so this regression is very recent.

### Operating System Version

Windows 11 21H2 (Build 22000.1455)

### Architecture

64 bit

### GPU Type

Nvidia

### GPU Model

GeForce RTX 3090

### GPU Driver/Mesa Version

GeForce Game Ready Driver 528.02

**Comment by cathyjf** [comment]
I just built 7f6383833c58b149f65a73d16b568c2949f2bb3d and I can confirm that the bug still exists in that version, although rather than making the video streams black, joining the second client now appears to cause `sunshine.exe` to terminate without anything notable printed to the log.

**Comment by ReenigneArcher** [comment]
We publish nightly releases here: https://github.com/LizardByte/Sunshine/releases/tag/nightly-dev

**Comment by neatnoise** [comment]
I confirm a bug.
Host: Windows 10 nightly, AMD Radeon RX 580
Client 1: MacOS 11.7.2
Client 2: iOS 16.2

**Comment by bigdrew** [comment]
I had also discovered this in release 17 and the nightly branch last week.  I reverted to a nightly build from a few weeks ago.

**Comment by ReenigneArcher** [comment]
We will close issues when the fix is in a stable release. Please leave open.
