### ISSUE TITLE
DualSense controller SHARE key not working

### ISSUE THREAD

**Issue by hhhfsj** [LizardByte/Sunshine#799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

DualSense controller SHARE key not working

### Host Operating System

Windows

### Operating System Version

21H2 19044.2364

### Architecture

64 bit

### Sunshine commit or version

0.17.0

### Package

Windows - portable

### GPU Type

Nvidia

### GPU Model

Tesla P4

### GPU Driver/Mesa Version

513.46

**Comment by TheElixZammuto** [comment]
On which Moonlight client does the issue occur?
Have you tried another client?

If you have used it before, did the same problem occur on Nvidia GFE?

**Comment by hhhfsj** [comment]
I am using MoonlightPortable version 4.3.1

My PC does not support Nvidia GFE

**Comment by hhhfsj** [comment]
![image](https://user-images.githubusercontent.com/47785500/213842836-e7d153c4-e2c3-44d4-bb53-a6a49856b704.png)

**Comment by KaosuReido** [comment]
Having similar issues on Sunshine 0.18.1, Moonlight 4.3.1, Windows 10 on both systems. Pressing Share presses the "B17" button. Pressing either side of the touchpad as a button produces:

![image](https://user-images.githubusercontent.com/49773238/216438652-99e6038d-cbd5-49cc-9e90-99ec0222399b.png)

Controller is being configured via Steam. Controller is a standard PS4 DS4, connected via Bluetooth.

If used via Steam Remote Play or Parsec, controller produces the correct output response.

**Comment by aseligmann** [comment]
I am seeing the same issue with my DS5 controller through Moonlight.

Sunshine version: 0.19.1
Using Moonlight Android.

https://github.com/LizardByte/Sunshine/issues/965
