### ISSUE TITLE
Sound 5.1 not working

### ISSUE THREAD

**Issue by c0d323r0** [LizardByte/Sunshine#818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Thank you for this project.

I migrate my setup from GFE to Sunshine but i have a problem with the sound.

I have a x86 x64 Setup with Moonlight client and my Denon X1700H AV receiver. 

Stereo Sound stream is working but 5.1 is not working. With GFE i have no problems. Maybe a bug?

I checked everything and i google it but i have no success. 

Tested with Windows 10 - Windows 11 and Android ( Shield )

Or is the BUG in the Moonlight Client?

Thanks for this wonderful project! 

 

### Host Operating System
Windows 11

### Client Operating System
Windows 10 Windows 11 and Android ( Shield )

### Architecture
x86 x64

### Sunshine commit or version
v0.17.0

### Package
Windows - installer

### GPU Type
Nvidia

### GPU Model
RTX2080Ti

### GPU Driver/Mesa Version
528.02

**Comment by bigdrew** [comment]
By default, Sunshine uses the speaker setup on the host PC which is probably stereo in your case.  You'll need to set up a virtual audio sink with a 5.1 speaker setup.  Steam streaming speakers and Scream are two easily accessible ones.  Once you've added the hardware ID to Sunshine config and choose your virtual speakers, it should work.

**Comment by Bobbar** [comment]
I had the same problem.  I was able to fix it by installing [VB-Cable](https://vb-audio.com/Cable/), creating a virtual sound device, configure it for 5.1 audio.  Then add the sink GUID to Sunshine config.

**Comment by c0d323r0** [comment]
Thank you guys. I test a virtual audio sink. But i think its a better option with include virtual 5.1 and 7.1 in sunshine already.

Maybe in the next release?

**Comment by ReenigneArcher** [comment]
As already stated, Sunshine doesn't provide any virtual sound devices. Maybe someday... probably not in the next release. Closing this for now so we can focus on current bugs.

**Comment by comienzo2093** [comment]
> https://docs.lizardbyte.dev/projects/sunshine/en/latest/about/advanced_usage.html#audio
> 
> See the tip for finding the guid/name.

thank you! I solved it. Have a nice day
