### ISSUE TITLE
Gamepads Issues

### ISSUE THREAD

**Issue by Dukobpa3** [LizardByte/Sunshine#821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Sometimes Sunshine not kills Virtual controller on closing session, and it still there forever.
Also this zombie controller at the first place and it is blocking proper working of many applications where needed "1-st controller"

Only steam big picture can operate it well because it can discover any connected controllers and not depends on their positions.

Also there issues with many controllers on client, but I'm not sure it is something different.

Current behaviour:
– After reboot pc or sunshine itself couple sessions ok but then after some session stays zombie controller at the first place forever
– Multiple controllers not working at all, only one operable in this couple first sessions

### Expected Behavior

Proper working with controllers and multiple controllers.

### Additional Context

Host – Nvidia GameStream ready PC (2060 GPU)
Tried with GS enabled and disabled but it is not depends.
With GS host Works well even with this dummy controller because GS's gamepads connecting to first place.
Sunshine connecting it's own gamepads to the end of array and losing "1-st gamepad place".

Client – Tried on Mac and Nvidia Shield TV Pro 2015.

Gamepads – Nvidia Shield Controller (2015), Xiaomi Mi Gamepad.

### Host Operating System

Windows

### Operating System Version

22H2 19045.2486

### Architecture

64 bit

### Sunshine commit or version

0.17.0

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

RTX 2060

### GPU Driver/Mesa Version

528.02

**Comment by Bobbar** [comment]
I have seen this a few times as well.  It really screws with keyboard and mouse inputs to the point I've had to hard reboot before.  

Killing/restarting the sunshine service seems to work, if you can manage to open task manager while it's in that stuck state.

**Comment by Dukobpa3** [comment]
@Bobbar 
With mouse sometimes drops focus, but I'm working like as RDP mode and switching between different monitors so maybe it is ok.

In this case enough to do right click(KB or Left Click not works in this situation) and moonlight/sunshine will recognize it again))

**Comment by Dukobpa3** [comment]
Can't play any RetroArch games with player1/player2 settings because of that

Games with many gamepads supported is ok (like battletoads or tmnt)

GS operates well

**Comment by hegemon76** [comment]
I have that issue too. My gamepad is allways 2nd or 3rd. I have tried with Xbox one bt connected gamepad and Xbox 360 with dongle. Also if i try connect Xbox one gamepad to pc with dongle after a while its connecting to 2nd gamepad slot

**Comment by lyndonguitar** [comment]
I an also experiencing this now ever since ive shield from nvidia to sunshine last march.

Sunshine doesnt kill the virtual controller made upon disconnect, and thus on reconnects it doesnt take over as player 1 and i cannot control some of my games.

The workaround was always restarting the PC. Never got around to reporting it and just settled with that workaround, but yeah today i tried to check it here on github

**Comment by JMTK** [comment]
I think #950 will resolve this
