### ISSUE TITLE
Warning: DuplicateOutput1 Failed [0x887A0004]

### ISSUE THREAD

**Issue by wangyousama** [LizardByte/Sunshine#845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I can start normally when I use AMD integrated display, but there will be errors when I replace it with NVIDIA graphics card

### Host Operating System

Windows

### Operating System Version

Windows 11 22H2

### Architecture

64 bit

### Sunshine commit or version

0.17.0

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

RTX3070 Laptop

### GPU Driver/Mesa Version

527.56

### Relevant log output

```Shell
[2023:01:28:02:20:16]: Info: Compiling shaders...
[2023:01:28:02:20:16]: Info: Compiled shaders
[2023:01:28:02:20:16]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2023:01:28:02:20:16]: Info: Trying encoder [nvenc]
[2023:01:28:02:20:17]: Info:
Device Description : NVIDIA GeForce RTX 3070 Laptop GPU
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x0000249D
Device Video Mem   : 8033 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 7886 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:01:28:02:20:17]: Warning: DuplicateOutput1 Failed [0x887A0004]
```

**Comment by TheElixZammuto** [comment]
You are using an nvidia optimus system. Your display is actually connected only on the AMD iGPU and not on the nvidia one, so Sunshine must be run on the AMD GPU to work correctly

**Comment by cgutman** [comment]
This should be fixed already in the latest nightly.
