### ISSUE TITLE
The mouse, keyboard, stops in the antivirus window.

### ISSUE THREAD

**Issue by YTOAA** [LizardByte/Sunshine#852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I don't know if this only happens in the vaccine program. But the screen is moving. It just stops the mouse keyboard.

### Host Operating System

None

### Operating System Version

windows 10

### Architecture

None

### Sunshine commit or version

nightly 23.01.29

### Package

None

### GPU Type

Intel

### GPU Model

intel uhd graphic( intel n6005)

### GPU Driver/Mesa Version

n/a

**Comment by ReenigneArcher** [comment]
You probably need to run Sunshine as a service. This is the default behavior with our installer.
