### ISSUE TITLE
Sunshine Crashes

### ISSUE THREAD

**Issue by shae23** [LizardByte/Sunshine#856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I'm not certain where to start or how to format this. Version 0.16.0 works with an issue. I install version 0.17.0, open the application, the command prompt looking window opens up and a bunch of text runs in the window, the window automatically closes after 3-5 seconds. After a minute or so, I keep getting a constant error popup. I have tried the installer and the portable version. I have tried the latest nightly build and the issue is still present, but if I go back to version 0.16.0, then the application works.

### Expected Behavior

Open the application, the command prompt looking window opens up and a bunch of text runs in the window. The window stays open and I am able to configure Sunshine or stream to my device.

### Host Operating System

Windows

### Operating System Version

Windows 11,  22H2,  22621.1194

### Architecture

64 bit

### Sunshine commit or version

0.17.0

### Package

Windows - installer

### GPU Type

AMD

### GPU Model

AMD RYZEN 4000 series  with built in APU and Nvidia 1650 TI.

### GPU Driver/Mesa Version

27.20.11028.5001 for the AMD and 31.0.15.2824 for the NVIDIA

### Relevant log output

```Shell
[2023:01:29:17:03:47]: Info: Compiling shaders...
[2023:01:29:17:03:47]: Info: Compiled shaders
[2023:01:29:17:03:47]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2023:01:29:17:03:47]: Info: Trying encoder [nvenc]
[2023:01:29:17:03:47]: Info: ddprobe.exe [1] [] returned: 0x00000000
[2023:01:29:17:03:47]: Info: Set GPU preference: 1
[2023:01:29:17:03:47]: Info: 
Device Description : AMD Radeon(TM) Graphics
Device Vendor ID   : 0x00001002
Device Device ID   : 0x00001636
Device Video Mem   : 496 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 7870 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:01:29:17:03:47]: Info: Desktop resolution [1920x1080]
[2023:01:29:17:03:47]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:01:29:17:03:47]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.149414,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:01:29:17:03:47]: Info: SDR color coding [Rec. 601]
[2023:01:29:17:03:47]: Info: Color range: [JPEG]
[2023:01:29:17:03:47]: Error: Could not open codec [h264_nvenc]: No such file or directory
[2023:01:29:17:03:47]: Info: 
Device Description : AMD Radeon(TM) Graphics
Device Vendor ID   : 0x00001002
Device Device ID   : 0x00001636
Device Video Mem   : 496 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 7870 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:01:29:17:03:47]: Info: Desktop resolution [1920x1080]
[2023:01:29:17:03:47]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:01:29:17:03:47]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.149414,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:01:29:17:03:47]: Info: SDR color coding [Rec. 601]
[2023:01:29:17:03:47]: Info: Color range: [JPEG]
[2023:01:29:17:03:47]: Error: Could not open codec [h264_nvenc]: No such file or directory
[2023:01:29:17:03:47]: Info: 
Device Description : AMD Radeon(TM) Graphics
Device Vendor ID   : 0x00001002
Device Device ID   : 0x00001636
Device Video Mem   : 496 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 7870 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:01:29:17:03:47]: Info: Desktop resolution [1920x1080]
[2023:01:29:17:03:47]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:01:29:17:03:47]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.149414,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:01:29:17:03:47]: Info: SDR color coding [Rec. 601]
[2023:01:29:17:03:47]: Info: Color range: [JPEG]
[2023:01:29:17:03:47]: Error: Could not open codec [h264_nvenc]: No such file or directory
[2023:01:29:17:03:47]: Info: 
Device Description : AMD Radeon(TM) Graphics
Device Vendor ID   : 0x00001002
Device Device ID   : 0x00001636
Device Video Mem   : 496 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 7870 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2023:01:29:17:03:47]: Info: Desktop resolution [1920x1080]
[2023:01:29:17:03:47]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:01:29:17:03:47]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.149414,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:01:29:17:03:47]: Info: SDR color coding [Rec. 601]
[2023:01:29:17:03:47]: Info: Color range: [JPEG]
```

**Comment by dtantono** [comment]
this also happened on version 0.18.0 as well

**Comment by Lapis-Apple** [comment]
I have same issue. I use AMD Ryzen 4000 too but I don't have a dGPU. This happens to both Windows 11 and 10.

**Comment by cgutman** [comment]
@dtantono That AMD driver is quite old (September 2020). Can you try downloading the latest driver from AMD's website?

@Lapis-Apple What version of the AMD driver is installed on your system?

**Comment by dtantono** [comment]
my current workaround is downgrade to version 0.16 and it works okay. But, I heard AMD official driver is quite wonky. So, I don't want risk my working OEM driver to unstable driver. What do you think?

**Comment by shae23** [comment]
> @dtantono That AMD driver is quite old (September 2020). Can you try downloading the latest driver from AMD's website?
> 
> @Lapis-Apple What version of the AMD driver is installed on your system?

I decided to forgo the OEM drivers and update from AMD's website. That solved the issue. Thank you.

**Comment by dtantono** [comment]
@shae23 @cgutman  the thing is I use a laptop and the dgpu I use is nvidia which is quite updated and may I know why Sunshine cannot point to use nvidia as a GPU?

**Comment by shae23** [comment]
> @shae23 @cgutman the thing is I use a laptop (I tried to to use admin account But, it does not worked either) and the dgpu I use is nvidia which is quite updated and may I know why Sunshine cannot point to use nvidia as a GPU?

My setup is the same. I tried to point sunshine to the nvidia gpu but that threw up a different error. The nvidia drivers are up to date, but the amd ones were behind. I updated that and it worked.

**Comment by dtantono** [comment]
Do you mean by?
Right-click anywhere on your desktop.
Click NVIDIA Control Panel.
On the left side, select Manage 3D Settings.
Select the Global Settings tab
Change the preferred graphics processor to "High-performance NVIDIA processor."?
But, the output log on Sunshine shows they detected Ryzen igpu right?

**Comment by cgutman** [comment]
The display must be connected to the GPU used for capture and encoding. See https://github.com/LizardByte/Sunshine/discussions/889#discussioncomment-4889562

Sunshine doesn't allow your GPU preference to take effect because doing so would completely break streaming entirely.

**Comment by dtantono** [comment]
@cgutman noted for that. since igpu is weaker than dgpu for gaming performance. Will this affect gaming experience?

**Comment by cgutman** [comment]
No, the frames are already being copied to your iGPU to be displayed, so there is no additional copy or impact on your dGPU when encoding with your iGPU.

**Comment by rojnwa** [comment]
Any updates on this? I have exactly the same problem on an **AMD R9 390** (driver version 22.6.1/21.09.13.02-220802a-382934C-RadeonSoftware). This is the latest version, the GPU has gone into legacy mode, no newer drivers will be released.

v0.16.0 works, every version above crashes after the "testing for available encoders".
