### ISSUE TITLE
Unable to change the resolution (widescreen)

### ISSUE THREAD

**Issue by Staubgeborener** [LizardByte/Sunshine#915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I use a widescreen monitor with the following resolution: 2560x1080 (144 Hz). When I stream to my TV using sunshine and moonlight, the resolution is not adjusted to the resolution of the TV (16:9). So it should be adjusted to 1920x1080 (60 Hz) for example. Because of the widescreen, it leads to black bars on top and without. How can I get around this?

### Expected Behavior

Automatically adjusted resolution

### Host Operating System

Windows

### Operating System Version

10 Pro

### Architecture

64 bit

### Sunshine commit or version

0.18.1

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

GeForce RTX 2070 Super

### GPU Driver/Mesa Version

528.49

**Comment by ReenigneArcher** [comment]
Sunshine doesn't change the resolution for you. Some users suggest using `qres`, you might give that a try as a do and undo command in Sunshine.

**Comment by ahmadalli** [comment]
@Staubgeborener You can find proper commands [on the docs](https://docs.lizardbyte.dev/projects/sunshine/en/nightly/about/app_examples.html#windows). But the default parameters (`SUNSHINE_CLIENT_WIDTH`, `SUNSHINE_CLIENT_HEIGHT`, and `SUNSHINE_CLIENT_FPS`) did not work for me and I ended up hardcoding the values instead.
