### ISSUE TITLE
Wrong dependency in Ubuntu 20.04 DEB package

### ISSUE THREAD

**Issue by UnasZole** [LizardByte/Sunshine#916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

After installing the Ubuntu 20.04 deb (tried the 0.18.1, and then the nightly), running "sunshine" in the terminal outputs : 

```sh
$ sunshine
sunshine: error while loading shared libraries: libboost_log.so.1.71.0: cannot open shared object file: No such file or directory
```

And indeed, the versions of libboost that were installed as deb dependencies are libboost-log1.67.0 libboost-regex1.67.0 libboost-thread1.67.0.
So it seems the binary calls a different version than the one listed in the deb dependencies.

### Expected Behavior

sunshine should run without missing library complaints.

### Host Operating System

None

### Operating System Version

Ubuntu 20.04, Linux 5.4.0-139-generic

### Architecture

64 bit

### Sunshine commit or version

0.18.1

### Package

Linux - 20.04-deb

### GPU Type

Nvidia

### GPU Model

GeForce GTX 1050 Mobile

### GPU Driver/Mesa Version

470.161

### Relevant log output

```Shell
sunshine: error while loading shared libraries: libboost_log.so.1.71.0: cannot open shared object file: No such file or directory
```

**Comment by ReenigneArcher** [comment]
Hmm... I guess the way we set it isn't working how we thought it would.

We might need to do something similar to this. https://github.com/kpeeters/cadabra2/blob/b1e0fefe3ed5b38fdb1294cf092d86777fa150f7/cmake/packaging.cmake#L1

**Comment by nacorti** [comment]
Similar problem here - only different is Nvidia T4 @ Driver Version 525.85.12

**Comment by jarq6c** [comment]
Also ran into this issue. I was able to get sunshine running by installing all the `libboost-` `1.71` equivalents on Linux Mint 20.3 (based on Ubuntu 20.04).

However, this option will not work on Ubuntu 22.04 and its derivatives. The only version of `libboost` available in Ubuntu 22.04 repos is `1.74`.  I think the only solution for these newer systems is to build boost `1.71` from source.

**Comment by ReenigneArcher** [comment]
> Also ran into this issue. I was able to get sunshine running by installing all the `libboost-` `1.71` equivalents on Linux Mint 20.3 (based on Ubuntu 20.04).
> 
> However, this option will not work on Ubuntu 22.04 and its derivatives. The only version of `libboost` available in Ubuntu 22.04 repos is `1.74`.  I think the only solution for these newer systems is to build boost `1.71` from source.

For 22.04 we build with boost 1.74.

**Comment by jarq6c** [comment]
> > Also ran into this issue. I was able to get sunshine running by installing all the `libboost-` `1.71` equivalents on Linux Mint 20.3 (based on Ubuntu 20.04).
> > However, this option will not work on Ubuntu 22.04 and its derivatives. The only version of `libboost` available in Ubuntu 22.04 repos is `1.74`.  I think the only solution for these newer systems is to build boost `1.71` from source.
> 
> For 22.04 we build with boost 1.74.

Thanks! I just noticed the 22.04 deb package in the latest release. It installed and ran without a problem.

**Comment by psyke83** [comment]
@ReenigneArcher

This should fix incorrect dependencies: https://gist.github.com/psyke83/3a9167d977dac4b1b77f9b8a458407e3

I'm not sure if it's worth submitting a PR to fix this, since the pending C++20 PR opts to remove dynamic boost support entirely.

**Comment by ReenigneArcher** [comment]
@psyke83 that looks like a good option! If you could submit a PR that would be great. I'm not sure how close the C++20 PR is as of now.

**Comment by UnasZole** [comment]
I confirm the latest deb (I took 0.18.3) no longer has the issue.
Thanks a lot for the amazingly fast fix and delivery :-)

**Comment by joezhouchenye** [comment]
Still have a similar issue with the latest deb on Ubuntu 22.04.  I am using the ubuntu-22.04-amd64.deb.

![image](https://github.com/LizardByte/Sunshine/assets/59191277/5fd5e9bd-ae83-4e95-a8b1-3edc71a4e093)

![image](https://github.com/LizardByte/Sunshine/assets/59191277/2258986c-d861-4d41-9531-c50febbe9b68)

Which package am I missing? Need to install libboost-chrono1.74.0?

**Comment by joezhouchenye** [comment]
Fixed with `apt install libboost-chrono1.74.0`

**Comment by ReenigneArcher** [comment]
Please open a new issue... While similar this is actually a very different cause.

**Comment by eboody** [comment]
getting a similar error after an arch update

`sunshine: error while loading shared libraries: libboost_locale.so.1.81.0: cannot open shared object file: No such file or directory`

**Comment by MELVARDEV** [comment]
> getting a similar error after an arch update
> 
> `sunshine: error while loading shared libraries: libboost_locale.so.1.81.0: cannot open shared object file: No such file or directory`

Same exact issue here

**Comment by ReenigneArcher** [comment]
You need to recompile.

https://github.com/LizardByte/Sunshine/issues/1600
