### ISSUE TITLE
microstutter

### ISSUE THREAD

**Issue by azriel84** [LizardByte/Sunshine#918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

PC: 9900K, 16GB 3600/14 RAM, RTX 4080, running the latest stable and afterwards nightly build. Streaming on an Apple TV 4K 1st gen via Moonlight latest version (tvOS 16.3.1). Streaming at 4K/60 fps with v-sync and triple buffering on since my displays are 60Hz both PC monitor and oled TV and not g-sync compatible. Everything on default on Sunshine web settings. 

Using both HEVC or h264, there are constant microstutters making the experience not fluid. No frame drops, steady 60 fps in every game tried with the 4080 (stray, shadow of the tomb raider, cyberpunk 2077, plague tale requiem). Disabling DwmFlush did make things somehow better but the stutters remain. Decreasing the resolution to 1440p didn't do anything neither increasing the CPU threads to 8 for the encoding process. I literally tried every combination of resolution, v-sync on/off/fast/adaptive, I always get some kind of stutter that I cannot get rid of. Steam Link has a ton of problems but it's buttery smooth with the exact same GPU settings so I guess either I am doing something wrong or it is a bug? Thanks in advance!

### Expected Behavior

No microstutters during gaming.

### Host Operating System

Windows

### Operating System Version

Window 10 22H2 OS build 19045.2546  

### Architecture

64 bit

### Sunshine commit or version

latest nightly

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

Gigabyte RTX 4080 Gaming OC

### GPU Driver/Mesa Version

528.49

### Relevant log output

```txt
[2023:02:12:19:09:19]: Info: Compiling shaders...
[2023:02:12:19:09:19]: Info: Compiled shaders
[2023:02:12:19:09:19]: Info: Trying encoder [nvenc]
[2023:02:12:19:09:20]: Info: ddprobe.exe [1] [] returned: 0x00000000
[2023:02:12:19:09:20]: Info: Set GPU preference: 1
[2023:02:12:19:09:20]: Info: 
Device Description : NVIDIA GeForce RTX 4080
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002704
Device Video Mem   : 16064 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8151 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160
[2023:02:12:19:09:20]: Info: Desktop resolution [3840x2160]
[2023:02:12:19:09:20]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:02:12:19:09:20]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.655273,0.335938]
Green Primary      : [0.325195,0.612305]
Blue Primary       : [0.154297,0.0654297]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:02:12:19:09:20]: Info: SDR color coding [Rec. 601]
[2023:02:12:19:09:20]: Info: Color range: [JPEG]
[2023:02:12:19:09:20]: Info: 
Device Description : NVIDIA GeForce RTX 4080
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002704
Device Video Mem   : 16064 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8151 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160
[2023:02:12:19:09:20]: Info: Desktop resolution [3840x2160]
[2023:02:12:19:09:20]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:02:12:19:09:20]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.655273,0.335938]
Green Primary      : [0.325195,0.612305]
Blue Primary       : [0.154297,0.0654297]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:02:12:19:09:20]: Info: SDR color coding [Rec. 601]
[2023:02:12:19:09:20]: Info: Color range: [JPEG]
[2023:02:12:19:09:20]: Info: 
Device Description : NVIDIA GeForce RTX 4080
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002704
Device Video Mem   : 16064 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8151 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160
[2023:02:12:19:09:20]: Info: Desktop resolution [3840x2160]
[2023:02:12:19:09:20]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:02:12:19:09:20]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.655273,0.335938]
Green Primary      : [0.325195,0.612305]
Blue Primary       : [0.154297,0.0654297]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:02:12:19:09:20]: Info: SDR color coding [Rec. 601]
[2023:02:12:19:09:20]: Info: Color range: [JPEG]
[2023:02:12:19:09:21]: Info: 
Device Description : NVIDIA GeForce RTX 4080
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002704
Device Video Mem   : 16064 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8151 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160
[2023:02:12:19:09:21]: Info: Desktop resolution [3840x2160]
[2023:02:12:19:09:21]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:02:12:19:09:21]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.655273,0.335938]
Green Primary      : [0.325195,0.612305]
Blue Primary       : [0.154297,0.0654297]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:02:12:19:09:21]: Info: SDR color coding [Rec. 601]
[2023:02:12:19:09:21]: Info: Color range: [JPEG]
[2023:02:12:19:09:21]: Info: 
Device Description : NVIDIA GeForce RTX 4080
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002704
Device Video Mem   : 16064 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8151 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160
[2023:02:12:19:09:21]: Info: Desktop resolution [3840x2160]
[2023:02:12:19:09:21]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:02:12:19:09:21]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.655273,0.335938]
Green Primary      : [0.325195,0.612305]
Blue Primary       : [0.154297,0.0654297]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:02:12:19:09:21]: Info: SDR color coding [Rec. 601]
[2023:02:12:19:09:21]: Info: Color range: [JPEG]
[2023:02:12:19:09:21]: Info: 
Device Description : NVIDIA GeForce RTX 4080
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002704
Device Video Mem   : 16064 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8151 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160
[2023:02:12:19:09:21]: Info: Desktop resolution [3840x2160]
[2023:02:12:19:09:21]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:02:12:19:09:21]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.655273,0.335938]
Green Primary      : [0.325195,0.612305]
Blue Primary       : [0.154297,0.0654297]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:02:12:19:09:21]: Info: SDR color coding [Rec. 709]
[2023:02:12:19:09:21]: Info: Color range: [JPEG]
[2023:02:12:19:09:21]: Error: Could not open codec [h264_nvenc]: Function not implemented
[2023:02:12:19:09:21]: Info: 
Device Description : NVIDIA GeForce RTX 4080
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002704
Device Video Mem   : 16064 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8151 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160
[2023:02:12:19:09:21]: Info: Desktop resolution [3840x2160]
[2023:02:12:19:09:21]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:02:12:19:09:21]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.655273,0.335938]
Green Primary      : [0.325195,0.612305]
Blue Primary       : [0.154297,0.0654297]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:02:12:19:09:21]: Info: SDR color coding [Rec. 709]
[2023:02:12:19:09:21]: Info: Color range: [JPEG]
[2023:02:12:19:09:21]: Info: 
Device Description : NVIDIA GeForce RTX 4080
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002704
Device Video Mem   : 16064 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8151 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160
[2023:02:12:19:09:21]: Info: Desktop resolution [3840x2160]
[2023:02:12:19:09:21]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:02:12:19:09:21]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.655273,0.335938]
Green Primary      : [0.325195,0.612305]
Blue Primary       : [0.154297,0.0654297]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:02:12:19:09:21]: Info: SDR color coding [Rec. 601]
[2023:02:12:19:09:21]: Info: Color range: [JPEG]
[2023:02:12:19:09:22]: Info: 
Device Description : NVIDIA GeForce RTX 4080
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002704
Device Video Mem   : 16064 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8151 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160
[2023:02:12:19:09:22]: Info: Desktop resolution [3840x2160]
[2023:02:12:19:09:22]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:02:12:19:09:22]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.655273,0.335938]
Green Primary      : [0.325195,0.612305]
Blue Primary       : [0.154297,0.0654297]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:02:12:19:09:22]: Info: SDR color coding [Rec. 601]
[2023:02:12:19:09:22]: Info: Color range: [JPEG]
[2023:02:12:19:09:22]: Warning: nvenc: hevc: replacing nalu prefix data
[2023:02:12:19:09:22]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2023:02:12:19:09:22]: Info: 
[2023:02:12:19:09:22]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2023:02:12:19:09:22]: Info: 
[2023:02:12:19:09:22]: Info: Found encoder nvenc: [h264_nvenc, hevc_nvenc]
[2023:02:12:19:09:22]: Info: Configuration UI available at [https://localhost:47990]
[2023:02:12:19:09:22]: Info: Registered Sunshine mDNS service
[2023:02:12:19:09:26]: Error: A UPnP device has been found,  but it wasn't recognized as an IGD
[2023:02:12:19:21:30]: Info: Web UI: [127.0.0.1] -- not authorized
```

**Comment by azriel84** [comment]
Updated with correct host OS. Thanks!

**Comment by ReenigneArcher** [comment]
logs?

**Comment by azriel84** [comment]
Uploaded the logs from webui's troubleshooting section unless you need something else? As for config you need some file from the folder or the whole folder?

**Comment by vinylen** [comment]
I can confirm that i am also experiencing microstutters. 

PC specs:
* Ryzen 5800X3D
* RTX 3080
* 32GB RAM
* Streaming locally, 1440@120fps, 150mbps

Will attach logs momentarilly

**Comment by samrold13** [comment]
Disable VSYNC and Tripple buffering on your host computer. You don't need this when streaming and it just creates issues and unnecessary input lag. Let Moonlight handle VSYNC of the stream. Enable VSYNC on the Moonlight app. I believe the IOS version of Moonlight has VSYNC turned on by default.

Go to your NVIDIA control panel and limit the global framerate to 60fps and set the video card power settings to maximum performance in case it's lowering the power draw when streaming.

**Comment by azriel84** [comment]
I have already tried that with vsync and triple buffering off. No v-sync compatible screen here. Will update to the latest nightly though and follow your suggestion with the 60 fps frame limit again maybe this fixes things. There is no vsync option in tvOS you just set the frames (60 in my case) and I have also set apple tv to 60hz instead of 59,74 of the ntsc standard just in case... Will try everything again when I return home and respond.

**Comment by samrold13** [comment]
I think you are confusing VSYNC with Variable Refresh Rate. Two different things. VSYNC and Tripple Buffering creates input lag on the stream, and it's not needed because Moonlight will handle the VSYNC part of your stream. Always leave those off on your host when streaming for the best experience. On your Apple TV make sure the frame pacing is set to smooth.

**Comment by azriel84** [comment]
No my bad I wanted to write G sync and keyboard changed it to v-sync sorry my mistake didn't see ti 😂

**Comment by azriel84** [comment]
No VRR doesn't bother me both my monitor and TV do not support it so I play with 60 fps cap all the time but I was using vsync tbh. Will try with vsync off and frame limiter and the 60hz option also in Apple TV's output. Frame pacing is always to smooth yeah, the other option didn't do anything anyway. DwmFlush enabled in Sunshine or disabled?

**Comment by azriel84** [comment]
So, I tried your suggestions + vsync off in game settings. I observed an improvement in input lag as you said, but the stutters are still there. I dunno if I am nitpicking now or not... 4K streaming Stray should be something easy. I understand having problems with cyberpunk where streaming at 4K with RT psycho settings and DLSS 3 can be taxing for the system but I am having issues in relatively light games too, considering my graphics card.

**Comment by samrold13** [comment]
Out of curiosity. Can you try streaming in 1080p on Moonlight and also reducing your in-game resolution to 1080p and see if the stutters go away. Try lowering the bitrate too if you have it too high. If the stutters go away, it may be that your router can't handle a 4k high bitrate stream.

**Comment by azriel84** [comment]
I know it can cause Steam Link works fine without stutters. Dunno what causes the issue in Moonlight with the exact same settings. AppleTV always on wire on a gigabit ethernet.

**Comment by samrold13** [comment]
The other thing I can think of is GPU scheduling on windows. Go to graphic settings on windows > default graphics settings> , and turn off Hardware-accelerated GPU scheduling. That is known to cause stutters in games.

**Comment by azriel84** [comment]
VSYNC and Tripple Buffering are off on the nvidia control panel and in the in-game settings.

GPU scheduling didn't do anything but we found the problem.

Reducing Moonlight's stream resolution to 1440p instead of 4K solved everything, even in heavy games like Cyberpunk. I continue to play the games at 4K on the host PC but Moonlight streams to the TV at 1440p and this solved everything. So the problem is clearly the handling of 4K stream.

**Comment by azriel84** [comment]
Did some more testing this morning. 1440p stream with either 1440p/4K resolution in game, seems to solve the issues either with vsync on or off. Tripple buffering is always off. There is the case of Plague Tale Requiem which still stutters in 1440p, it's one of the heaviest and GPU taxing games out there so I guess the encoder struggles as well. Everything else works fine at 1440p and the stutters begin again at 4K streams.

**Comment by azriel84** [comment]
Tested on Elden Ring too a relatively light game. Everything off, vsync, triple buffering had only the 60 fps cap on from Moonlight. Once again, every now and then microstutters at 4K stream, buttery smooth at 1440p.

**Comment by Nonary** [comment]
@azriel84 Can you try the suggestions mentioned here? I hav been wondering if the same bug exists in NVIDIA drivers in general but cannot replicate issue on my end anymore but it seems to match the same symptoms.

https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/38

**Comment by azriel84** [comment]
> @azriel84 Can you try the suggestions mentioned here? I hav been wondering if the same bug exists in NVIDIA drivers in general but cannot replicate issue on my end anymore but it seems to match the same symptoms.
> 
> [moonlight-stream/nvidia-gamestream-issues#38](https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/38)

DX12 maybe the cause of these issues tbh, cause of the RT and DLSS I am testing. I will try using DX11 and 4K streams with your suggestions and see what will happen, but with DX12 games and lower resolutions all the issues quite dissapear as you mention.

**Comment by Nonary** [comment]
> > @azriel84 Can you try the suggestions mentioned here? I hav been wondering if the same bug exists in NVIDIA drivers in general but cannot replicate issue on my end anymore but it seems to match the same symptoms.
> 
> > 
> 
> > [moonlight-stream/nvidia-gamestream-issues#38](https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/38)
> 
> 
> 
> DX12 maybe the cause of these issues tbh, cause of the RT and DLSS I am testing at 4K. I will try using DX11 and 4K streams with your suggestions and see what will happen, but with DX12 games and lower resolutions all the issues quite dissapear as you mention.

It's not exclusive to DX12, it's just that the optimized full screen API is forced on DX12 games.

DX11 games can use the same API, but it's optional.

If you can confirm the issue goes away when setting NVIDIA energy profile to maximum performance, then I know it's the same issue and an NVIDIA bug basically.

**Comment by azriel84** [comment]
I have already tried the maximum performance option and did nothing for the 4K stream. Just to make sure, you are suggesting to try 4K stream with windows or borderless window option to see if that's causing the issue? Tbh I was always trying every game with exclusive fullscreen or fullscreen, not window.

**Comment by azriel84** [comment]
> > > @azriel84 Can you try the suggestions mentioned here? I hav been wondering if the same bug exists in NVIDIA drivers in general but cannot replicate issue on my end anymore but it seems to match the same symptoms.
> > 
> > 
> > > 
> > 
> > 
> > > [moonlight-stream/nvidia-gamestream-issues#38](https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/38)
> > 
> > 
> > DX12 maybe the cause of these issues tbh, cause of the RT and DLSS I am testing at 4K. I will try using DX11 and 4K streams with your suggestions and see what will happen, but with DX12 games and lower resolutions all the issues quite dissapear as you mention.
> 
> It's not exclusive to DX12, it's just that the optimized full screen API is forced on DX12 games.
> 
> DX11 games can use the same API, but it's optional.
> 
> If you can confirm the issue goes away when setting NVIDIA energy profile to maximum performance, then I know it's the same issue and an NVIDIA bug basically.

OK so, vsync off, frame cap via nvidia control panel off, power set to maximum performance and frame limit set to 60 fps via RTSS. Stutters again while streaming at 4K. When I droped the streaming resolution from Moonlight to 1440p everything were just fine (games running at 4K still). Windowed, borderless window, fullscreen and exclusive fullscreen, all had the same issue while streaming at 4K.
