### ISSUE TITLE
Microstutter

### ISSUE THREAD

**Issue by azriel84** [LizardByte/Sunshine#919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

PC: 9900K, 16GB 3600/14 RAM, RTX 4080, running the latest stable and afterwards nightly build. Streaming on an Apple TV 4K 1st gen via Moonlight latest version (tvOS 16.3.1). Streaming at 4K/60 fps with v-sync and triple buffering on since my displays are 60Hz both PC monitor and oled TV and not g-sync compatible. Everything on default on Sunshine web settings.

Using both HEVC or h264, there are constant microstutters making the experience not fluid. No frame drops, steady 60 fps in every game tried with the 4080 (stray, shadow of the tomb raider, cyberpunk 2077, plague tale requiem). Disabling DwmFlush did make things somehow better but the stutters remain. Decreasing the resolution to 1440p didn't do anything neither increasing the CPU threads to 8 for the encoding process. I literally tried every combination of resolution, v-sync on/off/fast/adaptive, I always get some kind of stutter that's really annoying because 1: Steam link doesn't have this and 2: I prefer to use Sunshine to Steam Link because of the better gamepad support.

### Expected Behavior

No microstutters

### Host Operating System

Windows

### Operating System Version

Window 10 22H2 OS build 19045.2546

### Architecture

64 bit

### Sunshine commit or version

latest nightly - 02/10/2023

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

RTX 4080

### GPU Driver/Mesa Version

528.49

**Comment by ReenigneArcher** [comment]
Are you trying to get banned from the repo? Update your other issue and fill out the entire template.

**Comment by azriel84** [comment]
How can I access my other issue since I've closed it and reopened this one? Missed the Host OS section of the template and couldn't find how to edit it properly (choose an OS from a list) sorry I don't use github often
