### ISSUE TITLE
`error: ‘xdisplay_t’ does not name a type` with `SUNSHINE_ENABLE_X11=0`

### ISSUE THREAD

**Issue by greyltc** [LizardByte/Sunshine#932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

building with `SUNSHINE_ENABLE_X11=0` fails with this compile error:
```
In file included from Sunshine/src/platform/linux/kmsgrab.cpp:21:
Sunshine/src/platform/linux/x11grab.h:46:56: error: type/value mismatch at argument 2 in template parameter list for ‘template<class T, typename util::Function<void, T*>::type function> using safe_ptr = util::uniq_ptr<T, util::Destroy<T*, void, function> >’
   46 | util::safe_ptr<_XDisplay, std::default_delete<_XDisplay>>;
      |                                                        ^~
Sunshine/src/platform/linux/x11grab.h:46:56: note:   expected a constant of type ‘typename util::Function<void, T*>::type’, got ‘std::default_delete<_XDisplay>’
Sunshine/src/platform/linux/x11grab.h:56:1: error: ‘xdisplay_t’ does not name a type; did you mean ‘display_t’?
   56 | xdisplay_t make_display() { return nullptr; }
      | ^~~~~~~~~~
      | display_t
```

### Expected Behavior

the build to complete without error

### Host Operating System

Linux

### Operating System Version

Arch is a rolling release distro

### Architecture

64 bit

### Sunshine commit or version

0.18.2

### Package

None

### GPU Type

Intel

### GPU Model

n/a

### GPU Driver/Mesa Version

22.3.4

### Relevant log output

```Shell
see above
```

**Comment by ReenigneArcher** [comment]
@greyltc I tried to mention you on the PR, but got no response. If you'd like your PR reviewed and merged, please edit the PR body to use our PR template. If I don't get a response here, I'll close both this issue and the PR. Thanks.
