### ISSUE TITLE
IddSampleDriver no longer works properly on latest version

### ISSUE THREAD

**Issue by Desouler** [LizardByte/Sunshine#948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Hi all,

On 17.0 version i used IddSampleDriver to create a virtual monitor with 4k resolution and everything worked. On version 18.3, instead of sunshine choosing NVIDIA GPU, it chooses the Intel GPU from the CPU, and i get no video output message on moonlight. If i force the NVIDIA card with adapter_name in the configuration, sunshine no longer starts. If i revert back to 17.0 release everything works again.

### Host Operating System

Windows

### Operating System Version

Windows 10 Latest

### Architecture

None

### Sunshine commit or version

18.3

### Package

None

### GPU Type

None

### GPU Model

1080 Ti

### GPU Driver/Mesa Version

Latest

**Comment by ReenigneArcher** [comment]
Please edit your issue and add your log output.

**Comment by Erfboom** [comment]
I second this. I can create a new virtual monitor just fine. If I try to choose it in sunshine, I receive a no video output error in my moonlight client. Sunshine will then fail to start and I have to edit the conf file to remove the display adapter setting. I can recreate this behavior and attach logs if you guys want? The logs are in the troubleshooting tab of sunshine?

**Comment by ReenigneArcher** [comment]
Logs would be helpful. Yes they're in the troubleshooting tab.

**Comment by ReenigneArcher** [comment]
No logs provided, so closing.

**Comment by Nonary** [comment]
Fixed with #3002
