### ISSUE TITLE
Portrait resolution failed on Windows 11

### ISSUE THREAD

**Issue by linyf2008** [LizardByte/Sunshine#951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Tested Resolution: 1440x2560, 720x1280
Client APP: Moonlight for Android
Result: black screen with audio for a few seconds, then got disconnected.

### Host Operating System

Windows

### Operating System Version

11 Home

### Architecture

64 bit

### Sunshine commit or version

0.18.3

### Package

Windows - installer

### GPU Type

Intel

### GPU Model

Iris Xe Graphics

### GPU Driver/Mesa Version

31.0.101.4091

**Comment by VrTech** [comment]
happen the same with steam deck landscape mode
