### ISSUE TITLE
Audio switches from Sink to Default a few seconds after stream start

### ISSUE THREAD

**Issue by skellycode** [LizardByte/Sunshine#976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Launching Steam Big Picture (whilst the audio sink is -blank- and the virtual sink is set to the ID of Steam Streaming Speakers) causes the streamed audio to start coming out of the client and not the host (as expected) for 3-5 seconds, before suddenly switching back to coming out of the host and not the client (not expected).
The switch happens part-way through steam big picture playing its loading sound, so it is clear what is happening.

There are zero errors/warnings or pieces of useful information that are presented in the logs for me to attach, unfortunately.  The logs simply show the stream starting, and then me disconnecting it when I exit.

As a workaround I can go back to my PC and manually choose the Steam Streaming Speakers (via Windows) once the stream has loaded, however this is not possible when I am not am home.

### Host Operating System

Windows

### Operating System Version

Windows 11

### Architecture

64 bit

### Sunshine commit or version

0.18.3

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

RTX 3070

### GPU Driver/Mesa Version

528.49

### Config

```Shell
amd_usage = ultralowlatency
origin_pin_allowed = pc
amd_vbaq = enabled
gamepad = ds4
upnp = disabled
resolutions = [
    1920x1080,
    3860x2160
]
nv_preset = default
nv_tune = ull
output_name = \\.\DISPLAY1
min_log_level = 2
adapter_name = NVIDIA GeForce RTX 3070
nv_coder = auto
amd_preanalysis = disabled
qsv_coder = auto
amd_quality = default
vt_software = auto
amd_coder = auto
origin_web_ui_allowed = lan
dwmflush = enabled
nv_rc = auto
virtual_sink = {0.0.0.00000000}.{c5a978e1-6180-4295-8c2a-0d44608a2162}
encoder = nvenc
amd_rc = auto
qsv_preset = medium
fps = [30,60,90,120]
vt_coder = auto
vt_realtime = enabled
hevc_mode = 0
key_rightalt_to_key_win = disabled
```

### Apps

```json
{
    "env": {
        "PATH": "$(PATH);C:\\Program Files (x86)\\Steam"
    },
    "apps": [
        {
            "name": "Steam Big Picture",
            "output": "steam.txt",
            "detached": [
                "steam steam:\/\/open\/bigpicture"
            ],
            "image-path": "steam.png",
            "prep-cmd": [
                {
                    "do": "C:\\Users\\USERNAME\\QRes.exe \/x 3840 \/y 2160",
                    "undo": "C:\\Users\\USERNAME\\QRes.exe \/x 3440 \/y 1440"
                }
            ]
        }
    ]
}
```

### Relevant log output

```shell
None.
```

**Comment by Maz111111** [comment]
Same issue here
As a workaround I use nircmd and add a do and undo like this
Do:
nircmd setdefaultsounddevice "Stream LS"
undo:
nircmd setdefaultsounddevice "local LS"

**Comment by skellycode** [comment]
Thank you for the workaround!

**Comment by Maz111111** [comment]
I did it nearly the same way. Besides that I put the nircmd.exe in my windows directory and I put smthg. in both audio sink and virtual sink.
I think I couldn't solve the problem with leaving audio sink blank.
In audio sink I put  an unused audio output - so it is "muted" while streaming - I also had a result during my tests, that I had sound on both client and host simultaneously.
In virtual sink I put the steam streaming speakers

**Comment by skellycode** [comment]
Thank you!

Putting in a set of unused speakers in the audio sink was the missing piece of the puzzle to get the NirCmd workaround to work!

I'll leave this bug report open as I would still consider it a bug, but happy with the workaround in the interim.

Thanks again @Maz111111 ❤️

**Comment by Nonary** [comment]
I've tested this myself and could not replicate the issue, my guess is you may have some audio software in the background that is automatically swapping it back (such as SteelSeries headsets for example)

**Comment by Maz111111** [comment]
not that I know.
It is not that it not switches back at all - in my case - it switches allways to the unused USB Sound output and not to the main output, that was selected before.
Maybe it depends on the fact, that I use nvidia High Def Sound direct via the HDMI to my Monitor.
It seems as if sunshine did not recognize the highdevsound as a sounsoutput

**Comment by Maz111111** [comment]
I've just tested it again.
When I leave audio and virtual sink blank, it works. 
But when I use moondeck it doesn't. 
When the stream starts I can hear the sound for some seconds over the steamdeck. Then it switches back and the sound is on the monitor again while the steamdeck is quiet.
It seems, that I use my steamdeck a lot and only tested it with moondeck. 
Since MoonDeck starts Steam in Big Picture Mode I now tested to stream Steam . And that seems to be the problem. As soon as Steam has started in BigPictureMode the audio switches back.
It seems that Steam BP turns off the streaminspeakers

**Comment by ReenigneArcher** [comment]
In Steam can you enable this option to see if it resolves the issue.

![image](https://user-images.githubusercontent.com/42013603/224119134-bc971a7b-279b-4c72-ae86-7736c87c4fa8.png)
![image](https://user-images.githubusercontent.com/42013603/224119266-a9fb58b8-16c0-4d34-8338-817a9fb38a95.png)

**Comment by Maz111111** [comment]
I just tried this on my own and it changed nothing.
But when steam is already running (e.g. in the tray) before establishing the stream with steam bigpicturemode everything works.

**Comment by Maz111111** [comment]
And it works if I put my unused realtek usb Audio device into audio sink and the steam streaming speakers in the virtual sink.
Problem here is that: after the stream has ended the host swichtes to the usb device and i have to switch manually to the nvidia highdev.

**Comment by Maz111111** [comment]
It seems to be solved after I completely deleted sunshine.conf, restart sunshine and don't change anything in the webUI.

**Comment by Maz111111** [comment]
Ok, unfortunately something seemed to have gone wrong during testing.
The problem persisted. It had nothing to do with deleting sunshine.conf.

It looks like I was able to solve it now by switching the unused USB audio device to "disallow" audio in the windows system settings (I don't know how this switch is named in the English version) and the NvidiaHighDef Sound device still set as standard.

There may be a problem with the interaction of the new BigPictureMode and Sunshine if more than one audio device is activated in the system settings.

For the moment it seems to be working for me.

**Comment by Nonary** [comment]
I think I found the cause, it appears that if you have Steam Streaming Speakers on the machine and you have Mute Audio enabled, it will automatically change the default audio to Steam Streaming Speakers, regardless if you have a virtual sink configured or not.

It's probably hardcoded in Sunshine somewhere, will look at it later today.

**Comment by Nonary** [comment]
Nope, its just something weird with Steam Streaming speakers I guess 

/shrug

It's not doing it for me anymore.

**Comment by cgutman** [comment]
This test build should fix the issue: https://github.com/LizardByte/Sunshine/suites/12732422498/artifacts/684013547

**Comment by Maz111111** [comment]
As far as I've tested, moonlight now reliably switches to the virtual speakers when the stream starts. Unfortunately, when leaving the stream, my PC does not switch back to the original speakers. So I would say it hasn't been fully resolved yet.
Can someone else please test who originally had the same problem.

**Comment by cgutman** [comment]
@Maz111111 can you detail the exact steps you followed to trigger the issue? Also did you manually specify a "Audio Sink" or "Virtual Sink" in the config?

I tried these steps with no audio/virtual sink and it switched back just fine:
1. Set the default audio device to something that's not Steam Streaming Speakers
2. Start "Steam Big Picture" using the built-in shortcut from a Moonlight client
3. Observe the Steam Streaming Speakers becomes the default audio device
4. Chose the "Exit Steam Big Picture" option
5. Disconnect Moonlight from the PC
6. Observe that the original audio device is now the default again

**Comment by Maz111111** [comment]
After you released the new version, I initially left audio and virtual sink blank and deleted every nircmd command in my do's and undo's and all my batch files.
I'm not sure now.
I have now - after your post above - entered my standard speakers as audio sink and left virtual sink empty. "Apply" and "Safe"
This results in me having sound on the host and client at the same time.
Then I deleted the entry in audio sink again and left both empty. "Apply" and "Safe"
Now everything seems to be working as expected. Even after a restart of the PC.
I'll keep watching. For the moment everything seems to be working.
Thank you for the great work.
BTW I can see the speakers switch to the Steam speakers when the stream starts and then shortly thereafter switch back to my default speakers for less than a second and then immediately switch back to the Stream speakers.
So everything seems to be working as desired.
Thanks again.

**Comment by skellycode** [comment]
This release (v0.20.0) has completely broken any ability to select any speakers for me.
My existing solution no longer works after updating (sound only comes from host).
I have tried every permutation of Audio Sink/Virtual Sink and using my DO/UNDO nircmd (literally every combination - including blanks) and in every single case audio only comes out of the host.  When I manually change speakers to Steam Streaming Speakers, it also won't restore back to my normal speakers after ending the stream.
I've adjusted the log level to debug and read through, but no clues.  I am at a complete loss as to how to resolve...
I have regrettably had to downgrade to v0.19.1 again and restore my previous configuration.

Anyone else with this problem?

**Comment by ReenigneArcher** [comment]
Leave audio and virtual sink blank. Sunshine will automatically use Steam Streaming Speakers if found (on Windows).

**Comment by skellycode** [comment]
Have done exactly that.  I have also removed my NirCmd DO/UNDO methods as well, so it's pretty much a 'vanilla' setup.
I also uninstalled the steam streaming speakers via device manager and let sunshine install them when starting steam big picture mode.  Again, same issue.  Audio on host, no audio on client.

**Comment by Maz111111** [comment]
Try the following:
Just figure out the correct name of your standard speakers with audio tools. Put the name in audio sink and safe and apply. Try if it works.
After that delete the entries and leaf the fields blank again. Test it again. Some of this steps helped in my configuration to make it work.
But as you can read above, the switch back to standard speakers works sometimes and sometimes not.
It seems it has sthg to do with the fact, if the sunshine UI was open befor start streamin. But I am not sure. I didn't test it in the last time.
Normally I've accepted to switch back manually as soon as I am back on my PC again.
Just give it a try. Nothing to loose so far.

**Comment by skellycode** [comment]
tried your suggested method @Maz111111 but no luck 😢

**Comment by skellycode** [comment]
Ok well this is odd.  I tried restarting my computer (yet again) - but this time opened up a stream WITHOUT opening up the sunshine UI - as @Maz111111 mused - and it worked!
So it looks like this might be a different bug now... opening the Sunshine UI stops the correct audio device from being selected...
At least this isn't an issue 99% of the time! 😆

**Comment by cgutman** [comment]
Well that's very strange. No Sunshine behavior should depend on whether the UI was opened or not. Can you file a new bug for this?

When you do, please also provide this information:
- Do you have the "Play audio on host PC" option checked in Moonlight?
- Are you using the portable or installer version of Sunshine?
- Is Sunshine configured to start on boot?
- How exactly are you opening the Sunshine UI (Start Menu shortcut or just navigating in your web browser)?
- What are your Audio Sink and Virtual Sink options set to?
- What device are you expected Sunshine to select and which one is selected instead?
