### ISSUE TITLE
Multiple Client Sessions - 1st session FPS is forced on all subsequent clients

### ISSUE THREAD

**Issue by Nonary** [LizardByte/Sunshine#984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

When using the channels feature for multiple sessions, the framerate will be locked to the first session. Meaning if the first stream asked for 120fps, it does not matter what the other clients ask for... they will be forced to run at 120fps.

### Expected Behavior

Subsequent clients should be able to ask for different framerate, at the very least... ones lower than the first session should be fine. 

### Additional Context

It might be much more difficult to fix the scenario where the first user asks for 30fps and subsequent clients ask for 60/120fps, but like mentioned above we should focus on allow clients request a lower framerate from a higher one.

### Host Operating System

Windows

### Operating System Version

11

### Architecture

64 bit

### Sunshine commit or version

0.18.4

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

4090

### GPU Driver/Mesa Version

528.49

### Config

```Shell
N/A
```

### Relevant log output

```shell
N/A
```

**Comment by Nonary** [comment]
This one is going to be very difficult to fix from my observations. It has to do with how the capture/encoding is being shared to all sessions and essentially, the capturing rate is determined by the first session. It doesn't seem like it would be possible to have the sessions have a different framerate than the main session.

Perhaps it might be possible if Moonlight enforced a frame limit?

Tagging @cgutman for some food for thought on that.

**Comment by shodanx2** [comment]
Maybe the sunshine server could just drop the excess frames that aren't key frames ?
Encoder resources would still be wasted on those frames but that would save the bandwidth 

If not, maybe spawn a second encoder process (maybe easier to just run a second sunshine instance)?

In my case I have a center monitor running at 4k120hz and four side monitors running at 60Hz (maybe even 30Hz depending on bandwidth)

Using ffmpeg I noticed great performance improvements encoding multiple adjacent monitor with a single process and then cropping them for each client, I assume this is how sunshine does multiple monitors so the encoding of multiple monitors cannot occur at various framerates.
